### ISSUE TITLE
Structure information endpoint miss-consistency

### ISSUE THREAD

**Issue by warlof** [esi/esi-issues#1000]
# Bug

When I'm requesting a non-existent structure information, I'm getting 403 response instead 404 one.

## Request

`GET /latest/universe/structures/1/?datasource=tranquility`

### Status Code

`403`

### Headers

``` 
 date: Mon, 30 Jul 2018 06:12:20 GMT 
 status: 403 
 x-esi-error-limit-remain: 99 
 x-esi-error-limit-reset: 40 
 x-esi-request-id: b7507c66-14ea-4466-bd2a-819f723f7538
```

### Body

```json
{
  "error": "Forbidden"
}
```

## Expected

`404`

```json
 {
    "error": "The structure does not exists"
 }
```

# Checklist

Check all boxes that apply to this issue:

- [x] Bug description is provided
- [x] Request path is provided
- [x] Response status code is provided
- [x] Response headers are provided
- [x] Response body is provided
- [x] Expected response is provided

**Comment by lukasni** [comment]
I would argue that it shouldn't ever return 403, instead returning 404 for both non-existent structures and structures the authed character doesn't have access to. Keep 401 for unauthed requests, obviously.

**Comment by ccp-zoetrope** [comment]
Taken from the description for this route: ![screenshot_195](https://user-images.githubusercontent.com/28647795/43387093-15b6569e-93d5-11e8-92bc-4c96d49b38f3.png)

As @Aidansavage pointed out this is for intel purposes 😃.

**Comment by kennethjor** [comment]
@lukasni If you request information for a structure that you do not have access to, then a 403 is appropriate. FWIW S3 does the same thing, it's quite a common thing in the API world.

**Comment by warlof** [comment]
@ccp-zoetrope so how to know of we're doing shit or not when attempting to resolve something supposed to be a structure id but is not ? 

😐

**Comment by GoldenGnu** [comment]
Customs Offices location_id's should the only ids you can't know if is a structure or not.
...or are there any other, I don't know about?
For Reference: 
Resolving Customs Offices feature request: #685

**Comment by warlof** [comment]
Let's say I'm sending an id to resolve thinking it's a structure whereas it's a container affaict.

The endpoint will tell me I don't have access, not I'm actually doing shit by sending a wrong id (this is a dummy sample)

Also, esi scheme for this endpoint is wrong as 404 will never be returned according to your say 😐
