### ISSUE TITLE
specification missing consumes for form/body objects

### ISSUE THREAD

**Issue by antihax** [esi/esi-issues#1003]
Consumes information is missing for form/body objects and fails to generate a client for any language with the latest codegen generator.

This may include but not limited to:

- post_characters_character_id_fittings_fitting
- post_characters_character_id_mail_mail
- put_characters_character_id_mail_mail_id_contents
- put_fleets_fleet_id_new_settings
- post_fleets_fleet_id_members_invitation
- put_fleets_fleet_id_members_member_id_movement
- put_fleets_fleet_id_squads_squad_id_naming
- put_fleets_fleet_id_wings_wing_id_naming
- post_ui_openwindow_newmail_new_mail
- post_characters_character_id_mail_labels_label
- put_characters_character_id_calendar_event_id_response

Error received is:

```[main] WARN  o.o.codegen.DefaultCodegen - The following schema has undefined (null) baseType. It could be due to form parameter defined in OpenAPI v2 spec with incorrect consumes. A correct 'consumes' for form parameters should be 'application/x-www-form-urlencoded' or 'multipart/form-data'```

**Comment by a-tal** [comment]
shouldn't the global consumes be used when not overridden?

**Comment by antihax** [comment]
The code generator is broken
