### ISSUE TITLE
esi.evetech.net doesn't redirect properly when trailing / is missing

### ISSUE THREAD

**Issue by skiedude** [esi/esi-issues#1004]
# Bug

The redirect of urls not ending in `/` is no longer present. Visiting the following URLs in browser fail to load the swagger UI.

## Request

`https://esi.evetech.net/legacy`
`https://esi.evetech.net/latest`
`https://esi.evetech.net/dev`

### Status Code

`404`

### Body

```
Failed to load resource: the server responded with a status of 404 ()
legacy:14 Uncaught ReferenceError: $ is not defined
    at legacy:14
legacy:95 Uncaught ReferenceError: $ is not defined
    at legacy:95
```

## Expected

`200`

# Checklist

Check all boxes that apply to this issue:

- [x] Bug description is provided
- [x] Request path is provided
- [x] Response status code is provided
- [ ] Response headers are provided
- [x] Response body is provided
- [x] Expected response is provided

**Comment by a-tal** [comment]
resolved, thanks
