### ISSUE TITLE
Request: add Wormholes Collapsed to /characters/{character_id}/stats/

### ISSUE THREAD

**Issue by LuxNitor** [esi/esi-issues#1008]
# Feature Request

Add the number of wormholes a character has collapsed (i.e. last jump while rolling a hole as it collapses. "Have you been trapped?" message.)

## Use case

Players living in wormholes often "roll" their holes many times each day to find content. It would be interesting to see how many a character has collapsed themselves.

## Authentication

Same auth as the existing parent /characters/{character_id}/stats/

## Example return

```json
[
  {
    "character":{
      "travel":{
        "wormholes_collapsed": 16,
      },
    },
  },
]
```

# Checklist

Check all boxes that apply to this issue:

- [x] Feature request description is provided
- [x] Use case exists
- [ ] Feature requires a new route
- [x] Feature adds data to existing route
- [ ] Feature requires new auth scope
- [x] Feature can reuse existing scope
- [ ] Feature does not require auth
- [ ] Meta feature, applies to all routes

**Comment by lukasni** [comment]
Closing this since the character stats endpoint has been deprecated and is no longer being updated.
