### ISSUE TITLE
Corporations Blueprints missing blueprints

### ISSUE THREAD

**Issue by GoldenGnu** [esi/esi-issues#1009]
# Bug

Starting today (2018-08-12) all blueprints in the group `Capital Construction Blueprints` are missing from corporation blueprints endpoint.

## Request

`GET /corporations/{corporation_id}/blueprints/?datasource=tranquility`
Reproduced with corporation `Zansha Omega`

May or may not affect the character endpoint too (not sure)
`GET /characters/{character_id}/blueprints/`

## Response

I don't own any `Capital Construction Blueprints` blueprints, so, I'm not able to provide this...

### Status Code

`200`

### Headers

I don't own any `Capital Construction Blueprints`, so, I'm not able to provide this...

### Body

I don't own any `Capital Construction Blueprints`, so, I'm not able to provide this...

## Expected

`200`

Include all blueprints, no matter the group...

# Checklist

Check all boxes that apply to this issue:

- [X] Bug description is provided
- [X] Request path is provided
- [X] Response status code is provided
- [ ] Response headers are provided
- [ ] Response body is provided
- [ ] Expected response is provided

**Comment by tsuthers-ccpgames** [comment]
It seems unlikely that this is a bug for the following reasons:
a) it started happening on a Sunday, and code is not deployed on weekends
b) it is about an extremely specific set of blueprints

We need way more information to debug this, a list of exactly which blueprints were expected and not found would help. Were they originals, copies, in use, just finished doing something? Etc.

My initial suspicion would be that something like this has happened: https://github.com/esi/esi-issues/issues/611

Is this seen by anyone except the given corporation?

**Comment by GoldenGnu** [comment]
Here is a bit of extra info:
They are all in active industry job, with the activity being copy.
None of them where not started or finishing today.
The guy who reported it to me is `@charliedimaggio` on slack
I will try to contact him to get some `item_id`'s for you to work with.

I'm very sorry for the weak bug report. I should know better...

**Comment by GoldenGnu** [comment]
Here are the item_id’s missing from the corporation blueprints endpoint.
```
1026828847959
1026828804452
1026828859210
1026829097295
1026828876957
1026829092062
1026829038196
1026828845585
1026829191224
1026833448530
1026828854104
1026828814530
1026828842950
1026829034294
1026828849722
1026828807157
1026829094738
1026828852318
1026828808684
1026829032455
```
Let me know if I can provide any more info.

**Comment by tsuthers-ccpgames** [comment]
A random sample of about 6 of these item ids found that they were all in use.

I would expect them to be showing up in the /v1/corporations/{corporation_id}/industry/jobs/ route, similar to how in the game client once a blueprint is in use it stops showing up in the industry/blueprints window and starts showing up in the industry/jobs window.

Can anyone confirm?

**Comment by GoldenGnu** [comment]
Yes, they are all included in `/v1/corporations/{corporation_id}/industry/jobs/`
However, The blueprints endpoints have always included all blueprints in use, so it's not expected behavior, that they're left out of the blueprints endpoint.

**Comment by tsuthers-ccpgames** [comment]
Got some item ID's for blueprints in use that are returning I can take a peek at?

**Comment by GoldenGnu** [comment]
I hope these will work (kindly provided by Charlie Dimaggio):
```
1026944916637
1026983882770
1026981246685
1026983585930
1026983745781
1028045637354
1027624232876
1026983881766
1026983747052
1026983583600
1026981264070
1027624228301
1027286229952
1028045468410
```

**Comment by GoldenGnu** [comment]
The above industry jobs are now finished. The have been installed in new industry jobs and are now returned by the blueprint endpoint. This may have been a onetime thing. Not sure if I should close or not?

**Comment by ccp-zoetrope** [comment]
Since this may have been a one time thing I am going to close this issue. However if you see it again please re-open this.
