### ISSUE TITLE
422 - Yet receiving an invalid kill_id/hash message

### ISSUE THREAD

**Issue by cvweiss** [esi/esi-issues#1018]
# Bug

https://esi.evetech.net/latest/killmails/71690882/bf9ec357b0c1b144ba5a5fb7782ea6633b6993fb/

Returns an http code of 422 instead of a 404 and provides this content:

    {"error":"Invalid killmail_id and\/or killmail_hash"}

## Request

No auth or tokens requried.

### Status Code

`422`

### Headers

```
> GET /latest/killmails/71690882/bf9ec357b0c1b144ba5a5fb7782ea6633b6993fb/ HTTP/1.1
> User-Agent: curl/7.26.0
> Host: esi.evetech.net
> Accept: */*
> 
* additional stuff not fine transfer.c:1042: 0 0
* HTTP 1.1 or later with persistent connection, pipelining supported
< HTTP/1.1 422 Unprocessable Entity
< Date: Mon, 27 Aug 2018 05:44:25 GMT
< Content-Type: application/json; charset=UTF-8
< Content-Length: 53
< Connection: keep-alive
< Access-Control-Allow-Credentials: true
< Access-Control-Allow-Headers: Content-Type,Authorization,If-None-Match,X-User-Agent
< Access-Control-Allow-Methods: GET,HEAD,OPTIONS
< Access-Control-Allow-Origin: *
< Access-Control-Expose-Headers: Content-Type,Warning,ETag,X-Pages,X-ESI-Error-Limit-Remain,X-ESI-Error-Limit-Reset
< Access-Control-Max-Age: 600
< Allow: GET,HEAD,OPTIONS
< Strict-Transport-Security: max-age=31536000
< X-Esi-Error-Limit-Remain: 98
< X-Esi-Error-Limit-Reset: 35
< X-Esi-Request-Id: 6c93af55-419e-4bca-a451-0a8d44d5826f

```

### Body

Please provide the response body, feel free to scrub any opsec details you wish. E.g.:

```json
{
    "error": "Invalid killmail_id and/or killmail_hash"
}
```

## Expected

Not sure, is this an actual 404, or was there a problem on the backend in processing this mail and it should be a 200?

# Checklist

Check all boxes that apply to this issue:

- [X] Bug description is provided
- [X] Request path is provided
- [X] Response status code is provided
- [X] Response headers are provided
- [X] Response body is provided
- [X] Expected response is provided

**Comment by cvweiss** [comment]
A couple more:

https://esi.evetech.net/v1/killmails/72347479/de690beb0669613d7b2582ba2c6265d6b2d9cc47/ 
https://esi.evetech.net/v1/killmails/72347396/2bf333650cd0ce13dd80d44554465c7823663089/

**Comment by tsuthers-ccpgames** [comment]
422 is listed as the response code in the spec for incorrect hashes, looks like situation normal?

**Comment by cvweiss** [comment]
If that's the case then yea its a non-issue, at the time I created this ticket invalid killmail urls were returning a 404, so it was an inconsistency at minimum.
