### ISSUE TITLE
Make /universe/structures/{structure_id}/ not return a error if a structure is inaccessible.

### ISSUE THREAD

**Issue by Lucius-Q-User** [esi/esi-issues#1019]
# Feature Request
If a structure with passed id exists but is inaccessible, make the route return a different kind of an error object, one that doesn't count against the esi error limit.

## Use case

The primary usecase is together with the public contracts endpoint. It will make it possible to display names for the structures that contain contracts without requiring the client to "poke" each structure id and risk exhausting the error limit.

## Authentication

Can be rolled into the read-structures api key.

## Example return
Return the response below instead of all the fields in the standard response.
```json
{"error": "Structure inaccessible"}
```

# Checklist

Check all boxes that apply to this issue:

- [x] Feature request description is provided
- [x] Use case exists
- [ ] Feature requires a new route
- [x] Feature adds data to existing route
- [ ] Feature requires new auth scope
- [x] Feature can reuse existing scope
- [ ] Feature does not require auth
- [ ] Meta feature, applies to all routes

**Comment by a-tal** [comment]
negatory, this is by design.

stay tuned for a structure browser type endpoint, character-scoped returning all structures that character can dock at (#616)
