### ISSUE TITLE
Scope doesnt exist - esi-universe.read_structures.v1

### ISSUE THREAD

**Issue by AndersDit** [esi/esi-issues#1030]
When trying to include this scope (esi-universe.read_structures.v1) in the requested scope when fetching a an access token esi reports the following:

"error":"invalid_scope","error_description":"The requested scopes either don't exist, or are not valid for this client"}"

I get this error as soon as i try to login on the eve website after being redirection, thus i dont get to choose  character and so it cannot be that my characters dont have access to the information in the game and therfore it must be that the scope does not exist.

This is the only api documented under universe that has a "lock" on it. Even when only putting this scope in the request the result is the same

**Comment by ddavaham** [comment]
This error means that the application on https://developers.eveonline.com does not have the scope assigned to it. If you are the maintainer of the application, you can update the scope list and add the scope. If not, please contact the maintainer of the application and have them update the scope list.
