### ISSUE TITLE
UniverseIDs limit does not work with more than 500 names

### ISSUE THREAD

**Issue by Flupster** [esi/esi-issues#1031]
# Bug

Tried with 1000/999/750/600 names all result in this
```
2018-09-09 15:05:30,779 - urllib3.connectionpool - DEBUG - https://esi.evetech.net:443 "POST /latest/universe/ids/ HTTP/1.1" 400 27
b'{"error":"Invalid search!"}'
```

with 500 works flawlessly
```
2018-09-09 15:06:22,842 - urllib3.connectionpool - DEBUG - https://esi.evetech.net:443 "POST /latest/universe/ids/ HTTP/1.1" 200 None
```

## Expected

That 1000 names could be posted, This might just be a bad option in the swagger.json and the limit was lowered to 500?

**Comment by tsuthers-ccpgames** [comment]
The limit was probably implicitly lowered to 500 when this was switched to use search as a backend.

How do people feel about lowering this without a version bump given that this is under the hood a limitation anyway?

**Comment by tsuthers-ccpgames** [comment]
No one has screamed against me doing this, so I'm going to just do it and move on.

**Comment by tsuthers-ccpgames** [comment]
Done.
