### ISSUE TITLE
Character Location not updating after dying in Sleeper Site

### ISSUE THREAD

**Issue by ddavaham** [esi/esi-issues#1035]
# Bug

Submitting this on behalf of a newbro to the #esi channel. He popped and stated that multiple 3rd party sites were reporting that he is still in a Wormhole that he is no longer in. States that this started happening after he died to a Sleepless Keeper.

https://zkillboard.com/kill/72378436/
https://esi.evetech.net/latest/killmails/72378436/78edc8412f9b777e0948e52ffa627c7dbd40c81d/

## Request

Be sure to include the HTTP method, path (including version), and any relevant parameters. Please do not include auth tokens. E.g.:

`GET /latest/characters/2114449854/location?datasource=tranquility`

### Status Code

`200`

### Headers

```
content-length: 28
content-type: application/json; charset=UTF-8
date: Thu, 13 Sep 2018 04:17:19 GMT
etag: "b77e897ea08937204c57a1b13d5c5dbe4ef0c7f245ee96a18ef28880"
expires: Thu, 13 Sep 2018 04:17:24 GMT
last-modified: Thu, 13 Sep 2018 04:17:19 GMT
strict-transport-security: max-age=31536000
x-esi-error-limit-remain: 100
x-esi-error-limit-reset: 41
x-esi-request-id: a5f3648a-be39-4be3-9362-f540c5d1f7b7
```
### Body

```json
{
   "solar_system_id": 31002125
}
```
## Expected

`200` and an accurate response from this endpoint

# Checklist

Check all boxes that apply to this issue:

- [x] Bug description is provided
- [x] Request path is provided
- [x] Response status code is provided
- [x] Response headers are provided
- [x] Response body is provided
- [x] Expected response is provided

**Comment by Zoibderg** [comment]
I’m the one experiencing these issues, anybody have any ideas?

**Comment by ddavaham** [comment]
Duplicate of https://github.com/esi/esi-issues/issues/828
