### ISSUE TITLE
Public contract items endpoint can return duplicate item_id and record_id values for the same contract

### ISSUE THREAD

**Issue by andyhassall** [esi/esi-issues#1036]
# Bug

Public contract items endpoint can return duplicate item_id and record_id values for the same contract.

In the case where this has been seen, the contract in-game also appears to have two items (two identical-looking Phoenix BPCs).

## Request

`GET https://esi.evetech.net/v1/contracts/public/items/136753050/`

### Status Code

`200`

### Headers

```
Date: Sat, 15 Sep 2018 19:49:04 GMT
Expires: Sat, 15 Sep 2018 20:37:41 GMT
Last-Modified: Sat, 15 Sep 2018 19:37:41 GMT
X-ESI-Request-ID: 27158905-13fc-42f1-af70-eff1dd386f9f
ETag: "5b7278b65117dca1e92ce331f92fcf999f00edfd30b972039a8e6e62"
```

### Body

```
[
    {
        "is_blueprint_copy": true,
        "is_included": true,
        "item_id": 1027420170421,
        "material_efficiency": 10,
        "quantity": 1,
        "record_id": 2706189214,
        "runs": 1,
        "time_efficiency": 18,
        "type_id": 19727
    },
    {
        "is_blueprint_copy": true,
        "is_included": true,
        "item_id": 1027420170421,
        "material_efficiency": 10,
        "quantity": 1,
        "record_id": 2706189214,
        "runs": 1,
        "time_efficiency": 18,
        "type_id": 19727
    }
]
```

## Expected

Expected that all item_id and record_id values are unique for a given contract.

# Checklist

Check all boxes that apply to this issue:

- [x] Bug description is provided
- [x] Request path is provided
- [x] Response status code is provided
- [x] Response headers are provided
- [x] Response body is provided
- [x] Expected response is provided

**Comment by tsuthers-ccpgames** [comment]
If it was showing in game as well then it's something inside the contract system itself rather than a problem with ESI. If people are seeing it on the regular the best thing would be to file an EBR and send it to me on slack and I'll send it to the right people.
