### ISSUE TITLE
Add regionID to /universe/structures/ to limit to structures in that region

### ISSUE THREAD

**Issue by Zifrian** [esi/esi-issues#1040]
# Feature Request
Add option for including regionID to universe/structures/ to only return structures within that region.

Example: /universe/structures/{regionID}

## Route
/universe/structures/

## Authentication
esi-universe.read_structures

## Use case

Loading all structures (4k) is a bit excessive when a user only works in one region. This would improve processing on my end for market data from structures.

**Comment by CarbonAlabel** [comment]
To clarify, you are requesting for a region ID parameter to be added to the public structures endpoint?

**Comment by ddavaham** [comment]
I think it would be better if this is an optional query parameter that is sent along instead of being apart of the base URL. Otherwise, this would require a whole new route and spec for that route, whereas adding an optional query parameter is just an extension of the existing route.

**Comment by Zifrian** [comment]
Yes, optional parameter would be perfect. Thanks
