### ISSUE TITLE
Inconsistent Time Format in /verify/ Content Headers

### ISSUE THREAD

**Issue by wranders** [esi/esi-issues#1041]
# Inconsistency

The `expires` and `last-modified` content headers on all paths return times using the `GMT` time zone.
The exception is the `verify` meta path, which returns an expiry and last-modified time using `UTC` as a time zone, which it is not.
Some parsing methods, specifically .NET's `DateTime.Parse`, throws an exception because `UTC` is not a timezone.

ex. `ddd, dd MMM yyyy HH:mm:ss UTC`

## Routes

- `GET /verify/`

## Resolution

Change the format of the `expires` and `last-modified` content headers to one of the following:

- `ddd, dd MMM yyyy HH:mm:ss GMT`
- `ddd, dd MMM yyyy HH:mm:ssZ`

# Checklist

Check all boxes that apply to this issue:

- [X] Inconsistency description is provided
- [X] Inconsistent route(s) are provided
- [ ] Resolution [will require a version bump](https://docs.esi.evetech.net/docs/breaking_changes)
- [X] Resolution [does not require a version bump](https://docs.esi.evetech.net/docs/breaking_changes)

**Comment by Aidansavage** [comment]
It may be inconsistent between the two, but they are _BOTH_ RFC 7231 compliant. That being said, the presence of `GMT` rather than `UTC` can be said to be the real issue, as `UTC` is the Standard in use.

Also- https://docs.microsoft.com/en-us/globalization/locale/time-formatting-and-time-zones-in-dotnet-framework , courtesy of googlefu.

**Comment by wranders** [comment]
Thanks for the link. I've already adjusted my code to compensate though, just figured I'd bring it up.
How I interpret that RFC is that the three-letter suffix denotes UTC offset, where GMT would be UTC+0. Even the date/time examples provided use GMT to reference. 

And on that note, RFC 5322 says that either way this is obsolete and +0000 should be used instead of the three-letter qualifier.

**Comment by GoldenGnu** [comment]
just a friendly reminder that changing date formats may break existing software and the meta endpoints are not versioned, making a safe change impossible. 

I prefer keeping the current format, even if it's not technical correct.

**Comment by a-tal** [comment]
thanks for the report. this is resolved and deployed
