### ISSUE TITLE
Get contract items doesnt return item id

### ISSUE THREAD

**Issue by AndersDit** [esi/esi-issues#1044]
/characters/{character_id}/contracts/{contract_id}/items/

When getting a contract for an item(in this case mutated abyssal thing), the item id is not given. 

Example of said contract
[{
    "is_included": true,
    "is_singleton": false,
    "quantity": 1,
    "record_id": 2727145143,
    "type_id": 47749
  }]

Could this be added?

**Comment by CarbonAlabel** [comment]
Duplicate of #951
