### ISSUE TITLE
500 on invalid constellation_id /universe/constellations/{constellation_id}/

### ISSUE THREAD

**Issue by Blacksmoke16** [esi/esi-issues#1045]
When an invalid constellation_id is given for the constellation endpoint, it returns:

```
curl -I https://esi.evetech.net/latest/universe/constellations/123/
HTTP/2 500 
date: Mon, 08 Oct 2018 04:40:44 GMT
content-type: application/json; charset=UTF-8
access-control-allow-credentials: true
access-control-allow-headers: Content-Type,Authorization,If-None-Match,X-User-Agent
access-control-allow-methods: GET,HEAD,OPTIONS
access-control-allow-origin: *
access-control-expose-headers: Content-Type,Warning,ETag,X-Pages,X-ESI-Error-Limit-Remain,X-ESI-Error-Limit-Reset
access-control-max-age: 600
allow: GET,HEAD,OPTIONS
content-language: en-us
etag: W/"4befcd399a22510851d6475877d03b00d42a56887f18bf06432328f8"
strict-transport-security: max-age=31536000
vary: Accept-Language
x-esi-error-limit-remain: 99
x-esi-error-limit-reset: 16
x-esi-request-id: f4a70147-2c70-427b-af91-3e3d22f01e07

{"error":"Unhandled internal error encountered!"}
```

This should be a 404 `{"error": "Constellation not found"}`

Also there is an inconsistency with the regions and systems endpoints. Currently the error response for region not found is `Region not found!`.  For a system it is `System not found`. 

Probably should either add the `!` to the systems and constellations endpoints as well, or remove it from the regions endpoint.

**Comment by tsuthers-ccpgames** [comment]
I've submitted a fix for this, it'll probably wander out on Tuesday. I resisted the urge to put tableflip emotes on the end of the errors and have removed the exclamation marks from the region error for consistency.
