### ISSUE TITLE
Scope doesnt exist in Swagger Singularity - esi-industry.read_corporation_mining.v1

### ISSUE THREAD

**Issue by Thor844** [esi/esi-issues#1049]
# Bug

When requesting authorization via swagger ui https://esi.evetech.net/ui/?version=latest&datasource=singularity with the scope esi-industry.read_corporation_mining.v1 i get the error message: 

{
  "error": "invalid_scope",
  "error_description": "The requested 'esi-industry.read_corporation_mining.v1' scope is not valid."
}

I used the site: https://esi.evetech.net/ui/?version=latest&datasource=singularity
version legacy and dev produce the same error.
i tried different accounts.
other corp scopes work fine.
tranquility works fine.

Maybe the scope is not included in the application for swagger itself?

# Checklist

Check all boxes that apply to this issue:

- [x] Bug description is provided
- [ ] Request path is provided
- [ ] Response status code is provided
- [ ] Response headers are provided
- [ ] Response body is provided
- [ ] Expected response is provided

**Comment by Blacksmoke16** [comment]
This scope hasn't been applied to the Singularity server.  I'll bring it up in slack.

**Comment by CarbonAlabel** [comment]
I've done some more testing, and of the 67 ESI scopes, 15 aren't valid for ESI UI's Singularity app. This will need to be fixed.

**Comment by ccp-zoetrope** [comment]
The missing scopes for ESI UI for Singularity have been added.
