### ISSUE TITLE
Industry jobs cancelled due to explosion of facility have completed_character_id == 1

### ISSUE THREAD

**Issue by andyhassall** [esi/esi-issues#1053]
# Bug

Industry jobs cancelled due to the structure they are building in exploding have `completed_character_id` set to 1.

The swagger spec defines this field as `ID of the character which completed this job`, but 1 is not a valid character ID.

`/v2/universe/names/` also refuses to resolve this ID, replying `Ensure all IDs are valid before resolving.` but this ID came from an ESI payload defined to contain a valid character ID.

It would seem more reasonable that `completed_character_id` is missing in this case as it was not a character cancelling the job.

## Request

`GET /v1/corporations/{corporation_id}/industry/jobs/?includeCompleted=true`
`GET /v1/characters/{character_id}/industry/jobs/?includeCompleted=true`

### Status Code

`200`

### Headers

```
Date →Thu, 25 Oct 2018 19:21:24 GMT
Content-Type →application/json; charset=UTF-8
Transfer-Encoding →chunked
Connection →keep-alive
Access-Control-Allow-Credentials →true
Access-Control-Allow-Headers →Content-Type,Authorization,If-None-Match,X-User-Agent
Access-Control-Allow-Methods →GET,HEAD,OPTIONS
Access-Control-Allow-Origin →*
Access-Control-Expose-Headers →Content-Type,Warning,ETag,X-Pages,X-ESI-Error-Limit-Remain,X-ESI-Error-Limit-Reset
Access-Control-Max-Age →600
Allow →GET,HEAD,OPTIONS
Cache-Control →private
Content-Encoding →gzip
Etag →"1834796a19712ef6123c135c59c1e39df940984da442c5046429222b"
Expires →Thu, 25 Oct 2018 19:26:23 GMT
Last-Modified →Thu, 25 Oct 2018 19:21:23 GMT
Strict-Transport-Security →max-age=31536000
Vary →Accept-Encoding
X-Esi-Error-Limit-Remain →100
X-Esi-Error-Limit-Reset →36
X-Esi-Request-Id →d58b11f6-9d61-46ea-ae8e-581e5705e0c3
X-Pages →2
```

### Body

```json
    {
        "activity_id": 1,
        "blueprint_id": 1028627169681,
        "blueprint_location_id": 1028813164173,
        "blueprint_type_id": 34829,
        "completed_character_id": 1,
        "completed_date": "2018-10-25T06:54:23Z",
        "cost": 9958837,
        "duration": 917878,
        "end_date": "2018-10-20T03:41:20Z",
        "facility_id": 1027824508576,
        "installer_id": opsec,
        "job_id": 374314351,
        "licensed_runs": 1,
        "location_id": 1027824508576,
        "output_location_id": 1028813164173,
        "pause_date": "2018-10-18T08:03:07Z",
        "probability": 1,
        "product_type_id": 34828,
        "runs": 14,
        "start_date": "2018-10-09T12:43:22Z",
        "status": "cancelled"
},
```

## Expected

Expected that `completed_character_id` represents a valid character ID or is missing.

# Checklist

Check all boxes that apply to this issue:

- [x] Bug description is provided
- [x] Request path is provided
- [x] Response status code is provided
- [x] Response headers are provided
- [x] Response body is provided
- [x] Expected response is provided

**Comment by tsuthers-ccpgames** [comment]
Seems reasonable, particularly since that attribute is already optional.

**Comment by tsuthers-ccpgames** [comment]
deployed.
