### ISSUE TITLE
https://login.eveonline.com/v2/oauth/token/ has "Access-Control-Allow-Headers" missing!

### ISSUE THREAD

**Issue by jeffy-g** [esi/esi-issues#1058]
# Bug

I threw it to `https://login.eveonline.com/v2/oauth/token/` with `code` obtained by `https://login.eveonline.com/v2/oauth/` authentication as a parameter , Request never succeeds...

## Request
using Web Fetch API

callback result url: http://localhost/callback/?code=wkEExnPJXUCIUfZhB5xOuw&state=login

```js
function token2(code) {
    const options = {
        method: "POST",
        mode: "cors",
        uri: `https://login.eveonline.com/v2/oauth/token/?grant_type=authorization_code&code=${code}`,
        headers: {
            "content-type": "application/x-www-form-urlencoded",
            authorization: `Basic ${_CS}`
        }
    };
    return fetch(options.uri, options).then(res => res.json()).then(json => console.log(json));
}

const p = token2("wkEExnPJXUCIUfZhB5xOuw");
```

## Response
[browser console]
Failed to load https://login.eveonline.com/v2/oauth/token/?grant_type=authorization_code&code=wkEExnPJXUCIUfZhB5xOuw: Request header field authorization is not allowed by Access-Control-Allow-Headers in preflight response.
Uncaught (in promise) TypeError: Failed to fetch

### Status Code

`200`

### Headers

```
access-control-allow-methods: OPTIONS, GET, POST
access-control-allow-origin: *
cache-control: no-cache
content-length: 0
date: Wed, 31 Oct 2018 20:38:16 GMT
expires: -1
pragma: no-cache
server: Microsoft-IIS/8.5
status: 200
```

### Body

Please provide the response body, feel free to scrub any opsec details you wish. E.g.:

```json
<empty>
```

## Expected

Please provide either the expected return code, correct response body, header value, or some combination thereof. E.g.:

`200`

# Checklist

Check all boxes that apply to this issue:

- [x] Bug description is provided
- [x] Request path is provided
- [x] Response status code is provided
- [x] Response headers are provided
- [x] Response body is provided
- [x] Expected response is provided

**Comment by antihax** [comment]
please post this in the sso-issues repo.

**Comment by jeffy-g** [comment]
im sorry, I overlooked that...
okay
