### ISSUE TITLE
Portraits endpoints Internal error

### ISSUE THREAD

**Issue by ascentior** [esi/esi-issues#1067]
``` json
{
  "error": "Internal error",
  "request_id": "00daec07-325d-4c71-bb0d-a6422957ef31",
  "sentry_id": "b3730018da444f719d06c60ba5ebc1d6"
}
```
Tested `/character/{character_id}/portrait/` and `/alliances/{alliance_id}/icons/` and both return the same error.

**Comment by ascentior** [comment]
Also checked `/latest/` `/dev/` `/v1/` and `/legacy/` paths with the same result

**Comment by ccp-zoetrope** [comment]
This has been fixed, please re open this if you see it again.

**Comment by ccp-zoetrope** [comment]
I saw this show up again an hour after I closed this. I __believe__ I have fixed this for good now :)

**Comment by ccp-zoetrope** [comment]
Annnnd this showed up in droves again, going to re-open it and take a deeper dive.

**Comment by ccp-zoetrope** [comment]
A new fix for this was just deployed and I am pretty certain this issue has been fixed, however based on my previous track record on this issue I'm going to keep this open until I can verify this for myself.

**Comment by ccp-zoetrope** [comment]
I have not seen this reoccur since I commented. If you see this again, please reopen this issue.
