### ISSUE TITLE
Social skill return a required skill level

### ISSUE THREAD

**Issue by mayumi7** [esi/esi-issues#1068]
# Bug

Social skill returns a dogma attribute that should not be there
https://esi.evetech.net/latest/universe/types/3355
{"attribute_id":277,"value":0.0}

which is described as "Required skill level for skill 1"
https://esi.evetech.net/latest/dogma/attributes/277

Social doesn't require any skills in reality.

## Request

`GET /latest/universe/types/3355`

# Checklist

Check all boxes that apply to this issue:

- [X] Bug description is provided
- [x] Request path is provided
- [ ] Response status code is provided
- [ ] Response headers are provided
- [ ] Response body is provided
- [ ] Expected response is provided

**Comment by ddavaham** [comment]
```
{
    "attribute_id": 180,
    "value": 164
},
{
    "attribute_id": 181,
    "value": 165
},

```

Those are the alpha and omega clones. They do not have skill levels, hence the 0.0
`https://esi.evetech.net/latest/universe/types/164`
```
{
  "capacity": 0,
  "description": "",
  "dogma_attributes": [
    {
      "attribute_id": 161,
      "value": 1
    },
    {
      "attribute_id": 162,
      "value": 0
    },
    {
      "attribute_id": 419,
      "value": 900000
    },
    {
      "attribute_id": 4,
      "value": 0
    },
    {
      "attribute_id": 38,
      "value": 0
    }
  ],
  "group_id": 23,
  "icon_id": 34,
  "mass": 0,
  "name": "Clone Grade Alpha",
  "packaged_volume": 1,
  "portion_size": 1,
  "published": false,
  "radius": 1,
  "type_id": 164,
  "volume": 1
}
```


`https://esi.evetech.net/latest/universe/types/165`
```
{
  "capacity": 0,
  "description": "",
  "dogma_attributes": [
    {
      "attribute_id": 161,
      "value": 1
    },
    {
      "attribute_id": 162,
      "value": 0
    },
    {
      "attribute_id": 419,
      "value": 1380000
    },
    {
      "attribute_id": 4,
      "value": 0
    },
    {
      "attribute_id": 38,
      "value": 0
    }
  ],
  "group_id": 23,
  "icon_id": 34,
  "mass": 0,
  "name": "Clone Grade Beta",
  "packaged_volume": 1,
  "portion_size": 1,
  "published": false,
  "radius": 1,
  "type_id": 165,
  "volume": 1
}
```

**Comment by lukasni** [comment]
So, definitely an error returned from EVE there. I recommend ignoring Attribute 277 if no Attribute 182 (Type ID of primary skill requirement) is present. The issue likely doesn't lie with ESI though.

**Comment by ddavaham** [comment]
My apologies, I got this mixed up with another set of attributes. However, the data in question is pulled directly from the SDE, so a bug report should be submitted via https://support.eveonline.com

**Comment by mayumi7** [comment]
I don't understand,
```
{
    "attribute_id": 180,
    "value": 164
},
{
    "attribute_id": 181,
    "value": 165
},
```
these are dogma attributes of the skillbook, those attributes refer to the primary and secondary character attributes the skill training uses,
https://esi.evetech.net/latest/dogma/attributes/180
which refers to another dogma attribute, 164 which is charisma
https://esi.evetech.net/latest/dogma/attributes/164
nothing to do with clone types?

**Comment by mayumi7** [comment]
Ok will do, got really confused there for a moment.

**Comment by mayumi7** [comment]
> My apologies, I got this mixed up with another set of attributes. However, the data in question is pulled directly from the SDE, so a bug report should be submitted via https://support.eveonline.com

I'm not going to open a support ticket for this since it's not really a problem with any of my characters or accounts.
The bug reporting form on the other hand has no option that would even remotely relate to the SDE
https://community.eveonline.com/support/submit-bug-report
So I guess I won't report it then since I can't find a place to do it from.
