### ISSUE TITLE
ESI status endpoint returning empty array

### ISSUE THREAD

**Issue by CarbonAlabel** [esi/esi-issues#1071]
# Bug
The ESI status endpoint is not working properly; it is only returning an empty array. According to https://status.esiknife.space/, this has been happening since `2018-11-21 14:23:03`.

## Request
https://esi.evetech.net/status.json

## Response
```[]```

## Expected
Information about the health of ESI endpoints.

**Comment by ccp-zoetrope** [comment]
This has been fixed.
