### ISSUE TITLE
Invalid-scope error on all existing auths when requesting access token

### ISSUE THREAD

**Issue by Foiritain** [esi/esi-issues#1076]
# Bug

Invalid-scope error on all existing auths when requesting access token. Same thing when clicking our login with eve link the login page displays the invalid scope error as well. Errors started piling up somewhere around 11:00 eve time yesterday.

On our login trough eve link scope list we had an old CREST scope called fleetRead, once this is removed from the link the page displays the character select screen instead of an error.

I think the access token request is also failing because all our members provided auths that included this scope. (it's no longer visible on the application management page so I assume it's been removed as it served no purpose anymore). 

## Request

Access token request at /oauth/token

## Response

Invalid-scope

Posting this from my phone so no access to actual response body, headers, etc. Let me know if any additional info is required.

**Comment by lukasni** [comment]
A fix for that was _just now_ pushed to Tranquility, can you verify that you are no longer getting the error?

**Comment by Foiritain** [comment]
> A fix for that was _just now_ pushed to Tranquility, can you verify that you are no longer getting the error?

Ah nice. I won't be able to check until I get home in a few hours. I turned all ESI things off last night.

**Comment by lukasni** [comment]
For future reference, please use [ccpgames/sso-issues](https://github.com/ccpgames/sso-issues) for SSO related issues
