### ISSUE TITLE
Skill endpoint updating delayed

### ISSUE THREAD

**Issue by Dawnkeeper** [esi/esi-issues#1087]
# Bug

Endpoint /characters/{character_id}/skills/ updates only on character login

## Request

`GET /characters/{character_id}/skills/ ?datasource=tranquility`

## Expected

Returned skill level and XP should reflect the current ingame status.

## Actual

Esi reports the status at last logoff.

Example:
I logged out with the skill Mining 3 training. The queue had Mining 4 and Amarr Cruiser 5 added after this. Two days later ESI still reported Mining being at level 3 while the login screen already displayed the cruiser skill as training. Only  upon login the ESI value was corrected to Mining at 4.

**Comment by ddavaham** [comment]
This is not a bug. Skills are calculated by the client on login and then communicated back to the servers to store, so the data is not available until the character is logged in and skills are recalculated.

**Comment by fuzzysteve** [comment]
Not actually calculated on the client. Just not calculated on the server until it's triggered by a client login. As no-one needs the skill, until someone logs in. It's an efficiency thing, so there's not a job updating all the characters in existence on a regular basis.

**Comment by ddavaham** [comment]
@fuzzysteve Well put. Here is another issue that is addressed by this as well for reference,

https://github.com/esi/esi-issues/issues/770

**Comment by irwiss** [comment]
FWIW you should be able to merge this with skill queue endpoint and work out the "actual" state when you need it

**Comment by Dawnkeeper** [comment]
Why was this closed? Even if the way it is working now is by design **the result is still wrong**.

If a skill is training for X hours it should be marked as done after this time. It's not like Schrödingers Cat as we know exactly when something will happen.

**Comment by ddavaham** [comment]
The API does not know that the skill is done training until the character has been logged back in. You stated it yourself that once you logged in, the endpoint updated and reflected the correct information.

**Comment by fuzzysteve** [comment]
The details can be calculated as required. ESI is returning what Eve knows at the time of query, in a way which is easy for it to cache. 

As such, I'm now locking this conversation.
