### ISSUE TITLE
List the market history by location.

### ISSUE THREAD

**Issue by FabianPiconeDev** [esi/esi-issues#1094]
# Feature Request

It would be nice if we could list the market history of a type by location.

For avoiding route conflict, fetch by region id should be adapted.

 `GET /markets/history/location/{location_id}/{type_id}`
 `GET /markets/history/region/{region_id}/{type_id}`

## Use case

As a trader I want to fetch market history of a type by location.

## Authentication

A public route, no auth required.

## Example return

Same response structure as by region id:
```
{
  "application/json": [
    {
      "average": 5.25,
      "date": "2015-05-01",
      "highest": 5.27,
      "lowest": 5.11,
      "order_count": 2267,
      "volume": 16276782035
    }
  ]
}
```

# Checklist

- [x] Feature request description is provided
- [x] Use case exists
- [x] Feature requires a new route
- [ ] Feature adds data to existing route
- [ ] Feature requires new auth scope
- [ ] Feature can reuse existing scope
- [x] Feature does not require auth
- [ ] Meta feature, applies to all routes

**Comment by tsuthers-ccpgames** [comment]
Unfortunately that's not how market history works. Market history is pre-baked per region based on the aggregate data over the entire region. Additionally, if this new route is to support market citadels it cannot be unauthed.

Incidentally, your use case is not actually a use-case. I can see that you'd like to request this information by the existence of the ticket, but a use case contains a goal for the information will be used, e.g. "As a manufacturer I want to fetch market history of a type by station so that I can know which stations move the most of the products I wish to sell, and thus set up shop there".

I think this one will probably be closed on the basis of "high cost of engineering a solution is not worth the payoff", but I am open to being persuaded and curious to know what your specific use case is, if you'd like to be more specific about what you're thinking?

**Comment by FabianPiconeDev** [comment]
Sure, here a more detailed use case:
```
As a trader I want to fetch the market history of a type by location,
so that I can know the daily sell amount of that type in that location,
and thus I can know if i have a chance to sell that type in that location 
and thus I can decide to place a sell order of that type in that location.
```
The "chance to sell" is variable. It depends on the type and how much time I want to spend to adapt my prices.
Example: If the daily sell amount is too high: I may have much competition, so I have a small chance.

For citadels you could validate authorization only when fetching by a citadel location id.

**Comment by guiguilechat** [comment]
a better (imaginary) use case : 

```
I want the market order of jita IV-4 -CN assembly

I request the path /markets/history/location/JITAIV4LOCID

IT gives me the same list as if I had the /region/THEFORGELOCID but limited to exchanges that were performed in the structure
```


I'm not even sure this is possible. I think the monolith stores the sales on a region-based table. that means what you are asking may be not possible at all (you want data that does not exist).

**Comment by fuzzysteve** [comment]
And I suspect the response by game design may involve laughter, followed by a no.

**Comment by guiguilechat** [comment]
That would be a very bad way to answer.

**Comment by FabianPiconeDev** [comment]
@tsuthers-ccpgames What do you think about my more detailed [use case above](https://github.com/esi/esi-issues/issues/1094#issuecomment-468644073)? It should better reflect my thoughts.

Basically as a location trader, I am only interested in location data, not region-wide data.

> I'm not even sure this is possible. I think the monolith stores the sales on a region-based table. that means what you are asking may be not possible at all (you want data that does not exist).

I can immagine that every transaction holds the location id, so the data should be there.

**Comment by tsuthers-ccpgames** [comment]
>I can immagine that every transaction holds the location id, so the data should be there.

It is, but to support this, we'd either have to implement on-demand map-reduce jobs per location, or start pre-baking the map-reduce outputs per location as well as per region. That feature creeps to obvious questions such as "why not per constellation?" and "why not per arbitrary collection of stations I care about?".

It would also need to be an authed route to avoid leaking structure information. There's a huge amount of edge-cases to this proposal. Unfortunately I don't think the use case of "discovering stations that my stuff is likely to sell at" is compelling enough to justify the work at this point. This seems like a good candidate for a third party service to aggregate data from the existing region market endpoints and perform it's own post-processing to create these kinds of outputs.

**Comment by guiguilechat** [comment]
come on, just give access to the full list of transactions already !! :P
