### ISSUE TITLE
500 error when fetching character wallet journal

### ISSUE THREAD

**Issue by Ville-Saari** [esi/esi-issues#1095]
# Bug
I get a consistent 500 error when trying to fetch the wallet journal of any of my characters.

If I replace "page=1" with "page=2" in the request, it works. Even when the character has enough
journal entries to have non empty second page.

## Request
https://esi.evetech.net/latest/characters/{character_id}/wallet/journal/?datasource=tranquility&page=1

### Status Code

500

### Headers

 date: Fri, 22 Feb 2019 11:40:50 GMT 
 status: 500 
 x-esi-request-id: baa1bb0d-bca3-49ed-8bfb-ac273a7b6713 

### Body

{
  "error": "Unhandled internal error encountered!"
}

## Expected

200

# Checklist

Check all boxes that apply to this issue:

- [ x] Bug description is provided
- [ x] Request path is provided
- [ x] Response status code is provided
- [ x] Response headers are provided
- [ x] Response body is provided
- [ x] Expected response is provided

**Comment by Ville-Saari** [comment]
Now whatever there is in my wallet log causing this problem seems to have moved far enough to the past to affect page 2 too.

**Comment by jennej** [comment]
I have two characters in my corp who get this. Starting Feb 13th, so I suspect a guardians gala thing to be the culprit. (And I've been too busy to file a proper bug, so Hanks!)

**Comment by Ville-Saari** [comment]
I compared the wallet journal entries I had successfully received before the bug hit me to the in-game journal after that time and discovered a new 'Ref. type' value that never appeared before the bug hit me but appeared the first time very soon after the last successfully received row. This was:

Item Trade - Payment for use of Paradise Club

I hope this information was useful for locating and fixing the cause of the bug.

**Comment by aplulu** [comment]
Ref type "Item Trading" (Guardian's Gala Event) and "Skill Purchase" (Skills on demand) are causing this problem.
![item_trade_paradise_club](https://user-images.githubusercontent.com/20220680/54491781-65e95c80-4904-11e9-9fc7-4bdfa82b7d8b.png)
![skill_purchase](https://user-images.githubusercontent.com/20220680/54491783-6bdf3d80-4904-11e9-9747-44073d328e68.png)

**Comment by tsuthers-ccpgames** [comment]
I've found where the error is happening and submitted a fix that will prevent it from crashing by hiding the ID's. I'll be working on creating a new endpoint to support the new ID's soon.

**Comment by tsuthers-ccpgames** [comment]
Fixes to allow support for the new enums have also been deployed, I'll roll out a new dev endpoint tomorrow with the new enums once the server is updated. I can't move it to release for a little while because there's still quite a few people using the v4 endpoint.

**Comment by tsuthers-ccpgames** [comment]
the v6 with support for skill purchases and item traders is out.
