### ISSUE TITLE
Bad data while retrieving Plagioclose (TypeId 18)

### ISSUE THREAD

**Issue by seraphx2** [esi/esi-issues#1096]
# Bug
The key part here is that when requesting TypeId 18 (Plagioclase) from Universe, Attribute 4 returns 1e35.
```json
{
    "attribute_id": 4,
    "value": 1e35
}
```
Typically, I have been translating the `number` type in the swagger definition as `decimal` in .NET and that has been working fine. However, `1e35` is outside the bounds of `decimal`, and the fact the API is returning that value and not an actual number, must also mean the number is too large for your own structures.

## Request
`GET /v3/universe/types/{type_id}/`
type_id:18

### Status Code

`200`

### Headers

```json
{  
   "requestId": "32326404-ce74-4e6f-a806-0e08c0617ea2",
   "statusCode": 200,
   "endpoint": "/universe/types/{type_id}/",
   "version": "v3",
   "expires": "2019-02-28T06:05:00-05:00",
   "lastModified": "2019-02-26T06:05:48-05:00",
   "eTag": "W/9d62c98645ede8f314a67cdc7f5c52132f52e339ff36ba2e7d0eb61b",
   "errorLimitRemain": 100,
   "errorLimitReset": 33,
   "pages": null
}
```

### Body
```json
{
    "capacity": 0.0,
    "description": "Plagioclase is not amongst the most valuable ore types around, but it contains a large amount of pyerite and is thus always in constant demand. It also yields some tritanium and mexallon.\\r\\n\\r\\nAvailable in <color='0xFF4DFFCC'>0.9<\\/color> security status solar systems or lower.",
    "dogma_attributes": [{
        "attribute_id": 161,
        "value": 0.35
    }, {
        "attribute_id": 162,
        "value": 0.0
    }, {
        "attribute_id": 2115,
        "value": 0.0
    }, {
        "attribute_id": 4,
        "value": 1e35
    }, {
        "attribute_id": 182,
        "value": 3386.0
    }, {
        "attribute_id": 38,
        "value": 0.0
    }, {
        "attribute_id": 2699,
        "value": 1.0
    }, {
        "attribute_id": 1940,
        "value": 28422.0
    }, {
        "attribute_id": 1941,
        "value": 100.0
    }, {
        "attribute_id": 790,
        "value": 12191.0
    }, {
        "attribute_id": 2711,
        "value": 18.0
    }],
    "group_id": 458,
    "icon_id": 230,
    "market_group_id": 516,
    "mass": 1e35,
    "name": "Plagioclase",
    "packaged_volume": 0.35,
    "portion_size": 100,
    "published": true,
    "radius": 1.0,
    "type_id": 18,
    "volume": 0.35
}
```

## Expected

# Checklist

Check all boxes that apply to this issue:

- [x] Bug description is provided
- [x] Request path is provided
- [x] Response status code is provided
- [x] Response headers are provided
- [x] Response body is provided
- [ ] Expected response is provided

**Comment by snitchashor** [comment]
I just checked the SDE, the mass of all ores is 1e35 there as well.

**Comment by CarbonAlabel** [comment]
The e notation you refer to as "not an actual number" is a valid way of encoding a number in JSON, and the `value` attribute is defined in the spec as a [single-precision float](https://en.wikipedia.org/wiki/Single-precision_floating-point_format), with the returned value well within the bounds of the type.

If the type you're using in your code isn't capable of accomodating the value, you'll just have to use another one that is.

**Comment by seraphx2** [comment]
so does this mean that all references of number should be float instead of decimal? "number" can't literally mean two different types. can it? you use int and long to differentiate between upper limits for whole numbers.

**Comment by Blacksmoke16** [comment]
@seraphx2 It does.

The `swagger.json` states that the `value` property is a `float` while the `attribute_id` is `int32`

```json
{
  "properties": {
    "attribute_id": {
      "description": "attribute_id integer",
      "format": "int32",
      "title": "get_universe_types_type_id_attribute_id",
      "type": "integer"
    },
    "value": {
      "description": "value number",
      "format": "float",
      "title": "get_universe_types_type_id_value",
      "type": "number"
    }
  }
}
```

The Swagger UI also defines them in the same way.

![screen shot 2019-02-27 at 3 27 03 pm](https://user-images.githubusercontent.com/12136995/53520667-29180b80-3aa4-11e9-9b60-9e337d5125d7.png)

**Comment by seraphx2** [comment]
Would be interested to know where you're looking to see what that image shows.
![image](https://user-images.githubusercontent.com/11561820/53520844-9cba1880-3aa4-11e9-89cb-d7b8c6db2b29.png)

**Comment by Blacksmoke16** [comment]
https://esi.evetech.net/ui/#/Universe/get_universe_types_type_id

Under the Responses 200 section => `get_universe_types_type_id_dogma_attribute` => `get_universe_types_type_id_dogma_attribute`

**Comment by seraphx2** [comment]
ok. So why are there different ways to view this?
I am coming at it through this URL:
https://esi.evetech.net/latest/#/

**Comment by Blacksmoke16** [comment]
notice the `/ui/` part in the URL.
