### ISSUE TITLE
Wallet journal issue

### ISSUE THREAD

**Issue by SuudEVE** [esi/esi-issues#1097]
# Bug

This template contains an example bug report. Please replace all text except for the checklist and the section headers (they start with \#). Thank you for your contribution to improving ESI.

In this space please provide a short description of the bug you've encountered. E.g.:
{
  "error": "Unhandled internal error encountered!"
}

When requesting my character ID, I receive an unexpected 418 error.

## Request

Be sure to include the HTTP method, path (including version), and any relevant parameters. Please do not include auth tokens. E.g.:

`GET /latest/characters/{character_id}/?datasource=tranquility`

## Response
{
  "application/json": [
    {
      "amount": -100000,
      "balance": 500000.4316,
      "context_id": 4,
      "context_id_type": "contract_id",
      "date": "2018-02-23T14:31:32Z",
      "description": "Contract Deposit",
      "first_party_id": 2112625428,
      "id": 89,
      "ref_type": "contract_deposit",
      "second_party_id": 1000132
    }
  ]
}
### Status Code
200
### Headers

Include relevant headers received. Timestamps and request ID is nice, you may not have all these values, fill out what you received (don't worry about headers not listed here, unless pertinent to your issue). E.g.:

```

Header | Description | Type | Other
-- | -- | -- | --
Cache-Control | The caching mechanism used | string |  
ETag | RFC7232 compliant entity tag | string |  
Expires | RFC7231 formatted datetime string | string |  
Last-Modified | RFC7231 formatted datetime string | string |  
X-Pages | Maximum page number | integer | default: 1,format: int32


Date: Fri, 27 Apr 2018 07:22:48 GMT
Expires:
Last-Modified:
X-ESI-Request-ID: dcc736af-a73a-4c99-add5-8d66e197cec6
ETag:
```

### Body

Please provide the response body, feel free to scrub any opsec details you wish. E.g.:

```json
{
  "error": "Unhandled internal error encountered!"
}
```

## Expected

Please provide either the expected return code, correct response body, header value, or some combination thereof. E.g.:

`200`

# Checklist

Check all boxes that apply to this issue:

- [ ] Bug description is provided
- [ ] Request path is provided
- [ ] Response status code is provided
- [ ] Response headers are provided
- [ ] Response body is provided
- [ ] Expected response is provided

YOURE FCKING KIDDING WITH THAT BUG REPORT... Normal player cant do that!~

**Comment by DianaOlympos** [comment]
Hello,

As you can see, this is a place to report bugs for ESI. This is a tool built for developers. It is not expected that "normal players" without knowledge of how API and code works to have to deal with it.

If you have the capability to find a bug in ESI, you probably are a dev or learning to code. This is then a totally acceptable bug report. If you are still learning and need help to fill it, i am sure we would be happy to help you.

If a "normal player" encounter a bug with the game, there is a bug report tool both in game and out of game. See https://community.eveonline.com/support/test-servers/bug-reporting/

As this does not seem to be a proper bug report, i am going to close. If you encounter an error with ESI, we will happily help. If you need help understanding how to fill this report, i would advise to come talk in the #esi channel in the Tweetfleet slack. You can join at https://www.fuzzwork.co.uk/tweetfleet-slack-invites/

Thank you ❤️ 💜 💚 💙 💛

**Comment by jennej** [comment]
it is also possible that what you're seeing is https://github.com/esi/esi-issues/issues/1095, also always check for bugs before reporting one.
