### ISSUE TITLE
Planets endpont will return stars

### ISSUE THREAD

**Issue by kennethjor** [esi/esi-issues#1099]
# Bug
`40000001` is the ID of a star. The planets endpoint will return data about this star.

## Request

https://esi.evetech.net/latest/universe/planets/40000001

## Response

Star is returned.

### Status Code

`200`

### Headers

```
date: Sun, 03 Mar 2019 15:48:21 GMT
x-esi-request-id: 2bb44847-9e2f-4b6e-b984-0586334c8ec6
```

### Response Body

```
{
  "name": "Tanoo - Star",
  "planet_id": 40000001,
  "position": {
    "x": 0,
    "y": 0,
    "z": 0
  },
  "system_id": 30000001,
  "type_id": 45041
}
```

## Expected

Would expect a `404`.

# Checklist

- [x] Bug description is provided
- [x] Request path is provided
- [ ] Response status code is provided
- [x] Response headers are provided
- [x] Response body is provided
- [x] Expected response is provided

**Comment by mateuszkrasucki** [comment]
A fix was released on 2019/06/06.
