### ISSUE TITLE
/search endpoint on Serenity doesn't support Chinese characters

### ISSUE THREAD

**Issue by copyliu** [esi/esi-issues#1101]
# Bug

/search endpoint on Serenity seems doesn't support Chinese characters

## Request

For the alliance `泛银河商业共同体` aka `PIBC` ( alliance  ID `403524217` )

`https://esi.evepc.163.com/latest/search/?categories=alliance&search=pibc` 

returning `{"alliance":[403524217]}`  , it's ok

`https://esi.evepc.163.com/latest/search/?categories=alliance&search=%E6%B3%9B%E9%93%B6%E6%B2%B3`   (searching `泛银河`)

returning `{}` , no results found

`https://esi.evepc.163.com/latest/search/?categories=alliance&search=%E6%B3%9B%E9%93%B6%E6%B2%B3%E5%95%86%E4%B8%9A%E5%85%B1%E5%90%8C%E4%BD%93`  (searching `泛银河商业共同体`)

returning status code 500, `{"error":"Unhandled internal error encountered!"}` 

## Additional Information

the alliance `泛银河商业共同体` information:

`https://esi.evepc.163.com/latest/alliances/403524217/`

```
{
  "creator_corporation_id": 147812802,
  "creator_id": 102149490,
  "date_founded": "2006-08-15T10:17:00Z",
  "executor_corporation_id": 98021437,
  "name": "泛银河商业共同体",
  "ticker": "PIBC"
}
```

# Checklist

Check all boxes that apply to this issue:

- [ ] Bug description is provided
- [ ] Request path is provided
- [ ] Response status code is provided
- [ ] Response headers are provided
- [ ] Response body is provided
- [ ] Expected response is provided

**Comment by tsuthers-ccpgames** [comment]
This works in the client so something in esi is probably mangling unicode characters on their way to the server :(

**Comment by tsuthers-ccpgames** [comment]
I've found a fix for this that also cleans up some old code, which is nice. When I release it I'll put the legacy search endpoints on a timeline to deletion, but the current latest endpoints won't need updating.

**Comment by tsuthers-ccpgames** [comment]
Fixes have been deployed everywhere, waiting on confirmation from @copyliu that the issue is resolved before closing though

**Comment by copyliu** [comment]
confirmed everything work as expected, I think I can close the issue
