### ISSUE TITLE
Market order: More precise duration / expires_in

### ISSUE THREAD

**Issue by FabianPiconeDev** [esi/esi-issues#1107]
# Feature Request

It would be nice if we could fetch more precise duration informations via `/markets/{region_id}/orders/`. The `Expires In` value used in the market table would be sufficent.

## Use case

As a trader, I want to fetch market orders containing precise duration informations
so that I can know when the last price change on each order was done
and thus I can see if I would have tough competition on that product.

## Authentication

A public route, no auth required.

## Example return

```javascript
  {
    "expires_in": "2019-06-24T22:28:08Z", // new, precise
    "duration": 90, // current, not precise
    "is_buy_order": false,
    "issued": "2019-03-24T22:28:08Z",
    "location_id": 60003760,
    "min_volume": 1,
    "order_id": 5389680881,
    "price": 43999992.69,
    "range": "region",
    "system_id": 30000142,
    "type_id": 28583,
    "volume_remain": 1,
    "volume_total": 1
  },
```

# Checklist

Check all boxes that apply to this issue:

- [x] Feature request description is provided
- [x] Use case exists
- [ ] Feature requires a new route
- [x] Feature adds data to existing route
- [ ] Feature requires new auth scope
- [ ] Feature can reuse existing scope
- [x] Feature does not require auth
- [ ] Meta feature, applies to all routes

**Comment by fuzzysteve** [comment]
The order expires at issued+duration which is precise down to the second.

What's the additional precision added by this?

**Comment by FabianPiconeDev** [comment]
I assumed that “issued” only stands for the creation date and thus i could not get the value that I want. But you let me check that and indeed changing an order updates that value (tested with `/characters/{character_id}/orders/`). So that’s already what i need.
