### ISSUE TITLE
Include ship cargo and fitting in /characters/{character_id}/assets

### ISSUE THREAD

**Issue by leetistan** [esi/esi-issues#111]
Currently th endpoint doesn't include items fitted to the ship or items in cargo, xml API includes this data, I think esi should as well, thanks

**Comment by tsuthers-ccpgames** [comment]
Agreed, not sure why it's not returning this info but it should.

**Comment by lukasni** [comment]
Im closing this in favour of #683 since the assets endpoint shouldn't leak fitting info, bit of an intel issue in that. Can be reopened if people disagree with that assessment ^^
