### ISSUE TITLE
Inconsistent data return with alliance data + etag

### ISSUE THREAD

**Issue by cvweiss** [esi/esi-issues#1118]
# Inconsistency

Creating issue at request of CCP Bartender.

On occasion, and with no proof, the alliance endpoint does not return a full set of data when an etag is passed despite underlying information changing. 

This has come from 6 complaints since the beginning of the year about zkillboard.com alliance information not being updated automatically. Clearing the etag for the alliance will cause the information to be updated. This is quite unusual since the member count of an alliance can vary from day to day.

## Routes

Most recent complaint involved this alliance:

https://esi.evetech.net/latest/alliances/99007252/?datasource=tranquility

## Resolution

Ensure etags change when underlying data changes.

# Checklist

Check all boxes that apply to this issue:

- [X] Inconsistency description is provided
- [X] Inconsistent route(s) are provided

**Comment by tsuthers-ccpgames** [comment]
So to be clear, this isn't on the top level /alliances/ endpoint, it's on the alliance details endpoint?

**Comment by cvweiss** [comment]
Yes. Sorry if I wasn't clear about that in slack chat yesterday, I did try to point that out.

**Comment by tsuthers-ccpgames** [comment]
No worries. Can you give me some historical examples so I can go delving and see if there's a common cause?

Approximate dates would be even better if you've got 'em.

**Comment by CarbonAlabel** [comment]
In your issue you mention the member count varying from day to day, but the endpoint you reference doesn't contain member count information.

Which alliance information not being updated were the complaints about? I'm getting the impression you might be misunderstanding what ETags do, or requesting that they change based on information that the endpoint doesn't return.

**Comment by cvweiss** [comment]
So, yea, I'm going to go ahead and close this. Turns out my code wasn't calculating alliance member total when getting a blank response back. ETAGs are working as expected, my brain, not so much.
