### ISSUE TITLE
/fleets/{fleet_id}/members/ & /fleets/{fleet_id}/ GET return "Unhandled internal error encountered!" after 05/28 patch

### ISSUE THREAD

**Issue by AndreyYarovoy** [esi/esi-issues#1121]
After 05/28 patch /fleets/{fleet_id}/members/ & /fleets/{fleet_id}/ stopped working and return http error code 500 with 
{
  "error": "Unhandled internal error encountered!"
}

Response body
Download
{
  "error": "Unhandled internal error encountered!"
}
Response headers
 access-control-allow-credentials: true 
 access-control-allow-headers: Content-Type,Authorization,If-None-Match,X-User-Agent 
 access-control-allow-methods: GET,POST,HEAD,OPTIONS 
 access-control-allow-origin: * 
 access-control-expose-headers: Content-Type,Warning,ETag,X-Pages,X-ESI-Error-Limit-Remain,X-ESI-Error-Limit-Reset 
 access-control-max-age: 600 
 allow: GET,HEAD,OPTIONS,POST 
 content-language: en-us 
 content-length: 49 
 content-type: application/json; charset=UTF-8 
 date: Wed, 29 May 2019 03:54:25 GMT 
 status: 500 
 strict-transport-security: max-age=31536000 
 vary: Accept-Language 
 x-esi-error-limit-remain: 99 
 x-esi-error-limit-reset: 35 
 x-esi-request-id: 9de18e30-b72a-4251-85f0-60c1d5fda5b3 

Steps to reproduce:
1. Create fleet
2. Copy external fleet link and get fleet id from it
3. Open https://esi.evetech.net and navigate to /fleets/{fleet_id}/members/
4. Authorize swagger to read fleet info
5. Execute GET /fleets/{fleet_id}/members/ with fleet_id from step 2. <- get error here

**Comment by tsuthers-ccpgames** [comment]
Related to https://github.com/esi/esi-issues/issues/1113

Being rolled back today
