### ISSUE TITLE
Links on Dev Resources page

### ISSUE THREAD

**Issue by rayanth** [esi/esi-issues#1130]
https://developers.eveonline.com/resource/resources contains broken/outdated URLs and should add additional URLs as starting points.

* FAQ, Question 5, link for 'references' section of documentation points at a dead page on the old read-the-docs
* "Technology Lab Forum" Link in 'external links' section points at the old forums, last used in 2017.
* SDE Documentation points at Read-the-docs. While this is still probably the best resource for SDE at this point, on Read the docs itself, the "edit on github" link gives a github 404.

Suggest Adding:
* Link here, to esi-issues
* Link to ESI playground, https://esi.evetech.net/ui 

(normal bug template not used because it doesn't really apply - this is just the best place I could think of to post this)

**Comment by tsuthers-ccpgames** [comment]
Tech co does not control this webpage, please file a bug report :)
