### ISSUE TITLE
Ability to find out if a character is alpha using ESI.

### ISSUE THREAD

**Issue by guiguilechat** [esi/esi-issues#1131]
I consider this as a bug because IIRC ESI should not give access to alpha state.

There are at least two ways to find out if a character is alpha : 

For an account that has trained omega skills already
---

If one skill have different values on the path "characters/{character_id}/skills/" for
 - active_skill_level
 - trained_skill_level

For any account that is training
---

Using the three paths
 - characters/{character_id}/skillqueue/
 - characters/{character_id}/attributes/
 - universe/types/{type_id}/
 by taking the first training skill in the queue, and getting its effective hourly acquisition rate `eff_rate = 60.0 * (sk.level_end_sp - sk.training_start_sp) / diff_minutes(sk.finish_date - sk.start_date)`
 Then fetching its doma attributes and making its theoretical hourlyy acquisition rate using the attributes values `th_rate = 60.0 * primary + 30.0*secondary`

If the character is accelerated then the attribute difference (assuming the accelerator is about to expire) +12 I think, with a minimum of 17 for any attribute . That means at most, for an omega character, eff_rate/th_rate >17/29 = 0.58

Thus if eff_rate / th_rate <= 0.55 (because maybe rounding issues), then we know the character is an alpha.

**Comment by Blacksmoke16** [comment]
ESI does not directly give access to clone state.  Works as intended.

**Comment by guiguilechat** [comment]
#95

**Comment by Blacksmoke16** [comment]
https://github.com/esi/esi-issues/issues/95#issuecomment-263623670
