### ISSUE TITLE
"characters/{character_id}/ship/" does not working on /dev

### ISSUE THREAD

**Issue by wvdvegt** [esi/esi-issues#1133]
# Bug

Trying to get the path  "characters/{character_id}/ship/" with code that used to work on dev.

## Request

Be sure to include the HTTP method, path (including version), and any relevant parameters. Please do not include auth tokens. E.g.:

`GET  "https://esi.evetech.net/dev/characters/{character_id}/ship/" 

## Response

500 error, not supported on Tranquility.

### Status Code

`500`

### Body

{
  "error" : "Not supported by tranquility."
}

## Expected

Some Json containing the characters ship.

# Checklist

Check all boxes that apply to this issue:

- [x] Bug description is provided
- [x] Request path is provided
- [x] Response status code is provided
- [ ] Response headers are provided
- [x] Response body is provided
- [ ] Expected response is provided

**Comment by tsuthers-ccpgames** [comment]
Important clarification: this is only happening in dev.

It is showing in the UI, both in dev and latest, it's under location. It works correctly in latest, but is listed as not supported in dev.

**Comment by mateuszkrasucki** [comment]
Resolved.
