### ISSUE TITLE
universe_names path does not support character anymore

### ISSUE THREAD

**Issue by guiguilechat** [esi/esi-issues#1134]
https://esi.evetech.net/ui/#/Universe/post_universe_names

"Resolve a set of IDs to names and categories. Supported ID’s for resolving are: Characters, Corporations, Alliances, Stations, Solar Systems, Constellations, Regions, Types, Factions"

This should support a character.

that is me : 
https://esi.evetech.net/latest/characters/95940101/?datasource=tranquility
result ok so my id is valid character

That is jita in the universe_name
`
curl -X POST "https://esi.evetech.net/latest/universe/names/?datasource=tranquility" -H  "accept: application/json" -H  "Content-Type: application/json" -d "[30000142]"`
result : 
```
[
  {
    "category": "solar_system",
    "id": 30000142,
    "name": "Jita"
  }
]
```

that is me in the universe_name 

`curl -X POST "https://esi.evetech.net/latest/universe/names/?datasource=tranquility" -H  "accept: application/json" -H  "Content-Type: application/json" -d "[95940101]"`

result : 
```
{
  "error": "Ensure all IDs are valid before resolving."
}
```

**Comment by guiguilechat** [comment]
workaround : use character path like I do in the first case (to see if my id is correct)

**Comment by tsuthers-ccpgames** [comment]
Yep, we're on it. We've got a fix submitted, we're looking into how early we can get it out right now.

**Comment by maullerz** [comment]
same issue with alliances and corporations

**Comment by tsuthers-ccpgames** [comment]
Yep, all owners except factions are affected.

**Comment by tsuthers-ccpgames** [comment]
Unfortunately this doesn't meet the criticality cut for a friday patch, so we'll be deploying the fix on monday.

**Comment by guiguilechat** [comment]
which month ?

**Comment by r2n2** [comment]
Pity this.  Makes filling out AARs a real PITA now.  Thanks.

**Comment by maullerz** [comment]
This issue affect br.evetools.org. Break it almost at all. So just waiting to fix.

**Comment by ErikKalkoken** [comment]
Here is an overview which categories works and which don't (based on my own testing):

- alliance: NO
- character: NO
- constellation: yes
- corporation: NO
- inventory_type: yes
- region: yes
- solar_system: yes
- station: yes
- faction: yes
 
Obvious workaround is to use the individual routes for those categories to resolve IDs, 
e.g. `/characters/{character_id}/` for character

**Comment by AlexOutten** [comment]
Please can we have:
[
  {
    "category": "citadel",
    "id": 12345678,
    "name": "some dead or private place"
  }
]

As this gives no private structure info away.

I have transactions from structures, that go pop or private before I resolve the name.

**Comment by AlexOutten** [comment]
> Here is an overview which categories currently still work and which don't (based on my own testing) for the route `/universe/names/`:
> 
>     * alliance: NO
> 
>     * character: NO
> 
>     * constellation: yes
> 
>     * corporation: NO
> 
>     * inventory_type: yes
> 
>     * region: yes
> 
>     * solar_system: yes
> 
>     * station: yes
> 
>     * faction: yes
> 
> 
> Obvious workaround is to use the individual routes for those categories to resolve IDs,
> e.g. `/characters/{character_id}/` for character

This causes  404's if a client transaction is looked up, as the transaction endpoint doesn't specify if buyer is char or corp.

**Comment by AlexOutten** [comment]
BTW commenting here as tsuthers-ccpgames slammed the door in my face on the feature request I listed above, without linking this thread, with thanks to Dusty-Meg for the pointer.

**Comment by tsuthers-ccpgames** [comment]
>As this gives no private structure info away.

This does give private structure information away. It gives away the solar system the structure is in, because all structure names contain their solar system. This matter has been discussed on other tickets and at length in the tweetfleet slack.

Alex, this is not reddit. This space is maintained because it is a useful tool for ESI developers. I can see that you have made this github account less than an hour ago and have immediately started leaving a mess on everything you touch. Please develop a sense of professionalism rapidly, or you will no longer be welcome to contribute here.

**Comment by tsuthers-ccpgames** [comment]
Due to issues unrelated to this fix todays patch has been cancelled, which means this is delayed until tomorrow 😢

**Comment by AlexOutten** [comment]
> > As this gives no private structure info away.
> 
> This does give private structure information away. It gives away the solar system the structure is in, because all structure names contain their solar system. This matter has been discussed on other tickets and at length in the tweetfleet slack.
> 
> Alex, this is not reddit. This space is maintained because it is a useful tool for ESI developers. I can see that you have made this github account less than an hour ago and have immediately started leaving a mess on everything you touch. Please develop a sense of professionalism rapidly, or you will no longer be welcome to contribute here.

Quoting your professionalism:
This ticket contains the following:
a) matters that have been discussed at length in other tickets.
b) incorrect speculation on implementation details of the monolith
c) what seems to be a stream-of-consciousness venting of frustration
d) textual yelling.

This is not a productive ticket. I'm just going to close it without further comment.

**Comment by Eveess** [comment]
> Due to issues unrelated to this fix todays patch has been cancelled, which means this is delayed until tomorrow 😢

is this likely to fall into the "wontfix" bracket ?

**Comment by jowrjowr** [comment]
not quite - it falls in the elusive "wontfixuntiltomorrowasispecificallysaid" bracket.

**Comment by Eveess** [comment]
Well it seems it's fixed now was able to log in 30 mins ago


On 19 Aug 2019 18:40, Eric Gisse <notifications@github.com> wrote:

not quite - it falls in the elusive "wontfixuntiltomorrowasispecificallysaid" bracket.

**Comment by guiguilechat** [comment]
I'm afraid you posted on the wrong bug. This bug does not prevent people from logging in.

**Comment by Eveess** [comment]
Sorry I was getting the same error message

On 19 Aug 2019 19:36, guiguilechat <notifications@github.com> wrote:

I'm afraid you posted on the wrong bug. This bug does not prevent people from logging in.

**Comment by tsuthers-ccpgames** [comment]
@Eveess you're leaving the github email footers in the messages when you post. They seem to contain some kind of secret token in a URL, I've edited your posts to remove the tokens.

**Comment by tsuthers-ccpgames** [comment]
The fix for this has been deployed
