### ISSUE TITLE
Non failing ID resolution (no 404's)

### ISSUE THREAD

**Issue by AlexOutten** [esi/esi-issues#1135]
# Feature Request

## Use case

Current problem with alliance/char/corp on /universe/names/ was a killer to most apps.

Resolving multiple bad hits to ESI DB & local faults occurring from 404's then onto 420's

Success would require an Auth lookup on another endpoint for more detail.

## Authentication

No Auth should be fast public request, no error should be generated (except for spamming for bogus IDs rate limit?)

Straight flat json served from a once a day db generation/dump. 404 message replaced with 200 json[{valid:0}]

All IDs we have were provided from your data, so 404 should never be served.

Would substantially reduce DB loads both ends & error limiting.

/universe/id/

Singular, as the current system fails at ESI end & when an ID is no longer valid or suddenly made private.

## Example return

```json
[
  {
    "valid":["1|0"],
    "type": "[alliance|citadel|character|corporation|item|moon|planet|station|type|et al]",
    "name": "name"
  }
]
```
# name should always be available when id is valid, even for a closed private citadel, else how did we have the ID in transactions in the first place.
Name of citadel doesn't give any private or location information away.
Same for deleted Characters, Corps, Alliances (as IDs not reused)

No other info, as Authenticated endpoints should be used for further detail

# Checklist

Check all boxes that apply to this issue:

- [x] Feature request description is provided
- [x] Use case exists
- [x] Feature requires a new route
- [ ] Feature adds data to existing route
- [ ] Feature requires new auth scope
- [x] Feature can reuse existing scope
- [x] Feature does not require auth
- [ ] Meta feature, applies to all routes

**Comment by tsuthers-ccpgames** [comment]
This ticket contains the following:
a) matters that have been discussed at length in other tickets.
b) incorrect speculation on implementation details of the monolith
c) what seems to be a stream-of-consciousness venting of frustration
d) all caps.

This is not a productive ticket. I'm just going to close it without further comment.

**Comment by AlexOutten** [comment]
As you're now using ID's without contiguous ranges we have no method of trapping an error in a range to search for Corp/Alliance/Item. Even when the ID is provided by ESI. Programming errors can still be trapped by counting your side valid:0 as rate limit.
Currently checking endpoints
/alliances/{id}/
/characters/{id}/
/corporations/{id}/

**Comment by Dusty-Meg** [comment]
See #1134

**Comment by AlexOutten** [comment]
> See #1134

Thank you...

**Comment by AlexOutten** [comment]
> This ticket contains the following:
> a) matters that have been discussed at length in other tickets.
> b) incorrect speculation on implementation details of the monolith
> c) what seems to be a stream-of-consciousness venting of frustration
> d) textual yelling.
> 
> This is not a productive ticket. I'm just going to close it without further comment.

As a response developer to developer.
a) I wouldn't class #1134 as `at length`
b) I have neither speculated nor am aware of your monolithic implementation measures, just made an honest request.
c) You'll have to point out the venting part, as all us programmers are frustrated.
d) As my first ever post on GitHub, I wasn't aware of the formatting that would be highlighted when the post was put up. AFAIK TYPE IN CAPS IS STILL CONSIDERED YELLING, or has that changed?

I find your bulleted list & final comment both curt & insulting.

Now real venting is:
Most of my Eve Dev accounts are on eve@outten.co.uk
Sites are on http://eve.outten.co.uk/secure
http://www.newedendirectory.co.uk/
& eve https server are at 86.7.154.214
Kick me & my space accounts, you cheeky ****.
