### ISSUE TITLE
[small qol] opening market from ESI opens the groups window first, which can take some times

### ISSUE THREAD

**Issue by guiguilechat** [esi/esi-issues#1136]
When using the path
https://esi.evetech.net/ui/#/User%20Interface/post_ui_openwindow_marketdetails

ig my toons opens the "groups" tabs in the "market" window first, which can be slow to load.
if the market window is already opened it just works correctly.
If I keep an item info in the game, and click" show market details" I don't have this issue ingame.
I checked on another toon and AFTER using the group windows, it also opens on the group window from the ESI (before, it did not).

I suspect market window management has been slightly changed ig and the ESI handler does not know (maybe a param added with default value ? )

**Comment by tsuthers-ccpgames** [comment]
Hrm, I can't repro this. If I put in a valid ID it always opens to the details tab of the item no matter what.

What I did find is that if I put in an invalid ID then if the market window is open it does nothing, but if the market window is closed it opens the market window on the groups tab of the last thing that I manually opened the groups tab on. Kinda weird behavior, any chance it's what you're experiencing?

What types are you testing this on BTW?

**Comment by guiguilechat** [comment]
the types were correct, since it opens them.
I tested with a list of items including ladar sensor cluster, capital core defense field extender I, …

I'm trying to install a working recorder on my ubuntu. better do it with a recording.

**Comment by guiguilechat** [comment]
hmm I had to reboot because updates during my recording unsuccesses and now I don't have this issue anymore.

I uploaded the vids on youtube (private videos) that show the issue very clearly (with FPS window to notice when the game window is actually frozen)

So I close it because it seems gone with a reboot. Maybe it my launcher was not updated since last update ? I remember relaunching it recently as it requested it.

**Comment by guiguilechat** [comment]
grr it just started doing it again :fuuuuuu:

**Comment by guiguilechat** [comment]
https://youtu.be/DOb58lPfy6E?t=39

I added the timestamp when it happens (it does not always happen, but after some time it seems it starts happening)
you see very clearlry it starts opening the group for capital armor rigs before loading the ladar sensor cluster.
before that I do a lot of tries to do it. call ESI ui, close market window, rinse and repeat.

**Comment by tsuthers-ccpgames** [comment]
Oh, I see what you're talking about now. Unfortunately, how the client elects to follow an "open this market window" command is very much outside tech co's remit. We're invoking this the same way the "show market information" button does on various items.

**Comment by guiguilechat** [comment]
should I make a bug report ingame ?

**Comment by guiguilechat** [comment]
Also I may have a vid showing very clearly that when I open from the game I have no issue, but when I open from ESI there can be issue, with several tries, alternating both.
I made a lot of vids about that but they are bad ; and it contains personal informations though (reason why I did not publish it).

**Comment by tsuthers-ccpgames** [comment]
Given that there's a really good video showing it, I would, just be aware that it'll probably end up pretty low priority in the bug queue and it might be a while before there's movement on it.

**Comment by guiguilechat** [comment]
delegated to the game team through EBR-181207
