### ISSUE TITLE
dogma/attributes/ returns error 500 after DT

### ISSUE THREAD

**Issue by asvpdev** [esi/esi-issues#1142]
# Bug
Path is https://esi.evetech.net/dev/dogma/attributes/?datasource=tranquility 
returns error 500 after DT
## Request
https://esi.evetech.net/dev/dogma/attributes/?datasource=tranquility

### Status Code
500
### Headers

date: Tue, 10 Sep 2019 22:25:31 GMT 
etag: W/"133fb449ab195276656880e7af4d08dea34d66f005b708fdf1c5841a" 
status: 500 
x-esi-request-id: cfa9553f-f457-4c59-aa94-fb557e801151

### Body
{
  "error": "Unhandled internal error encountered!"
}

**Comment by mateuszkrasucki** [comment]
invalid, temporary error.
