### ISSUE TITLE
Market Group not found

### ISSUE THREAD

**Issue by asvpdev** [esi/esi-issues#1143]
# Bug
## Request 1
https://esi.evetech.net/dev/universe/types/52306/?datasource=tranquility&language=ru
## Response 1
{
  "capacity": 0,
  "description": "...",
  "dogma_attributes": [
   ...
  ],
  "graphic_id": 24434,
  "group_id": 4029,
  "icon_id": 24136,
  **"market_group_id": 2540,**
  "mass": 0,
  "name": "Talassonite",
  "packaged_volume": 16,
  "portion_size": 100,
  **"published": true,**
  "radius": 1,
  "type_id": 52306,
  "volume": 16
}
## Request 2
https://esi.evetech.net/dev/markets/groups/2540/?datasource=tranquility&language=ru
### Status Code
404
### Body
{
  "error": "Market Group not found!"
}
### Header
date: Tue, 10 Sep 2019 22:37:01 GMT 
 etag: W/"133fb449ab195276656880e7af4d08dea34d66f005b708fdf1c5841a" 
 status: 404 
  x-esi-request-id: 56df56d6-60dc-498b-8fe7-4cb47dee0c8d

**Comment by lukasni** [comment]
This is actually an issue that exists in game, the triglavian ores aren't searchable in the market, would close this as it's not an issue with ESI, the API is just reporting the data from the game. I would at least recommend opening an EBR

**Comment by asvpdev** [comment]
What is EBR?

**Comment by rayanth** [comment]
an EBR is an official bug report for the game, from a player - log in on https://community.eveonline.com/ and go to 'bug reports' under the Support menu

**Comment by guiguilechat** [comment]
Eve Bug Report ?
https://community.eveonline.com/support/bug-reports/

**Comment by rayanth** [comment]
I submitted this. EBR-182082 for the ISD BH team to look at.

**Comment by rayanth** [comment]
The triglavian ores are now searchable, both via ESI and in-game - suggest closing this issue.

**Comment by lukasni** [comment]
Hm, I can confirm the market group is now returned correctly, however a search for "Talassonite" still returns an empty result set for met on `/search/`

https://esi.evetech.net/v2/search/?categories=inventory_type&search=Talassonite&strict=false

**Comment by lukasni** [comment]
This has been addressed in a recent EVE patch, both market group and search now work as expected.
