### ISSUE TITLE
Get citadel ID from citadel name

### ISSUE THREAD

**Issue by Zyles** [esi/esi-issues#1146]
# Feature Request

Is this fixed yet?

I can't get the citadel ID and it does not show up in the structure list.

How do I get a citadel ID (I have access)?

## Use case

Getting a citadel ID from a citadel by name.

Otherwise how would I go about getting the ID?

## Authentication

Yes

# Checklist

Check all boxes that apply to this issue:

- [x] Feature request description is provided
- [x] Use case exists
- [x] Feature requires a new route
- [ ] Feature adds data to existing route
- [ ] Feature requires new auth scope
- [x] Feature can reuse existing scope
- [ ] Feature does not require auth
- [ ] Meta feature, applies to all routes

**Comment by lukasni** [comment]
The [authorized search endpoint](https://esi.evetech.net/ui/#/Search/get_characters_character_id_search) can be used for that.

**Comment by lukasni** [comment]
And please don't use the issue page to vent your frustrations. Flooding the issues with frivoulous requests does not help in getting the features you require added, it just makes people less likely to want to interact with you. 

That said, if you're willing to have a reasoned discussion the #esi channel on tweetfleet is a good place to field general questions on how to use ESI. You can join the slack group [here](https://www.fuzzwork.co.uk/tweetfleet-slack-invites/)
