### ISSUE TITLE
Latest /alliances/{alliance_id}/ false upgrade warning due to outdated version in /dev/

### ISSUE THREAD

**Issue by winterwings** [esi/esi-issues#1157]
# Inconsistency

_Note: I use versioned specs `_latest`, but the warning is in place for `latest` as well._

On alliance info request I get this header: `warning: 199 - This route has an upgrade available`  
...while changelog does not mention a change on this endpoint since 2017.

I suspect it is caused by versioned \_dev specs containing outdated v2 endpoint, while \_latest has v3.  
See for yourself:

- \_latest: https://esi.evetech.net/ui/?version=_latest#/Alliance/get_alliances_alliance_id -- v3
- \_dev: https://esi.evetech.net/ui/?version=_dev#/Alliance/get_alliances_alliance_id -- v2

You may also try it out to see the header in the response for both of them.

## Routes

- `GET /v3/alliances/{alliance_id}/`

## Resolution

Update `/alliances/{alliance_id}/` in Dev specs to the latest version (v3).  
_Or you plan to rollback? That's confusing._

# Checklist

Check all boxes that apply to this issue:

- [ ] Inconsistency description is provided
- [x] Inconsistent route(s) are provided
- [x] Resolution [will require a version bump](https://docs.esi.evetech.net/docs/breaking_changes)
- [ ] Resolution [does not require a version bump](https://docs.esi.evetech.net/docs/breaking_changes)

**Comment by mateuszkrasucki** [comment]
Solved.
