### ISSUE TITLE
Be able to batch query multiple character IDs

### ISSUE THREAD

**Issue by Rihoj** [esi/esi-issues#1160]
When developing third party applications you often have to worry about the removal of roles based on corp status, but want to still allow the character to be part of the community in a more limited way. The first part is easy using the corporation/corp_id/members. However, proceeding to update all characters not associated with the corp then comes down to hitting the characters/character_id route x amount of times. This puts more strain on the eve esi as well as longer wait times on the developers app because we have to either call async or wait for each individual request and update.

I propose that we are given an option to batch these requests through a /characters/ post route  where we can submit up to maybe 50 character_ids at once and get back a collection of character information.

**Comment by Blacksmoke16** [comment]
Any reason you couldn't just use https://esi.evetech.net/ui/#/Character/post_characters_affiliation ?

**Comment by winterwings** [comment]
I check every character hourly with the following approach:
1. Call [post_characters_affiliation](https://esi.evetech.net/ui/#/Character/post_characters_affiliation) (as mentioned above) for every 1000 characters.
2. On every call loop through the result, check for differences with the data you already have in DB. If there was a difference, update info for these characters individually, as you do on a registration process.
   Note: If you intend to leave them in a DB, don't forget to drop roles/titles that were updated on this step! So they won't get stuck with old roles/titles in a new corporation you don't have access for (see next step).
3. Lastly, for every _corporation_ in DB request [get_corporations_corporation_id_roles](https://esi.evetech.net/ui/#/Corporation/get_corporations_corporation_id_roles) and [get_corporations_corporation_id_titles](https://esi.evetech.net/ui/#/Corporation/get_corporations_corporation_id_titles) to update roles and titles for all characters.

Using this approach saves a lot of requests and time. For ~8000 and ~70 corporations, it takes about one minute or so with roughly 8+70+70=148 requests on a clear day (no characters has changed their corp/alliance).

**Comment by ddouglas** [comment]
Unless you are tracking security status, @Blacksmoke16 answer is correct
