### ISSUE TITLE
New shared bookmarks API

### ISSUE THREAD

**Issue by lenyapugachev** [esi/esi-issues#1161]
# Feature Request

When new bookmark engine will be available though ESI? Are developers having some information?

**Comment by rayanth** [comment]
https://developers.eveonline.com/blog/article/temporary-blackout-of-esi-bookmarks

**Comment by lenyapugachev** [comment]
> https://developers.eveonline.com/blog/article/temporary-blackout-of-esi-bookmarks

Yeah, but there are no information about WHEN it happens.

**Comment by rayanth** [comment]
> > https://developers.eveonline.com/blog/article/temporary-blackout-of-esi-bookmarks
> 
> Yeah, but there are no information about WHEN it happens.

And creating an issue on esi-issues just to ask "when", when they have not provided information on that in any other channel yet, isn't going to suddenly make them decide "Oh, we better tell this guy!".

Have you joined us on tweetfleet Slack? You're likely to get far more up-to-date info there, CCP even visits and talks to us, it's great! There's a link to where to get an invite on the esi-issues front page, but i'll toss it here, too : https://www.fuzzwork.co.uk/tweetfleet-slack-invites/  the #esi channel's the one you'll want for this type of question.

**Comment by lenyapugachev** [comment]
Hey, I'm new here, "let me suck" :)

I've tried to join the Slack, but there are no fields to fill on https://www.fuzzwork.co.uk/tweetfleet-slack-invites/, I thought it is broken

**Comment by lenyapugachev** [comment]
Figure that outб you gotta be logged in through EVE on fuzz to have a email field

**Comment by rayanth** [comment]
> Hey, I'm new here, "let me suck" :)
> 
> I've tried to join the Slack, but there are no fields to fill on https://www.fuzzwork.co.uk/tweetfleet-slack-invites/, I thought it is broken

My apologies. My reply was a little harsh. been a long day.

Please read the instructions on the URL carefully -- they indicate you must first log in with Eve SSO, to get the email field to show.

**Comment by lenyapugachev** [comment]
Thanks for answers! :)
