### ISSUE TITLE
Date Deleted for Contracts

### ISSUE THREAD

**Issue by alexbaileyuk** [esi/esi-issues#1162]
# Feature Request

There is currently no way to see through the ESI when a contract was manually deleted. I would like to see a property such as `date_deleted` which would be similar to the exising properties for `date_expired` etc. I guess another option would be updating the `date_expired` when you delete a contract but then you lose data of when the contract was due to expire.

## Use case

Players who manage contracts on a large scale for alliances or anyone looking at pulling ESI data for contracts.

Example: I share a corporation with other players which manages hundreds of contracts each month. I would like to be able to pull data which tells me if someone is taking contracts down and either keeping the assets, relisting them somewhere else or selling them to another party.

## Authentication

Yes. It would use the existing scopes for reading personal/corporation contracts respectively.

## Example return

Propose what an example return might look like. E.g.:

```json
[
  {
    "acceptor_id": 0,
    "assignee_id": 123456789,
    "availability": "personal",
    "collateral": 0,
    "contract_id": 123456789,
    "date_deleted": "2019-12-26T07:00:00Z",
    "date_expired": "2020-01-17T18:38:31Z",
    "date_issued": "2019-12-20T18:38:31Z",
    "days_to_complete": 0,
    "end_location_id": 123456789,
    "for_corporation": true,
    "issuer_corporation_id": 123456789,
    "issuer_id": 123456789,
    "price": 123456789,
    "reward": 0,
    "start_location_id": 123456789,
    "status": "deleted",
    "title": "My Deleted Contract",
    "type": "item_exchange",
    "volume": 0
  },
  ... more contracts
]
```

# Checklist

Check all boxes that apply to this issue:

- [x] Feature request description is provided
- [x] Use case exists
- [ ] Feature requires a new route
- [x] Feature adds data to existing route
- [ ] Feature requires new auth scope
- [x] Feature can reuse existing scope
- [ ] Feature does not require auth
- [ ] Meta feature, applies to all routes

**Comment by GoldenGnu** [comment]
Doesn't it set `date_completed` when deleted? That is the behavior I would expect.
