### ISSUE TITLE
Assets Locations Endpoint throw errors to Customs Office Gantry in hangars

### ISSUE THREAD

**Issue by wfjsw** [esi/esi-issues#1164]
# Bug

When item_ids contains Customs Office Gantry where it exists in either Item Hangars or Corporation Hangars, the endpoint throws an error.

## Request

```
GET https://esi.evetech.net/v2/corporations/98049623/assets/locations/?datasource=tranquility
Accept: application/json
Content-Type: application/json
User-Agent: Eseye/1.1.7/SeAT v3.0.17

[1014816906880]
```

### Status Code

`400`

### Body

```
Invalid IDs in the request
```

## Expected

As described in endpoint docs:

```
Coordinates for items in hangars or stations are set to (0,0,0)
```

# Checklist

Check all boxes that apply to this issue:

- [x] Bug description is provided
- [x] Request path is provided
- [x] Response status code is provided
- [ ] Response headers are provided
- [x] Response body is provided
- [x] Expected response is provided

**Comment by mateuszkrasucki** [comment]
This should be fixed now.
