### ISSUE TITLE
Request expires header is same as request time

### ISSUE THREAD

**Issue by Flupster** [esi/esi-issues#1166]
## Request

Any request afaik but testing was done on character location endpoint

### Headers

```
date: 'Sun, 12 Jan 2020 13:35:47 GMT',
content-type: 'application/json; charset=UTF-8',
content-length: '57',
connection: 'keep-alive',
expires: 'Sun, 12 Jan 2020 13:35:47 GMT',
last-modified: 'Sun, 12 Jan 2020 13:35:42 GMT',
strict-transport-security: 'max-age=31536000',
x-esi-request-id: '04b8b961-3b78-49d3-bb8b-1dc3b6c47517'
```

## Expected

Just reporting that the expires header and the date header are the same  
Not sure if this intended and is a potential bug, my code checks for the expires header and caches the response and throws errors if <0

If this isn't a bug just close it out :)

**Comment by lukasni** [comment]
Location is on a very short cache timer, seems like you _just_ missed the cache invalidation timer on that request. If you look at last_modified it's 5s before your date, which just so happens to match the expires header. Try adding a little bit of extra buffer time before refreshing your location.

**Comment by Flupster** [comment]
> Location is on a very short cache timer, seems like you _just_ missed the cache invalidation timer on that request. If you look at `last-modified` it's 5s before your `date`, which just so happens to match the `expires` header. Try adding a little bit of extra buffer time before refreshing your location.

I think my clock was desync'd, I'll use the date header instead of local time :) Thanks for pointing out last modified header, I thought this was the initial request returning a 0s expire time
