### ISSUE TITLE
Endpoints /dogma/dynamic/items/ and /dogma/attributes/ disappeared

### ISSUE THREAD

**Issue by Migi** [esi/esi-issues#1169]
# Bug

The route /dogma/dynamic/items/{type_id}/{item_id}/ for requesting the dynamic attributes of abyssal items returns 404 "Not found" for all type_id and item_id combinations. Other "dogma" routes, like /dogma/attributes, have also disappeared.

This is not listed on the changelog, so I don't think it's intentional. As far as I can tell, the route didn't get renamed or moved. It's just gone, and there is no alternative way to get the same information. The documentation about these routes is also not listed on [https://esi.evetech.net/ui/](https://esi.evetech.net/ui/) anymore.

This breaks widely-used sites like [mutaplasmid.space](https://mutaplasmid.space/) where it is no longer possible to [appraise](https://mutaplasmid.space/appraisal/) new items, and contracts with freshly rolled items are not being listed. Old items are still in its database, but if this route remains gone it would be a big blow to the abyssal market.

## Request

`GET https://esi.evetech.net/latest/dogma/dynamic/items/49734/1032178821320/?datasource=tranquility`

### Status Code

`404`

### Headers

Not really relevant I think, but for completeness sake:

Header | Value
-- | --
X-Firefox-Spdy | h2
access-control-allow-credentials | true
access-control-allow-headers | Content-Type,Authorization,If-None-Match,X-User-Agent
access-control-allow-origin | *
access-control-expose-headers | Content-Type,Warning,ETag,X-Pages,X-ESI-Error-Limit-Remain,X-ESI-Error-Limit-Reset
access-control-max-age | 600
content-language | en-us
content-length | 21
content-type | application/json; charset=utf-8
date | Sun, 19 Jan 2020 14:37:20 GMT
strict-transport-security | max-age=31536000
vary | Accept-Language
x-esi-error-limit-remain | 99
x-esi-error-limit-reset | 40

### Body

```json
{"error":"Not found"}
```

**Comment by DianaOlympos** [comment]
This is due to bugs and change introduced on the last big patch of the game servers.

There is work happening to try to fix it, the last communication by CCP is

>>> ok so.... esi-dogma is out for at least the weekend, and honestly Tuesday is probably a safer estimate for it coming back online

In general the last release broke a couple of things

> 
> ccp_blaraka Announcement: As you all know there are problems with certain ESI endpoints that started with today's release.
> 
> Most endpoints should be back, including alliance, corporation and character. There well indeed all down for a moment. Please do report if there any problems persisting with endpoints not mentioned below.
>Stars endpoint will be investigated tomorrow. 
> Due to bug introduced today in the game servers we need to disable GET /corporations/{corporation_id}/facilities/ from now untill it's fixed. It should be back latest beginning of next week.
>As dogma endpoints became more or less useless it's also disabled. For now we cannot commit to any timeframe for them coming back but we will start working on it tomorrow.

**Comment by Migi** [comment]
Thank you, it's good to know that CCP is aware of the issue. Where was that announcement posted? I can't find it on Google.

**Comment by DianaOlympos** [comment]
In the tweetfleet #esi Slack channel, which is considered by ccp as the place to communicate with the community around ESI for things that do not have to go through official PR

**Comment by gitAskur** [comment]
Fix made it into todays deployment so I should be able to online the endpoints again in a few hours. I am going to start trying to get into the habit of remembering this repo exists, and other avenues of communication so people are not sitting in the dark.

At some point soon we'll get access to quickly push out 3rd party dev announcements, but I imagine I'd still announce them on Slack as well since it is just a better platform for feedback. At any rate I'll probably forget to close this after onlining the endpoints since I keep forgetting this issue repo exists, so if you are reading this after esi-dogma is back online can you remind me that I did not forget to forget to close this issue and that I need to stop forgetting that the esi-issues repo exists thanks!

**Comment by gitAskur** [comment]
I REMEMBERED!
