### ISSUE TITLE
Wallet Journal missing HyperNode entries

### ISSUE THREAD

**Issue by GoldenGnu** [esi/esi-issues#1171]
# Bug

Journal responses are missing entries for "Purchased a HyperNode", the entries are present in-game, but, not via the ESI.
Like because, there is no `ref_type` enum entry for "Purchased a HyperNode", so it is ignored by ESI (to avoid errors).

See also:
https://github.com/esi/eve-glue/blob/master/eve_glue/wallet_journal_ref.py

~~EDIT: I should note, this is a breaking change and _should_ require a version bump~~
This is no longer a breaking change

## Request

`GET /v6/characters/{character_id}/wallet/journal/`

May also apply to (but, I'm not 100% sure):
`GET /v4/corporations/{corporation_id}/wallets/{division}/journal/`

# Checklist

Check all boxes that apply to this issue:

- [x] Bug description is provided
- [x] Request path is provided
- [ ] Response status code is provided
- [ ] Response headers are provided
- [ ] Response body is provided
- [ ] Expected response is provided

**Comment by mateuszkrasucki** [comment]
Update deployed on live.
