### ISSUE TITLE
Corp wallet journal limit not just 30 days, but also 10000 records

### ISSUE THREAD

**Issue by winterwings** [esi/esi-issues#1172]
# Bug

We've started to track jump bridge network usage using corp wallet journal and stumbled on an issue.

Endpoint in question: `/corporations/{corporation_id}/wallets/{division}/journal/`

Quote from ESI docs: _Retrieve the given corporation’s wallet journal for the given division going 30 days back._  
This 30 days rule worked fine before, but now we have a jb network that generates a high amount of records in a journal. 10 pages return a normal amount of records (10000 in total, 1000 per page), but the earliest record dated Jan 26, which is only less than a week old.

I believe this is an additional undocumented limitation that shouldn't be there.

## Request and response details

Request: `GET /corporations/{corporation_id}/wallets/{division}/journal/?page=10`
Response:
* Status Code: `200`  
* Header: `x-pages: 10`  
* Body: Normal response with 1000 records, down to Jan 26

Request: `GET /corporations/{corporation_id}/wallets/{division}/journal/?page=11`  
Response:
* Status Code: `200`  
* Header: `x-pages: 10`  
* Body: `[]` (empty array)

## Expected

Much more pages, much more records...

# Checklist

Check all boxes that apply to this issue:

- [x] Bug description is provided
- [x] Request path is provided
- [x] Response status code is provided
- [x] Response headers are provided
- [x] Response body is provided
- [x] Expected response is provided

**Comment by lukasni** [comment]
Can you check if you can see wallet journal entries that go further back than that in the actual EVE client? If the same limit exists in game the ESI endpoints won't be able to fetch more than that

**Comment by gitAskur** [comment]
This is a hardcoded constraint that applies to the client as well. ESI cannot offer any advantages over the desktop client so I am closing this. If the client limitation changes and ESI is not affected, feel free to reopen this or create a new issue.

**Comment by lukasni** [comment]
@winterwings You _could_ report this as a client bug through the client bug report tool, if you do, reference the EBR # in this issue
