### ISSUE TITLE
Chat Channels

### ISSUE THREAD

**Issue by Mikeyspud** [esi/esi-issues#1173]
# Feature Request

I would like to be able to pull a characters local chat and view who is in system alongside the player character - regardless of standing. Working on an application that can map an Alliance Real-time - giving directors a bird's eye view of their corporation/alliance.

## Use case

Primary Consumer would be CEO's and people of similiar importance.

## Authentication

This feature would use existing scopes

Would require a new route
eg characters/character_id/local OR chat?local OR chat_channels?local

## Example return

Propose what an example return might look like. E.g.:

```json
{
 [ 
   player1,
   player2,
   player3.
  ]
}
```

# Checklist

Check all boxes that apply to this issue:

- [ x] Feature request description is provided
- [x ] Use case exists
- [] Feature requires a new route
- [x] Feature adds data to existing route
- [ ] Feature requires new auth scope
- [x] Feature can reuse existing scope
- [ ] Feature does not require auth
- [ ] Meta feature, applies to all routes

**Comment by Dusty-Meg** [comment]
If you are looking at getting locations and online status of characters you can get ESI keys from then you could use a mix of.
/characters/{character_id}/location/
/characters/{character_id}/online/

The issue with this request is its not currently possible to easily do this in game so the likelihood of the game design team to accept this is slim to none.

**Comment by lukasni** [comment]
This would making intel bots completely trivial and is thus _very_ unlikely not to be shot down by game design, but I'll leave it open for now

**Comment by ddouglas** [comment]
This is already possible using the corporation member tracking endpoint

https://esi.evetech.net/ui/#/Corporation/get_corporations_corporation_id_membertracking
