### ISSUE TITLE
Constant 504 gateway timed out errors

### ISSUE THREAD

**Issue by jtrenaud1s** [esi/esi-issues#1176]
# Bug

Any endpoint on any method, even just visiting the esi.evetech.net/ui/ website simply returns an error 504 gateway timed out.

## Request

any request, example:
https://esi.evetech.net/latest/markets/10000002/history/?datasource=tranquility&type_id=34

## Response

504 Gateway Time-out

### Status Code

`504`

### Headers

```
Server →awselb/2.0
Date →Mon, 02 Mar 2020 12:32:58 GMT
Content-Type →text/html
Content-Length →148
Connection →keep-alive
```

### Body

```html
<html>
    <head>
        <title>504 Gateway Time-out</title>
    </head>
    <body bgcolor="white">
        <center>
            <h1>504 Gateway Time-out</h1>
        </center>
    </body>
</html>
```

## Expected

`200`

# Checklist

Check all boxes that apply to this issue:

- [x ] Bug description is provided
- [x ] Request path is provided
- [x ] Response status code is provided
- [x ] Response headers are provided
- [x ] Response body is provided
- [x ] Expected response is provided

**Comment by BlubQ** [comment]
Quoting CCP Blaraka:

>ANNOUNCEMENT
ESI DOWNTIME until ~16:00UTC+ today (2nd March 2020)
Due to some housekeeping that needs to be done, all ESI endpoints were shutdown at 12:00 UTC today. The downtime will last at least 4 hours, so until 16:00 UTC.
