### ISSUE TITLE
500 Error on Corporation Wallet Journal endpoint

### ISSUE THREAD

**Issue by pvyParts** [esi/esi-issues#1177]
# Bug

When requesting corporate wallet journal ESI returns a 500 error.

## Request

`https://esi.evetech.net/latest/corporations/1639878825/wallets/1/journal/?datasource=tranquility&page=1&token=#####`

### Status Code

`500`

### Headers

```
date: Wed, 11 Mar 2020 11:22:48 GMT 
status: 500
x-esi-request-id: f589d6b6-527a-443b-a0bb-a5f32a0970d0
```

### Body

Please provide the response body, feel free to scrub any opsec details you wish. E.g.:

```json
{
  "error": "Unhandled internal error encountered!"
}
```

## Expected

wallet data json with `200` response

# Checklist

Check all boxes that apply to this issue:

- [x] Bug description is provided
- [x] Request path is provided
- [x] Response status code is provided
- [x] Response headers are provided
- [x] Response body is provided
- [x] Expected response is provided

**Comment by Xamber** [comment]
It will be fixed soon.
I will let you know when it's ok.

**Comment by jeronica** [comment]
Confirmed for 3 corporations I have endpoints for too. Seems to be related to the new journal entries with the patch? Division 1 fails, division 2 etc pull just fine.

**Comment by Xamber** [comment]
Hello again, guys!
Issue was fixed and should be deployed during next downtime 🤗 

Sorry for the inconvenience!
Have a perfect evening!

**Comment by pvyParts** [comment]
Can confirm this is fixed for me! Thanks guys!
