### ISSUE TITLE
/markets/{region_id}/orders/ not returning sell orders for some regions

### ISSUE THREAD

**Issue by webwizrd** [esi/esi-issues#1189]
# Bug

When accessing the ESI via https://esi.evetech.net/ui/#/Market/get_markets_region_id_orders, only the buy orders are being shown for some regions (verified vs. ingame - there are actually sell orders), while both buy and sell orders are shown for others.

Example: no buy oders at all returned for Feythabolis and Catch, while Devoid, Domain and Delve return as expected.

## Request

https://esi.evetech.net/latest/markets/10000056/orders/?datasource=tranquility&order_type=sell&page=1

## Response

[]

### Status Code

304

### Headers

access-control-allow-credentials: true 
 access-control-allow-headers: Content-Type,Authorization,If-None-Match,X-User-Agent 
 access-control-allow-methods: GET,HEAD,OPTIONS 
 access-control-allow-origin: * 
 access-control-expose-headers: Content-Type,Warning,ETag,X-Pages,X-ESI-Error-Limit-Remain,X-ESI-Error-Limit-Reset 
 access-control-max-age: 600 
 allow: GET,HEAD,OPTIONS 
 cache-control: public 
 content-length: 2 
 content-type: application/json; charset=UTF-8 
 date: Sat, 04 Apr 2020 10:11:39 GMT 
 etag: "ed2e5773d709f4a0654d954884b08db4e152aeb8a70cb70b54e01bc4" 
 expires: Sat, 04 Apr 2020 10:15:31 GMT 
 last-modified: Sat, 04 Apr 2020 10:10:31 GMT 
 status: 304 
 strict-transport-security: max-age=31536000 
 x-esi-error-limit-remain: 100 
 x-esi-error-limit-reset: 21 
 x-esi-request-id: 135a114f-59ef-4084-ae83-5d7697fcbea2 
 x-pages: 1

### Body

[]

## Expected

List of sell orders in Feythabolis (quite a few),

# Checklist

Check all boxes that apply to this issue:

- [x ] Bug description is provided
- [ x] Request path is provided
- [ x] Response status code is provided
- [ x] Response headers are provided
- [ x] Response body is provided
- [ x] Expected response is provided

**Comment by fuzzysteve** [comment]
Sell orders in structures never show up on the region. Only in stations. This is so that you know that all orders you can see with the region endpoint are open to all. 
_ranged_ buy orders show up. But only ranged ones.

You'll have to query each of the structures in turn to see market orders in them.
