### ISSUE TITLE
Typo in description for market group 1337

### ISSUE THREAD

**Issue by Ionaru** [esi/esi-issues#1203]
# Bug

There is a typo in the description for market group 1337. It says "firth" instead of "fifth".

## Request

`GET https://esi.evetech.net/v1/markets/groups/1337/?datasource=tranquility&language=en-us`

### Status Code

`200`

### Body

```json
{
   "description":"The firth and final tier of planetary materials.",
   "market_group_id":1337,
   "name":"Advanced Planetary Materials",
   "parent_group_id":1332,
   "types":[
      2867,
      2868,
      2869,
      2870,
      2871,
      2872,
      2875,
      2876
   ]
}
```

## Expected

```json
{
   "description":"The fifth and final tier of planetary materials.",
   "market_group_id":1337,
   "name":"Advanced Planetary Materials",
   "parent_group_id":1332,
   "types":[
      2867,
      2868,
      2869,
      2870,
      2871,
      2872,
      2875,
      2876
   ]
}
```

# Checklist

Check all boxes that apply to this issue:

- [x] Bug description is provided
- [x] Request path is provided
- [x] Response status code is provided
- [x] Response body is provided
- [x] Expected response is provided

**Comment by CarbonAlabel** [comment]
Not an ESI issue, EVE bug reports should be filed for things like this: https://community.eveonline.com/support/bug-reports/

**Comment by Blacksmoke16** [comment]
Oops, was thinking it was a typo in the swagger doc description for market groups.
