### ISSUE TITLE
[GET] /fleets/{fleet_id}/members/ should return the 3 leadership skills of each member

### ISSUE THREAD

**Issue by ConorOD** [esi/esi-issues#1207]
# Feature Request

Fleet endpoint should contain the leadership skills of members. Currently, this is visualised in the fleet member screen in-game. 

## Use case

Fleet commanders trying to organise wings efficiently and quickly to provide the best boots to fleet members.

## Authentication

Uses all the existing scopes and auth requirements of the fleet endpoint

## Example return

```json
[
  "skills": {
    "leadership": 5,
    "wing_command": 5,
    "fleet_command": 5
  },
  ...99 other people
]
```

# Checklist

Check all boxes that apply to this issue:

- [x] Feature request description is provided
- [x] Use case exists
- [ ] Feature requires a new route
- [x] Feature adds data to existing route
- [ ] Feature requires new auth scope
- [x] Feature can reuse existing scope
- [ ] Feature does not require auth
- [ ] Meta feature, applies to all routes

**Comment by Lucius-Q-User** [comment]
FYI, boosts have been reworked more than a year ago and no longer require leadership skills for wing/squad/fleet commanders.

**Comment by ConorOD** [comment]
Oh snap, so these skills aren't that relevant to fleets anymore?

**Comment by Blacksmoke16** [comment]
> Oh snap, so these skills aren't that relevant to fleets anymore?

Correct, they only affect the command burst area of effect.  So don't really think this is needed.

**Comment by ConorOD** [comment]
Fair enough my bad!
