### ISSUE TITLE
Abandoned Structure Notifications

### ISSUE THREAD

**Issue by 0d17837d-20a5-4b3d-a00c-2823a412b0ee** [esi/esi-issues#1209]
# Feature Request

With the recent introduction of the _Forsaken Fortress_ expansion a new notification has been added to the game to notify players and corporations that their assets are about to be dropped into space.

ESI is currently not tracking this notification.

**Comment by Dusty-Meg** [comment]
The endpoint seems to have been updated with the below notification type.
StructureImpendingAbandonmentAssetsAtRisk

**Comment by Blacksmoke16** [comment]
:+1: That would probably satisfy this issue.
