### ISSUE TITLE
`/universe/stations/{station_id}/` 500 on invalid ID

### ISSUE THREAD

**Issue by Blacksmoke16** [esi/esi-issues#1215]
# Bug

`ESI`'s station endpoint will `500` if given a legacy station/outpost ID that existed before they were converted to structures.  It also seems to happen on any non valid number, like `10`, or `15000`, etc.

## Request

`GET /latest/universe/stations/60014917/`

### Status Code

`500`

### Headers

```
date: Mon, 06 Jul 2020 23:59:02 GMT
content-type: application/json; charset=UTF-8
content-length: 49
access-control-allow-credentials: true
access-control-allow-headers: Content-Type,Authorization,If-None-Match,X-User-Agent
access-control-allow-methods: GET,HEAD,OPTIONS
access-control-allow-origin: *
access-control-expose-headers: Content-Type,Warning,ETag,X-Pages,X-ESI-Error-Limit-Remain,X-ESI-Error-Limit-Reset
access-control-max-age: 600
allow: GET,HEAD,OPTIONS
etag: W/"fd372a2d65365cccdb7673c1f67a8f4c28e425f096763d3fcb4dd04f"
strict-transport-security: max-age=31536000
x-esi-error-limit-remain: 99
x-esi-error-limit-reset: 58
x-esi-request-id: b20e1966-1083-490a-8861-1048b9fb4053
```

### Body

```json
{
  "error": "Unhandled internal error encountered!"
}
```

## Expected

`404`

```json
{
  "error": "Station not found"
}
```

# Checklist

Check all boxes that apply to this issue:

- [x] Bug description is provided
- [x] Request path is provided
- [x] Response status code is provided
- [x] Response headers are provided
- [x] Response body is provided
- [x] Expected response is provided

**Comment by Xamber** [comment]
Internal Issue Created: TTC-3733

**Comment by mateuszkrasucki** [comment]
@Blacksmoke16 Is it still happening for you? I'm failing to reproduce.

**Comment by Blacksmoke16** [comment]
@mateuszkrasucki Nope.  Can confirm I correctly get a `404` now.  Closing.
