### ISSUE TITLE
/latest/corporations/{corporation_id}/customs_offices/ - 504 Gateway Timeout

### ISSUE THREAD

**Issue by Citricioni** [esi/esi-issues#1217]
# Bug

When requesting the Custom Offices on a corporation with many Custom Offices I always get a 504 Gateway Timeout.
On a corporation with only 1 POCO its always working fine.
Personally trying for 48 hours now, according to tweetfleet Slack other people have this issue already for several weeks.

## Request

`GET /latest/corporations/{corporation_id}/customs_offices/?datasource=tranquility&page=1`

### Status Code

`504`

### Headers

```
Date: Wed, 08 Jul 2020 17:11:30 GMT
Expires:
Last-Modified:
X-ESI-Request-ID: 1a71be3b-52cf-48f7-be81-56aed86907dc
ETag:
```

### Body

```json
{
    "error": "Timeout contacting tranquility",
    "timeout": 10
}
```

## Expected

`200`
```json
[
    {
        "alliance_tax_rate": 0.0,
        "allow_access_with_standings": true,
        "allow_alliance_access": true,
        "bad_standing_tax_rate": 0.0010000000474974513,
        "excellent_standing_tax_rate": 0.0010000000474974513,
        "good_standing_tax_rate": 0.0010000000474974513,
        "neutral_standing_tax_rate": 0.0010000000474974513,
        "office_id": ...,
        "reinforce_exit_end": 22,
        "reinforce_exit_start": 20,
        "standing_level": "terrible",
        "system_id": ...,
        "terrible_standing_tax_rate": 0.0010000000474974513
    },
{...},
....
]
```

# Checklist

Check all boxes that apply to this issue:

- [X] Bug description is provided
- [X] Request path is provided
- [X] Response status code is provided
- [X] Response headers are provided
- [X] Response body is provided
- [X] Expected response is provided

**Comment by jamesrobb** [comment]
Internal issue created: TTC-3757

**Comment by gitAskur** [comment]
This is being deployed.

**Comment by gitAskur** [comment]
Errors are gone from monolith side and esi side custom office metrics have improved. Closing.

**Comment by Citricioni** [comment]
It works now, thanks so far.

But with X-Pages > 1
page 1 and page 2 consist of the same custom offices

**page 1:**
'Date' => 'Thu, 05 Nov 2020 13:15:08 GMT'
'X-Esi-Request-Id' => '620f437e-20d7-4024-aad0-90d4e9cd0085'

'Expires' => 'Thu, 05 Nov 2020 13:23:10 GMT'
'Last-Modified' => 'Thu, 05 Nov 2020 13:13:10 GMT'
'Etag' => '"10de65b09cfd417a883f82eff9bd2e4233e60ded75cb7c2522479765"'

**page 2**
'Date' => 'Thu, 05 Nov 2020 13:15:08 GMT'
'X-Esi-Request-Id' => '53cfe75c-ee2c-42b6-a364-58574db561d3'

'Expires' => 'Thu, 05 Nov 2020 13:23:10 GMT'
'Last-Modified' => 'Thu, 05 Nov 2020 13:13:10 GMT'
'Etag' => '"10de65b09cfd417a883f82eff9bd2e4233e60ded75cb7c2522479765"'
