### ISSUE TITLE
`/dev/corporations/{corporation_id}/structures/` returns 500

### ISSUE THREAD

**Issue by Lucius-Q-User** [esi/esi-issues#1222]
# Bug
The structures endpoint consistently returns a 500 ISE.

## Request

`GET /dev/corporations/667531913/structures/ HTTP/1.1`

### Status Code

`HTTP/1.1 500 Internal Server Error`

### Headers

```
Date: Thu, 16 Jul 2020 14:14:49 GMT
Content-Type: application/json; charset=UTF-8
Content-Length: 49
Connection: keep-alive
access-control-allow-credentials: true
access-control-allow-headers: Content-Type,Authorization,If-None-Match,X-User-Agent
access-control-allow-methods: GET,HEAD,OPTIONS
access-control-allow-origin: *
access-control-expose-headers: Content-Type,Warning,ETag,X-Pages,X-ESI-Error-Limit-Remain,X-ESI-Error-Limit-Reset
access-control-max-age: 600
allow: GET,HEAD,OPTIONS
content-language: en-us
strict-transport-security: max-age=31536000
vary: Accept-Language
x-esi-error-limit-remain: 98
x-esi-error-limit-reset: 11
x-esi-request-id: 67a018de-5c8c-406b-be0b-b57af2e8d121
```

### Body

Please provide the response body, feel free to scrub any opsec details you wish. E.g.:

```json
{"error":"Unhandled internal error encountered!"}
```

## Expected

`200`

A list of my cits.

# Checklist

Check all boxes that apply to this issue:

- [x] Bug description is provided
- [x] Request path is provided
- [x] Response status code is provided
- [x] Response headers are provided
- [x] Response body is provided
- [x] Expected response is provided

**Comment by Blacksmoke16** [comment]
That's not a `structure_id`, you're trying to resolve a station via the structures endpoint.  See https://github.com/esi/esi-issues/issues/1215.

**Comment by Lucius-Q-User** [comment]
Correct, it is not a structure id, it is a corp id, i am trying to get a list of all cits in my corp. Please reopen.

**Comment by guiguilechat** [comment]
rename as "corporations/cid/structures/" maybe ?
Cause here is you just say structures we can assume it's the https://esi.evetech.net/ui/#/Universe/get_universe_structures endpoint 'or the one with id) that's got an issue.

**Comment by Blacksmoke16** [comment]
@Lucius-Q-User What happens if you dong use `dev` and switch that to `v3`?  I.e. `https://esi.evetech.new/v3/corporations/667531913/structures/`.

**Comment by Lucius-Q-User** [comment]
Works with v3

**Comment by Blacksmoke16** [comment]
@Lucius-Q-User Cool.  You would be better off using the latest stable version, especially at this point where I don't think any new dev is happening so no need to use `dev`.

However, I updated the title to make it clearer that this is specific to the dev version.  I'll leave this open for tracking, but it's not really high priority IMO.

**Comment by guiguilechat** [comment]
well if no dev is working on them I see no reason for the dev version to be broken.

**Comment by Blacksmoke16** [comment]
@guiguilechat Right, hence why I'm leaving this open.

**Comment by Blacksmoke16** [comment]
Actually there is a difference between the two versions https://esi.evetech.net/diff/v3/dev/#GET-/corporations/{corporation_id}/structures/.

I'd imagine it has something to do with that.

**Comment by jamesrobb** [comment]
Internal issue created: TTC-3756

**Comment by mateuszkrasucki** [comment]
Fixed for quite a time already.
