### ISSUE TITLE
oauth "context deadline exceeded" gives a 403

### ISSUE THREAD

**Issue by chrRtg** [esi/esi-issues#1226]
# Bug

Sometimes requests toward https://login.eveonline.com/oauth/verify gives me the following error:
`context deadline exceeded (Client.Timeout exceeded while awaiting headers)` with an error code of 403

403 is a persistent error and not suitable in this case. At least the application build by me deactivate clients who got an error in the range of 400 to 406 for their requests toward EVE API to avoid spamming the API with requests she has to answer with an error.

# Expectation

A proper error code would be "408 | Request Timeout".

**Comment by jamesrobb** [comment]
I suggest moving over to v2 OAuth endpoints we have setup. We don't have an exact date yet, but we plan on deprecating the old endpoints in the near future. An official statement will be made available when more information about the deprecation date becomes available.

You can find documentation about the new endpoints here: https://docs.esi.evetech.net/docs/sso/sso_authorization_flow.html

As a note these new endpoints give out JWT tokens, which will make calls to oauth/verify redundant.

I'm going to close this ticket for now. Please follow up again if you experience the same behavior on the new endpoints.
