### ISSUE TITLE
ESI-Universe - Factions list returns different language than default spec.

### ISSUE THREAD

**Issue by ISDThalackDalhar** [esi/esi-issues#1230]
# Bug
When requesting https://esi.evetech.net/latest/universe/factions/?datasource=tranquility  (note, no &language), I currently receive the Japanese localization for each faction, even though the spec states:

Available values : de, en-us, fr, ja, ru, zh, ko
Default value : en-us

Actually specifying a value makes it show the proper localization.

## Request

Be sure to include the HTTP method, path (including version), and any relevant parameters. Please do not include auth tokens. E.g.:

`GET /universe/factions/?datasource=tranquility`

vs

`GET /universe/factions/?datasource=tranquility&language=en-us`

## Response

See below

### Status Code

`200`

### Headers

Include relevant headers received. Timestamps and request ID is nice, you may not have all these values, fill out what you received (don't worry about headers not listed here, unless pertinent to your issue). E.g.:

```
cache-control: public
content-encoding: gzip
content-language: ja
content-type: application/json; charset=UTF-8
date: Wed, 19 Aug 2020 12:32:58 GMT
etag: "b5edd25fffabe4921f60fee3243013298b371f1d083e315be15c3f33"
expires: Thu, 20 Aug 2020 11:05:00 GMT
last-modified: Wed, 19 Aug 2020 11:02:03 GMT
status: 200
strict-transport-security: max-age=31536000
vary: Accept-Language
x-esi-error-limit-remain: 100
x-esi-error-limit-reset: 2
x-esi-request-id: 4b6c3dfb-4a45-4948-a35d-286c3f1104b4
```

### Body

Please provide the response body, feel free to scrub any opsec details you wish. E.g.:

```json
[{"corporation_id":1000051,"description":"\u30df\u30f3\u30de\u30bf\u30fc\u5171\u548c\u56fd\u306f\u30011\u4e16\u7d0 ...."}]
```
Scrubbed rest for brevity

## Expected

```json
[{"corporation_id":1000051,"description":"The Minmatar Republic was formed over a century ago when the Minmatar threw out ..."}]
```
Scrubbed rest for brevity

# Checklist

Check all boxes that apply to this issue:

- [x] Bug description is provided
- [x] Request path is provided
- [x] Response status code is provided
- [x] Response headers are provided
- [x] Response body is provided
- [x] Expected response is provided

**Comment by ISDThalackDalhar** [comment]
Checking a bit deeper, this also affects other /universe/ calls:

- `GET /universe/constellations/{constellation_id}`
- `GET /universe/regions/{region_id}`
- `GET /universe/systems/{system_id}/`
- `GET /universe/types/{type_id}/`

**Comment by Blacksmoke16** [comment]
Are you sure you're not mistakenly including the header?  Opening that link in chrome I get: `[{"corporation_id":1000051,"description":"The Minmatar Republic was formed over a century ago when the Minmatar threw`, which seems fine?

**Comment by ISDThalackDalhar** [comment]
My browser sends the following language headers:
`accept-language: en-US,en;q=0.9,en-GB;q=0.8,nl;q=0.7`

I don't see any mention of `ja` in there, but further more, en-US is listed as the first.

I think what's tripping up ESI is that browsers send 'en-US'. If I manually set it to 'en-us' everything goes fine. As mentioned by Mozilla ( https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Language ), browsers stick to RFC5646, in which the subtag is (often) capitalized. ESI expects all in lower-case....

Example:

```
curl -s -o /dev/null -v https://esi.evetech.net/latest/universe/factions/ 2>&1 | grep "Language"
< Content-Language: en-us
< Vary: Accept-Encoding,Accept-Language
```

As expected, with no headers, it gives back en-us

```
curl -H "Accept-Language: en-US,de" -s -o /dev/null -v https://esi.evetech.net/latest/universe/factions/ 2>&1 | grep "Language"
> Accept-Language: en-US,de
< Content-Language: de
< Vary: Accept-Encoding,Accept-Language
```
Here we see something off, we say we accept en-US first, but we get de

```
curl -H "Accept-Language: en-us,de" -s -o /dev/null -v https://esi.evetech.net/latest/universe/factions/ 2>&1 | grep "Language"
> Accept-Language: en-us,de
< Content-Language: en-us
< Vary: Accept-Encoding,Accept-Language
```

Sending it as lower-case (and not as RFC5646) does as expected.
Oddly enough I am unable to reproduce the Japanese output with any combination of Accept-Language (except explicitly asking for 'ja').

**Comment by Ionaru** [comment]
Related to (duplicate of?) https://github.com/esi/esi-issues/issues/1196

**Comment by ISDThalackDalhar** [comment]
I would agree, I'll close this issue seeing #1196 does a better job at explaining it.
