### ISSUE TITLE
Requests to /universe/schematics/{schematic_id}/ fail

### ISSUE THREAD

**Issue by Ionaru** [esi/esi-issues#1232]
# Bug

Any request to `/universe/schematics/{schematic_id}/` always fails.

## Request

`GET https://esi.evetech.net/latest/universe/schematics/65`
`GET https://esi.evetech.net/v1/universe/schematics/133`

### Status Code

`504`

### Headers
```
content-length: 55
date: Tue, 25 Aug 2020 23:04:11 GMT
status: 504
x-esi-request-id: 16c77174-424a-42fa-87d6-a78b97e870e1
```

### Body
```json
{"error":"Timeout contacting tranquility","timeout":10}
```

## Expected

See https://esi.evetech.net/ui/#/Planetary%20Interaction/get_universe_schematics_schematic_id

# Checklist

Check all boxes that apply to this issue:

- [x] Bug description is provided
- [x] Request path is provided
- [x] Response status code is provided
- [x] Response headers are provided
- [x] Response body is provided
- [x] Expected response is provided

**Comment by gitAskur** [comment]
Fix requested for deployment in the next available slot - that's expected to be on Thursday during downtime.
