### ISSUE TITLE
Add field to track Quantum Core installation in pre-existing structures in GET /corporations/{corporation_id}/structures/

### ISSUE THREAD

**Issue by cdanis** [esi/esi-issues#1238]
# Feature Request

Per [September's Quantum Cores post](https://www.eveonline.com/article/qfzmf8/quantum-cores), on 12 January 2021, all existing Upwell structures will need to have a Quantum Core installed in them to remain online.

Since even small to medium-sized alliances often have many structures, this can easily create a state-tracking nightmare.  It would be really nice if ESI told you which structures were already Quantum-ified and which weren't.

## Use case

Alliance leadership and logisticians for alliances that own several structures or more.

## Authentication

An existing scope.

## Example return

I propose adding a simple Boolean field to the `get_corporations_corporation_id_structures_200_ok` array item response for `GET /corporations/{corporation_id}/structures/`: let's call it `quantum_core_installed` for now.

It could be removed in an update after the deadline in January, or it could remain and just always be tautologically true.

# Checklist

Check all boxes that apply to this issue:

- [x] Feature request description is provided
- [x] Use case exists
- [ ] Feature requires a new route
- [x] Feature adds data to existing route
- [ ] Feature requires new auth scope
- [x] Feature can reuse existing scope
- [ ] Feature does not require auth
- [ ] Meta feature, applies to all routes

**Comment by CarbonAlabel** [comment]
Once https://github.com/esi/esi-issues/issues/1240 is fixed, this information will be readily available through the corporation assets endpoint.
