### ISSUE TITLE
Quantum cores appear to break corp assets endpoint

### ISSUE THREAD

**Issue by eve-n0rman** [esi/esi-issues#1240]
# Bug

After installing a quantum core in a corp structure, the corp assets endpoint returns a 500 error

## Request

`GET https://esi.evetech.net/latest/corporations/nnnnnnn/assets/?datasource=tranquility&page=1`

### Status Code

`500`

### Headers

```
 access-control-allow-credentials: true 
 access-control-allow-headers: Content-Type,Authorization,If-None-Match,X-User-Agent 
 access-control-allow-methods: GET,HEAD,OPTIONS 
 access-control-allow-origin: * 
 access-control-expose-headers: Content-Type,Warning,ETag,X-Pages,X-ESI-Error-Limit-Remain,X-ESI-Error-Limit-Reset 
 access-control-max-age: 600 
 allow: GET,HEAD,OPTIONS 
 content-encoding: gzip 
 content-length: 360 
 content-type: application/json; charset=UTF-8 
 date: Fri, 11 Sep 2020 23:37:52 GMT 
 status: 500 
 strict-transport-security: max-age=31536000 
 vary: Accept-Encoding 
 x-esi-error-limit-remain: 98 
 x-esi-error-limit-reset: 8 
 x-esi-request-id: 55364d46-74a0-430f-a755-f6a619c72379 
```

### Body

```
{
  "error": "Invalid 200 response: 'location_type' is required, 'location_flag' is required",
  "response": [
    [...normal assets returned here as expected...]
    {
      "is_blueprint_copy": false,
      "type_id": 56203,
      "is_singleton": false,
      "item_id": nnnnnnn,
      "location_id": nnnnnnnn,
      "quantity": 1
    }
  ]
}
```

type_id 56203 is a quantum core, and it appears to be missing location_type and location_flag data, which is causing a 500

## Expected

I'd expect a 200 response with the correct data populated for quantum cores

# Checklist

Check all boxes that apply to this issue:

- [x] Bug description is provided
- [x] Request path is provided
- [x] Response status code is provided
- [x] Response headers are provided
- [x] Response body is provided
- [x] Expected response is provided

**Comment by mateuszkrasucki** [comment]
Internal Issue Created: TTC-3670

**Comment by eve-n0rman** [comment]
Any eta on a fix?  This is going to be a game-breaking problem for any large alliance in 2 weeks.

**Comment by CarbonAlabel** [comment]
Fixed by https://github.com/esi/eve-glue/pull/24
