### ISSUE TITLE
/industry/facilities/  returning 500

### ISSUE THREAD

**Issue by Dusty-Meg** [esi/esi-issues#1247]
# Bug

When calling  /v1/industry/facilities/ a 500 response is always given.

"error": "Unhandled internal error encountered!"

## Request

`GET /v1/industry/facilities/?datasource=tranquility`

### Status Code

`500`

### Headers

Include relevant headers received. Timestamps and request ID is nice, you may not have all these values, fill out what you received (don't worry about headers not listed here, unless pertinent to your issue). E.g.:

```
Date: Thu, 15 Oct 2020 09:17:50 GMT
X-ESI-Request-ID: cf8524ef-3715-4a77-9590-354a6e01201f 
```

### Body

Please provide the response body, feel free to scrub any opsec details you wish. E.g.:

```json
{
  "error": "Unhandled internal error encountered!"
}
```

## Expected

Please provide either the expected return code, correct response body, header value, or some combination thereof. E.g.:

`200`

# Checklist

Check all boxes that apply to this issue:

- [x] Bug description is provided
- [x] Request path is provided
- [x] Response status code is provided
- [x] Response headers are provided
- [x] Response body is provided
- [x] Expected response is provided

**Comment by jamesrobb** [comment]
Internal issue created: TTC-3751

**Comment by mateuszkrasucki** [comment]
Fixed.
