### ISSUE TITLE
Colony layout service does not return stored items quantities 

### ISSUE THREAD

**Issue by jafuentest** [esi/esi-issues#1248]
# Bug

According to the swagger docs and issue #161 this service should return items in storage facilities and the stored quantity.

However, the content array in responses is always empty, Last time I checked my planets in client and made some edits there was definitely stuff there. Also, similar apps that show PI stuff display storage and launchpads empty, ex: EVE Mon, and Neocom on iOS. All my planets are in null-sec (in case that matters somehow)

Example response:

## Request

`GET /dev/characters/<character>/planets/<planet_id>/?datasource=tranquility`

Also tried with `/latest/`

### Status Code

`200`

### Headers

```
access-control-allow-credentials: true
access-control-allow-headers: Content-Type,Authorization,If-None-Match,X-User-Agent
access-control-allow-methods: GET,HEAD,OPTIONS
access-control-allow-origin: *
access-control-expose-headers: Content-Type,Warning,ETag,X-Pages,X-ESI-Error-Limit-Remain,X-ESI-Error-Limit-Reset
access-control-max-age: 600
allow: GET,HEAD,OPTIONS
content-encoding: gzip
content-length: 1209
content-type: application/json; charset=UTF-8
date: Thu, 15 Oct 2020 22:16:01 GMT
strict-transport-security: max-age=31536000
vary: Accept-Encoding
x-esi-error-limit-remain: 100
x-esi-error-limit-reset: 59
x-esi-request-id: 6deb3442-cf8b-47be-b718-68193f652b52
x-firefox-spdy: h2
```

### Body

Displaying only the relevant part
```json
{
  "pins": [
    {
      "contents": [],
      "last_cycle_start": "2020-10-15T17:30:04Z",
      "latitude": 2.5214450359344482,
      "longitude": 1.330422282218933,
      "pin_id": 1034406730043,
      "type_id": 2561
    },
    {
      "contents": [],
      "last_cycle_start": "2020-10-15T06:14:30Z",
      "latitude": 2.490783214569092,
      "longitude": 1.3525160551071167,
      "pin_id": 1034406730049,
      "type_id": 2557
    },
    {
      "contents": [],
      "last_cycle_start": "2020-10-12T05:55:40Z",
      "latitude": 2.4714725017547607,
      "longitude": 1.4031360149383545,
      "pin_id": 1034405109199,
      "type_id": 2550
    }
  ]
}
```

## Expected

Contents array should be populated with items stored in the facility
```json
{
  "contents": [
    {
      "amount": 123,
      "type_id": 456
    },
    {
      "amount": 789,
      "type_id": 012
    }
  ],
  "last_cycle_start": "2020-10-12T05:55:40Z",
  "latitude": 2.4714725017547607,
  "longitude": 1.4031360149383545,
  "pin_id": 1034405109199,
  "type_id": 2550
}
```

# Checklist

Check all boxes that apply to this issue:

- [x] Bug description is provided
- [x] Request path is provided
- [x] Response status code is provided
- [x] Response headers are provided
- [x] Response body is provided
- [x] Expected response is provided

**Comment by mateuszkrasucki** [comment]
Thanks for the report. It's indeed a bug, hopefully we will find bandwidth to fix it soon.

**Comment by gitAskur** [comment]
Fixed Internally, scheduled to release on the 10th of November 2020.

**Comment by Head** [comment]
Seem to be broken again? Same issue in https://github.com/esi/esi-issues/issues/654
