### ISSUE TITLE
ESI routes still uses triglavian systems

### ISSUE THREAD

**Issue by jeronica** [esi/esi-issues#1249]
# Bug

When requesting shortest route, ESI still uses triglavian systems (Niarja in my example).

## Request
Ex: Route from Jita to Ashab

https://esi.evetech.net/latest/route/30000142/30003491/?datasource=tranquility&flag=shortest

## Response

[
30000142,
30000144,
30000139,
30002791,
30002788,
30002789,
30003504,
30003503,
30003491
]

30003504 = Niarja, which is not accessible by gates

### Status Code

200

## Expected

Expect the route to return what's returned in game, which is 23 jumps using the shortest option.

# Checklist

Check all boxes that apply to this issue:

- [x] Bug description is provided
- [x] Request path is provided
- [x] Response status code is provided
- [n/a] Response headers are provided
- [x] Response body is provided
- [x] Expected response is provided

**Comment by CarbonAlabel** [comment]
See https://github.com/esi/esi-routes/issues/7
