### ISSUE TITLE
/search/ does not return results for Triglavian space

### ISSUE THREAD

**Issue by lukasni** [esi/esi-issues#1250]
# Bug

As per the title. Both public and authenticated search endpoints do not return the expected results when searching for the new Triglavian Region `Pochven`, nor its three constellations. The error occurs both with strict and non-strict search.

These are the affected regions / constellations:

```
10000070: Pochven
20000787: Krai Perun
20000788: Krai Svarog
20000789: Krai Veles
```

## Request

`GET /v2/search/?categories=constellation&search=Krai%20Svarog&strict=true`

### Status Code

`200`

### Headers

```
date: Fri, 23 Oct 2020 22:43:36 GMT
content-type: application/json; charset=UTF-8
content-length: 2
etag: "9661d47169c2d8014928d7c850283d9e74790f614155a853595b36fa"
expires: Fri, 23 Oct 2020 23:42:01 GMT
last-modified: Fri, 23 Oct 2020 22:42:01 GMT
x-esi-request-id: d5de3892-e23e-411e-ab97-dbd75996a92c
```

### Body

```json
{}
```

## Expected

`200`

```json
{
  "constellation": [20000788]
}
```

# Checklist

Check all boxes that apply to this issue:

- [x] Bug description is provided
- [x] Request path is provided
- [x] Response status code is provided
- [x] Response headers are provided
- [x] Response body is provided
- [x] Expected response is provided

**Comment by lukasni** [comment]
This issue also affects the `POST /universe/ids/` endpoint.

**Comment by mateuszkrasucki** [comment]
It's a known issue that affects also the in-game search, it's being worked on.

**Comment by Xamber** [comment]
Fixed
