### ISSUE TITLE
/universe/ids/ doesn't return id for valid character name

### ISSUE THREAD

**Issue by irwiss** [esi/esi-issues#1253]
# Bug

/universe/ids/ doesn't return id for valid character name

Character isn't a freshly created one either
There's a few characters with similar responses in logs

Several others i tried are:
```
x-esi-request-id: b2b83212-fbed-4f32-b034-b7b545b9cb3b
x-esi-request-id: fe5ee7ab-9fe8-4ce7-9d26-d53a5de592d9
x-esi-request-id: 469619e8-ddd7-480e-8574-72a77cf653b5
```

All names with corresponding id can be found via zkillboard

## Request

`curl -X POST "https://esi.evetech.net/latest/universe/ids/?datasource=tranquility&language=en-us" -H "accept: application/json" -H "Accept-Language: en-us" -H "Content-Type: application/json" -d "[ \"Zyklon SA\"]"`

### Status Code

`200`

### Headers
```
 access-control-allow-credentials: true 
 access-control-allow-headers: Content-Type,Authorization,If-None-Match,X-User-Agent 
 access-control-allow-methods: POST,OPTIONS 
 access-control-allow-origin: * 
 access-control-expose-headers: Content-Type,Warning,ETag,X-Pages,X-ESI-Error-Limit-Remain,X-ESI-Error-Limit-Reset 
 access-control-max-age: 600 
 allow: OPTIONS,POST 
 content-language: en-us 
 content-length: 2 
 content-type: application/json; charset=UTF-8 
 date: Mon, 16 Nov 2020 18:20:53 GMT 
 status: 200 
 strict-transport-security: max-age=31536000 
 vary: Accept-Language 
 x-esi-error-limit-remain: 99 
 x-esi-error-limit-reset: 7 
 x-esi-request-id: 538b47cc-e4d5-4d9d-a8f9-edb5b04feddb 
```
### Body

```json
{}
```

## Expected

`200`

```json
{
  "characters": [
    {
      "id": 96785208,
      "name": "Zyklon SA"
    }
  ]
}
```

# Checklist

Check all boxes that apply to this issue:

- [x] Bug description is provided
- [x] Request path is provided
- [x] Response status code is provided
- [x] Response headers are provided
- [x] Response body is provided
- [x] Expected response is provided

**Comment by lukasni** [comment]
Confirmed. Somewhat surprisingly, searching for the same character via the `/search/` endpoint seems to go through fine.

```bash
curl -X GET "https://esi.evetech.net/latest/search/?categories=character&datasource=tranquility&language=en-us&search=Zyklon%20SA&strict=true" -H "accept: application/json" -H "Accept-Language: en-us"
```

This may be related to a search issue currently happening in game where some characters can't be searched for.

**Comment by Eingang** [comment]
Interestingly, it *does* work for the sample provided on the Swagger page: CCP Zoetrope. It also worked for `CCP Dopamine`. It did not work for any other non-CCP character name I happened to try, though.

**Comment by jamesrobb** [comment]
I've deployed a fix just now that should fix this. I've tested against that character name and a number of others. Please do feel free to open this up again if the problem persists.
