### ISSUE TITLE
Some important endpoints are not working!

### ISSUE THREAD

**Issue by 792146** [esi/esi-issues#1261]
As of 03/12/2020 at least the following endpoints returns HTTP ERROR 404 'not found' :

GET characters/{character_id}/orders/
GET characters/{character_id}/orders/history/

GET markets/{region_id}/history/
GET markets/{region_id}/orders/
GET markets/{region_id}/types/

GET characters/{character_id}/wallet/
GET characters/{character_id}/wallet/journal/
GET characters/{character_id}/wallet/transactions/

**Comment by jowrjowr** [comment]
known issue.
