### ISSUE TITLE
Add endpoint to remove (kick) corporation members

### ISSUE THREAD

**Issue by Ebag333** [esi/esi-issues#1269]
# Feature Request
Add an endpoint to allow automation of removing (yeeting) members.  Right now this is a manual process and for large corps (10k+) this process can take literally days as it has to be manually done in game,.

## Use case
Either used to indirectly give yeet access without the player in question having the access in game, or (more likely) used to mass yeet players (IE: "yeet all inactives who haven't logged in for 1 year").

## Authentication
New scope, auth required.

## Example return
```json
[
  {
    "Processed": True,
    "members_kicked": 95538921
  }
]
```

# Checklist

Check all boxes that apply to this issue:

- [X] Feature request description is provided
- [X] Use case exists
- [X] Feature requires a new route
- [ ] Feature adds data to existing route
- [X] Feature requires new auth scope
- [ ] Feature can reuse existing scope
- [ ] Feature does not require auth
- [ ] Meta feature, applies to all routes

**Comment by ddouglas** [comment]
Gonna have to heavily disagree with every ounce of this request. I know we tell Eve Online Players to be careful with their tokens, but let's  be honest, they aren't. If somebody were to be like just about every other person in the world and not read the scopes screen before clicking authorize, they are literally handing the keys to their kingdom over to somebody they don't necessarily know, nor should really trust. This endpoint would allow some mischievous developer the ability to destroy a corporation in a matter of seconds by kicking every member of their corp creating a headache in game for somebody and that is just is not fair, especially considering that bulk kick members is not a function provided by the current UI if I remember correctly.

**Comment by cvweiss** [comment]
Removing members from a corp should continue to be an in-game only action.

And that was my thought before I even read @ddouglas 's reply. He has a very valid point.

**Comment by ddouglas** [comment]
Closing because this would never be approved by GD nor any member of ECM nor any member of the Dev Team.
