### ISSUE TITLE
/markets/prices/{type_id}/ endpoint

### ISSUE THREAD

**Issue by Ligraph** [esi/esi-issues#127]
An endpoint to get the price data for a single item, so I don't have to cache or sort through the entire list if I only need one price.  Might be better/easier to build this into /universe/types/{type_id}/ ?

**Comment by fuzzysteve** [comment]
Just checking, you know this is for the industry data, right? (you probably do)

**Comment by Ligraph** [comment]
You mean the base prices (like for install costs and taxes)?  That's what I thought it was, wasn't 100% sure.

**Comment by lukasni** [comment]
Getting the entire list is already a single request, filtering the list locally is trivial. This would add cache bloat without providing any significant value, closing this for now.
