### ISSUE TITLE
Get two factor (2FA) status for an individual character and members of a corporation

### ISSUE THREAD

**Issue by Shegox** [esi/esi-issues#1271]
# Feature Request

We have the use case that we would like to enforce 2FA for all members of our corporation. To ensure that we currently have to ask everyone individually if they have that enabled. 

I would like to propose to add such an endpoint either 
- to the corporation member list and/or ([`/corporations/{corporation_id}/membertracking/`](https://esi.evetech.net/ui/?version=latest#/Corporation/get_corporations_corporation_id_membertracking))
- the individual character. Probably a new endpoint required `/characters/{character_id}/2fa_enabled`

E.g. GitHub allows to see the 2FA status by organization (==corp) and for the individual user (==character). 

## Use case
Allow corporations and organizations to easily enforce and monitor security settings and improve overall account security.
From a corporation perspective we would like to ensure that everyone who has access to high value (strategic) assets like keepstars, BPOs and stuff have their accounts properly secured.

## Authentication

Existing scope:
corporation: `esi-corporations.track_members.v1`
individual:  probably new scope required: `esi-characters.read_2fa_status.v1`

## Example return

For the corporation member tracking endpoint it could be extended with the boolean attribute `2fa_enabled`.

```json
[
  {
    "character_id": 90012476,
    "location_id": 1034877491366,
    "logoff_date": "2021-02-11T16:31:06Z",
    "logon_date": "2021-02-11T16:22:19Z",
    "ship_type_id": 11567,
    "start_date": "2017-02-25T12:15:00Z",
    "2fa_enabled": true
  },
  {
    "character_id": 90157186,
    "location_id": 30004636,
    "logoff_date": "2020-12-22T22:22:50Z",
    "logon_date": "2020-12-22T22:21:55Z",
    "ship_type_id": 17738,
    "start_date": "2011-11-19T23:00:00Z",
    "2fa_enabled": false
  },
  ....
  ]
```

# Checklist

Check all boxes that apply to this issue:

- [x] Feature request description is provided
- [x] Use case exists
- [x] (maybe) Feature requires a new route
- [x] Feature adds data to existing route
- [x] (maybe) Feature requires new auth scope
- [x] Feature can reuse existing scope
- [ ] Feature does not require auth
- [ ] Meta feature, applies to all routes

**Comment by CarbonAlabel** [comment]
2FA status is account level information; as a character based API, this request is out of scope for ESI.
