### ISSUE TITLE
/characters/{character_id}/blueprints/

### ISSUE THREAD

**Issue by biow0lf** [esi/esi-issues#1274]
# Bug

`/characters/{character_id}/blueprints/` `v3` and `dev` version of end point response with wrong json structure. `v2` works as expected.

## Request

`curl -X GET "https://esi.evetech.net/v3/characters/1337512245/blueprints/?datasource=tranquility&page=1" -H "accept: application/json" -H "authorization: Bearer token" -H "Cache-Control: no-cache"`

### Status Code

`200`

### Headers

Include relevant headers received. Timestamps and request ID is nice, you may not have all these values, fill out what you received (don't worry about headers not listed here, unless pertinent to your issue). E.g.:

```
access-control-allow-credentials: true 
access-control-allow-headers: Content-Type,Authorization,If-None-Match,X-User-Agent 
access-control-allow-methods: GET,HEAD,OPTIONS 
access-control-allow-origin: * 
access-control-expose-headers: Content-Type,Warning,ETag,X-Pages,X-ESI-Error-Limit-Remain,X-ESI-Error-Limit-Reset 
access-control-max-age: 600 
allow: GET,HEAD,OPTIONS 
content-encoding: gzip 
content-length: 938 
content-type: application/json; charset=UTF-8 
date: Sun, 28 Feb 2021 14:56:35 GMT 
strict-transport-security: max-age=31536000 
vary: Accept-Encoding 
x-esi-error-limit-remain: 98 
x-esi-error-limit-reset: 25 
 x-esi-request-id: 7c41f1d0-556d-45f8-9e9a-a3a7d51432e6
```

### Body

Please provide the response body, feel free to scrub any opsec details you wish. E.g.:

```json
{
    "error": "Invalid 200 response: -1 does not meet minimum of 0, -1 does not meet minimum of 0",
    "response": [
    {
      "location_flag": "AssetSafety",
      "location_id": 60013867,
      "item_id": 1003026148920,
      "type_id": 1152,
      "quantity": -1,
      "time_efficiency": 20,
      "material_efficiency": 10,
      "runs": -1
    }, ...],
    "sentry_id": "2011cc1ffe484e34a9ba4f4d6a27d5d9"
}
```

## Expected

Please provide either the expected return code, correct response body, header value, or some combination thereof. E.g.:

`200` with right json structure:

```
{
   [
    {
      "location_flag": "AssetSafety",
      "location_id": 60013867,
      "item_id": 1003026148920,
      "type_id": 1152,
      "quantity": -1,
      "time_efficiency": 20,
      "material_efficiency": 10,
      "runs": -1
    }]
}
```

# Checklist

Check all boxes that apply to this issue:

- [x] Bug description is provided
- [x] Request path is provided
- [x] Response status code is provided
- [x] Response headers are provided
- [x] Response body is provided
- [x] Expected response is provided

**Comment by mateuszkrasucki** [comment]
EO-14111

**Comment by mateuszkrasucki** [comment]
solved
