### ISSUE TITLE
Route endpoint returns routes based on old map data

### ISSUE THREAD

**Issue by samoneilll** [esi/esi-issues#1285]
# Bug

Routes requested from ESI do not calculate routes from the new system_neighbours added from the recent TrailBlazer event.

For example, requesting a route from Jita to Amarr with the shortest flag returns a 24 jump route. Requesting the same route in the client is 12 jumps through the new Hykkota <=> Ahbazon connection.

## Request

`https://esi.evetech.net/latest/route/30000142/30002187/?connections=&datasource=tranquility&flag=shortest`

### Status Code

`200`

### Headers

```
date: Wed, 16 Jun 2021 01:11:47 GMT  
etag: "42d87f328a949841fd00d8d8fb0139bc0b69765aef2fc98f210a74be" 
expires: Wed, 16 Jun 2021 20:12:20 GMT  
last-modified: Tue, 15 Jun 2021 20:12:20 GMT  
strict-transport-security: max-age=31536000 
x-esi-error-limit-remain: 98  
x-esi-error-limit-reset: 13 
x-esi-request-id: 1caebbec-5cd1-41ab-9509-45ebc26c3305 
```

### Body

```json  
[
  30000142,
  30000144,
  30002642,
  30002643,
  30002644,
  30002691,
  30002718,
  30002719,
  30002720,
  30002050,
  30002051,
  30002060,
  30002066,
  30002099,
  30002517,
  30002537,
  30002542,
  30003068,
  30003067,
  30003065,
  30003520,
  30003521,
  30003522,
  30002187
]
```

## Expected

Expected body: 

```json
[30000142,30000138,30000132,30000134,30005196,30005192,30004083,30004081,30002197,30002193,30003491,30002187]
```

# Checklist

- [x] Bug description is provided
- [x] Request path is provided
- [x] Response status code is provided
- [x] Response headers are provided
- [x] Response body is provided
- [x] Expected response is provided

**Comment by Gh0stReaper123** [comment]
Is this still being looked at? It's quite a fundamental thing that the ESI has been providing.

**Comment by Blacksmoke16** [comment]
Essentially just waiting for someone to merge/release https://github.com/esi/esi-routes/pull/10.

**Comment by OrsikIronfist** [comment]
Any update on when this will be fixed?
