### ISSUE TITLE
'/characters/{character_id}/blueprints' X-Pages Header not returned

### ISSUE THREAD

**Issue by CockneyRhymingJedi** [esi/esi-issues#1287]
# Bug

ESI does not return the X-Pages Header when requesting Blueprints for Character

## Request

`GET /characters/{character_id}/blueprints?datasource=tranquility`

### Status Code

`200`

### Headers

Include relevant headers received. Timestamps and request ID is nice, you may not have all these values, fill out what you received (don't worry about headers not listed here, unless pertinent to your issue). E.g.:

```
 access-control-allow-credentials: true 
 access-control-allow-headers: Content-Type,Authorization,If-None-Match,X-User-Agent 
 access-control-allow-methods: GET,HEAD,OPTIONS 
 access-control-allow-origin: * 
 access-control-expose-headers: Content-Type,Warning,ETag,X-Pages,X-ESI-Error-Limit-Remain,X-ESI-Error-Limit-Reset 
 access-control-max-age: 600 
 allow: GET,HEAD,OPTIONS 
 cache-control: private 
 connection: keep-alive 
 content-encoding: gzip 
 content-type: application/json; charset=UTF-8 
 date: Thu, 01 Jul 2021 14:09:02 GMT 
 etag: "593e792dd9770bf8f7fc4a89dd89623378c0ed4ada2ed76a54269f7a" 
 expires: Thu, 01 Jul 2021 15:05:17 GMT 
 last-modified: Thu, 01 Jul 2021 14:05:17 GMT 
 strict-transport-security: max-age=31536000 
 transfer-encoding: chunked 
 vary: Accept-Encoding 
 x-esi-error-limit-remain: 100 
 x-esi-error-limit-reset: 58 
 x-esi-request-id: d3c07f4c-2582-4d0e-9816-4d5250d613df 
```

### Body

```
The first page of results returned correctly in JSON format.  NB: this is not the issue
```

### Status Code
`200`

### Body
```
The first page of results returned correctly in JSON format.  NB: this is not the issue
```

### Headers

As above, but also the following should be returned.
```
x-pages: 2
```

# Checklist

Check all boxes that apply to this issue:

- [x] Bug description is provided
- [x] Request path is provided
- [x] Response status code is provided
- [x] Response headers are provided
- [x] Response body is provided
- [x] Expected response is provided

**Comment by Blacksmoke16** [comment]
Also confirmed other paginated endpoints return `x-pages: 1` if there's only 1 page.

**Comment by mateuszkrasucki** [comment]
Fixed
