### ISSUE TITLE
/v2/characters/{character_id}/blueprints/ changes?

### ISSUE THREAD

**Issue by Ionaru** [esi/esi-issues#1291]
# Issue

The route `/v2/characters/{character_id}/blueprints/` was recently (I first noticed on Jun 23rd) deprecated and replaced with `/v3/characters/{character_id}/blueprints/`, however no mention of it is listed in the [changelog](https://github.com/esi/esi-issues/blob/master/changelog.md), there are no differences in swagger.json for that route and the [online diff viewer](https://esi.evetech.net/diff/legacy/latest/#GET-/characters/{character_id}/blueprints/) also has no changes for this route.
![image](https://user-images.githubusercontent.com/3472373/127160676-30a08287-be31-477e-b1e6-9f80dc38afa6.png)

What has changed here? Why is /v2/ deprecated in favour of /v3/ ?

Also looking at https://github.com/esi/esi-issues/issues/1274 and https://github.com/esi/esi-issues/issues/1287 maybe it's safer to stick with /v2/ for a while...

## Routes

`/v2/characters/{character_id}/blueprints/`
`/v3/characters/{character_id}/blueprints/`

## Resolution

Describe the reason for bumping the route from /v2/ to /v3/.

**Comment by GoldenGnu** [comment]
A lot of routes was updated like that (around ~2021-06-19):
```
/v2/characters/affiliation/
/v2/characters/{character_id}/agents_research/
/v2/characters/{character_id}/corporationhistory/
/v2/characters/{character_id}/fatigue/
/v2/characters/{character_id}/medals/
/v2/characters/{character_id}/notifications/contacts/
/v2/characters/{character_id}/standings/
/v2/characters/{character_id}/titles/
/v3/characters/{character_id}/blueprints/
/v3/characters/{character_id}/roles/
/v5/characters/{character_id}/cspa/
```
I asked on #esi when i happened, but no one appeared to know anything and nothing changed from the ESI users perspective, except for the versioned route name. So, nothing lost nothing won, I guess...

**Comment by mateuszkrasucki** [comment]
@Ionaru @GoldenGnu those were internal changes that are marked with higher `v-version` to prevent any problems, they were on `dev` tier for some time.

**Comment by mateuszkrasucki** [comment]
Closing as it's not an actual problem, will have a look at linked blueprints tickets.
