### ISSUE TITLE
Cannot create, edit or delete Applications on https://developers.eveonline.com/applications

### ISSUE THREAD

**Issue by dreej-net** [esi/esi-issues#1295]
Cannot create, edit or delete Applications on https://developers.eveonline.com/applications

Help ?

**Comment by guiguilechat** [comment]
expected : access to the page.
result : returns a 500 after loging in.

**Comment by Claudweb** [comment]
The behavior changed: It is possible to access the page now, but any newly created applications or changes to applications fail without notification. The main page is reloaded and the new application is still not there.

**Comment by dreej-net** [comment]
It is now working properly since extended downtime.

Not sure about the relation between all of this, but all is good. :)
