### ISSUE TITLE
C# SSO auth 401 Unauthorized

### ISSUE THREAD

**Issue by Irigana** [esi/esi-issues#1296]
# Bug 
The remote server returned an error: (401) Unauthorized'

Hello, I have some issues with the OAuth 2.0 flow of my c# app.
I'm stuck at the last step when I try to send the post request in order to get the JWT I have the following error : (401)Unauthorized.

code={Access_Token} => https://localhost/callback/?code={Access_Token}&state={Unique_state}
code_verifier={code_verifier} => I keep the code_verifier when i make my code_challenge like that : 
![image](https://user-images.githubusercontent.com/43547388/132373580-89e79026-4f6b-4d0a-8b67-9f2352e3dec6.png)

I make my request url here : 
![image](https://user-images.githubusercontent.com/43547388/132373882-d91b5417-d8ea-4c5b-b9df-79b635ccfda0.png)

And 

![image](https://user-images.githubusercontent.com/43547388/132373926-0f5873aa-0aa0-4855-a818-ff111e2d4946.png)

Do you have any idea what I'm doing wrong?

## Request

https://login.eveonline.com/v2/oauth/token/?grant_type=authorization_code&code={Access_Token}&client_id={client_id}&code_verifier={code_verifier}"

## Response

Unauthorized

### Status Code

`401`

# Checklist

Check all boxes that apply to this issue:

- Bug description is provided
-  Request path is provided
-  Response status code is provided
- [ ] Response headers are provided
- [ ] Response body is provided
- [ ] Expected response is provided

**Comment by Blacksmoke16** [comment]
This would be better suited to the forums or slack as it's most likely an issue with the code. However, if it does end up being an actual bug, it should be reported in the https://github.com/ccpgames/sso-issues repo as this isn't an ESI issue.
