### ISSUE TITLE
[error] => invalid_grant [error_description] => Grant type is not supported.

### ISSUE THREAD

**Issue by Gazza666G** [esi/esi-issues#1297]
My app has been using the esi and i have not changed any of the code however I now get this error whenever I try and use either the authorization_code or refresh_token grant types.

[error] => invalid_grant 
[error_description] => Grant type is not supported.

When I go onto the developers website and try and view my application I also get an internal service error. But i asked someone else to go onto the dev website and the applications link puts him onto the page for creating an app so looks  like its blocking me in someway.

I have reached out to support, but they only said that they dont deal with the esi, does anyone know what the issue is or direct me to someone who can help?

Thanks

**Comment by Blacksmoke16** [comment]
The dev application site is a known issue and is being actively investigated. However this would be better suited to the forums or slack. If it does end up being an actual bug, it should be reported in the https://github.com/ccpgames/sso-issues repo as this isn't an ESI issue.
