### ISSUE TITLE
Is 'Route' section gone?

### ISSUE THREAD

**Issue by HusKey-dev** [esi/esi-issues#1304]
# Bug
There is no 'Route' section at https://esi.evetech.net/ui/ anymore.

When requesting any route between systems, I recieve 404 error

## Request

`GET /latest/route/{origin}/{destination}/`

### Status Code

`404`

### Headers

```
Date: Tue, 30 Nov 2021 00:41:03 GMT
Expires:
Last-Modified:
ETag:
```

### Body

```json
{
    {"error":"Не обнаружено (ошибка 404)"}
}
```

## Expected

`200`

# Checklist

Check all boxes that apply to this issue:

- [x] Bug description is provided
- [x] Request path is provided
- [x] Response status code is provided
- [x] Response headers are provided
- [x] Response body is provided
- [x] Expected response is provided

**Comment by ddouglas** [comment]
This route was constantly being removed and added back to the schema today. Probably an issue with the node that is hosting it.

**Comment by pelgrimforever** [comment]
still doesn't work after the reboot today, and it also does not appear in https://esi.evetech.net/ui/
Hoping this is resolved soon, I'm relying on this a lot.

**Comment by karnyvekz** [comment]
Same here, same issue.

**Comment by pelgrimforever** [comment]
programmed my own version, could not wait anymore since we get info.

**Comment by Blacksmoke16** [comment]
This is resolved. It's back now.
