### ISSUE TITLE
EVE v19.11 - New Corporation Role

### ISSUE THREAD

**Issue by soratidus999** [esi/esi-issues#1306]
# Feature Request

EVE Patch 19.11 introduced a new corporation role, `Skill Plan Manager`. 

This role is not returned when applied/owned/set on a character.

This is missing from the Roles enum, which i presume is shared with all endpoints, as the following are affected
https://esi.evetech.net/ui/?version=latest#/Character/get_characters_character_id_roles
https://esi.evetech.net/ui/?version=latest#/Corporation/get_corporations_corporation_id_roles
https://esi.evetech.net/ui/?version=latest#/Corporation/get_corporations_corporation_id_roles_history

## Use case

Corporation Auditing, providing superior out of game checking of who has what roles (and usually which _people_)
Service Administration, granting access to external services, such as skill plan management based on this ingame role

These are all practices that currently occur with the roles endpoints currently, and to have a single role missing threatens the reliability and trustworthyness of all the data, requiring manual, slow, human-error filled intervention

## Authentication

No changes required, this is simply to replicate features that were created on TQ without responsiblity or care to their assocated endpoints

## Example return

Propose what an example return might look like. E.g.:

```json
{
  "roles": [
    "Accountant",
    "Skill Plan Manager" <-- this role does not appear
  ],
  "roles_at_base": [
    "Hangar_Take_6",
    "Hangar_Query_6",
    "Container_Take_6"
  ]
  ... other roles and role categories
}
```

# Checklist

Check all boxes that apply to this issue:

- [x] Feature request description is provided
- [x] Use case exists
- [ ] Feature requires a new route
- [x] Feature adds data to existing route
- [ ] Feature requires new auth scope
- [x] Feature can reuse existing scope
- [ ] Feature does not require auth
- [ ] Meta feature, applies to all routes

**Comment by LeoJian622** [comment]
收到勒。。。(-o-)／   _(_^_)_  请不要介意这封自动回复。。。。

**Comment by soratidus999** [comment]
I can be contacted for further testing on the CCP Partner Discord, or via this issue

**Comment by steven-noorbergen** [comment]
Closing this as this was fixed a while ago.

**Comment by soratidus999** [comment]
fixed in https://github.com/esi/eve-glue/pull/31
