### ISSUE TITLE
Batch REST endpoint for multiple resource calls to aggregate network roundtrips

### ISSUE THREAD

**Issue by notmorganfreewoman** [esi/esi-issues#1310]
# Feature Request

In order to reduce the number of REST calls to multiple endpoints for a client applications, and w.r.t. https://github.com/esi/esi-issues/issues/1309 it would be more efficient to POST multiple requests as one.

## Use case

Third party developers have to call many endpoints to make a useful application, reducing these N roundtrips to 1 would save a lot of bandwidth, especially if we want to achieve something like this https://github.com/esi/esi-issues/issues/1309 request.

## Authentication

Uses existing authentication

## Example return

Multi-part responses from all resources requested in the batch

# Checklist

Check all boxes that apply to this issue:

- [x] Feature request description is provided
- [x] Use case exists
- [x] Feature requires a new route
- [ ] Feature adds data to existing route
- [ ] Feature requires new auth scope
- [ ] Feature can reuse existing scope
- [ ] Feature does not require auth
- [ ] Meta feature, applies to all routes

**Comment by DianaOlympos** [comment]
You can already do this by connecting through a http2 connection, which will allow you to do all this stuff nicely.
