### ISSUE TITLE
Ability to specify which response model fields to prevent REST resource _over-fetching_ via a query parameter or header

### ISSUE THREAD

**Issue by notmorganfreewoman** [esi/esi-issues#1311]
# Feature Request

Ability to specify which response model fields to prevent REST resource _over-fetching_ via a query parameter or header

## Use case

Third party developers request resources and use only some of the data returned thus discarding unneeded data fields wasting bandwidth, known as the _over-fetching_ problem.

We would then be able to specify the needed fields with either a resource query parameter such as _&fields=A,B,C_ or a header such as _x-esi-fields-requested: A,B,C_.

This would enable an efficient implementation (no _over-fetching_) of a REST interface wrapper solution such as proposed in https://github.com/esi/esi-issues/issues/1309

## Authentication

Existing authentication is used

## Example return

Full or a subset (requested fields) of the data model is returned.

# Checklist

Check all boxes that apply to this issue:

- [X] Feature request description is provided
- [X] Use case exists
- [ ] Feature requires a new route
- [X] Feature adds data to existing route
- [ ] Feature requires new auth scope
- [ ] Feature can reuse existing scope
- [ ] Feature does not require auth
- [X] Meta feature, applies to all routes

**Comment by notmorganfreewoman** [comment]
What is the reason for this ticket being closed?

**Comment by DianaOlympos** [comment]
Incapability to understand the design of the API and using it, provide nothing to the conversation on top of existing one.

**Comment by notmorganfreewoman** [comment]
Is there the ability currently to limit the response to a subset of fields that we only need in our apps?

**Comment by ddouglas** [comment]
No

**Comment by notmorganfreewoman** [comment]
Then this ticket should be triaged on it's technical and application merit rather than hostility to the ticket creator.
