### ISSUE TITLE
Support for QUERY HTTP Verb for GET with body and defined semantics

### ISSUE THREAD

**Issue by notmorganfreewoman** [esi/esi-issues#1313]
# Feature Request

Future support for QUERY HTTP Verb for GET with body and defined semantics

There is currently a QUERY verb being proposed for HTTP queries that currently use POST semantics.

See IETF draft https://www.ietf.org/archive/id/draft-ietf-httpbis-safe-method-w-body-02.html and for IANA registery of HTTP verbs see https://www.iana.org/assignments/http-methods/http-methods.xhtml

Examples of such methods in ESI are

https://esi.evetech.net/ui/#/operations/Assets/post_characters_character_id_assets_locations
https://esi.evetech.net/ui/#/operations/Assets/post_characters_character_id_assets_names
https://esi.evetech.net/ui/#/operations/Assets/post_corporations_corporation_id_assets_locations
https://esi.evetech.net/ui/#/operations/Assets/post_corporations_corporation_id_assets_names
https://esi.evetech.net/ui/#/operations/Character/post_characters_character_id_cspa
https://esi.evetech.net/ui/#/operations/Character/post_characters_affiliation
https://esi.evetech.net/ui/#/operations/Universe/post_universe_ids
https://esi.evetech.net/ui/#/operations/Universe/post_universe_names

## Use case

Developers using POST for GET query bodies and require safe and idempotent semantics.

# Checklist

Check all boxes that apply to this issue:

- [x] Feature request description is provided
- [x] Use case exists
- [x] Feature requires a new route
- [ ] Feature adds data to existing route
- [ ] Feature requires new auth scope
- [x] Feature can reuse existing scope
- [ ] Feature does not require auth
- [ ] Meta feature, applies to all routes

**Comment by notmorganfreewoman** [comment]
> As far as I can tell, the propositions are drafts and not finalised. I wouldn't think this would even be considered in the API until the draft is approved and finalised. Given the other problems and pressures with the ESI, I don't see this being a priority personally.

Obviously we wait for finalisation, this ticket is to track this method. POST is not the correct way to do it semantically as it is not idempotent and safe, GET can use bodies but undefined semantics. QUERY addresses this.

1) this is a "feature request" and 2) I stated "Future support" and 3) this is the way it is going for HTTP complex query methods.

**Comment by warlof** [comment]
Definitely not a good idea to invest on a draft. Keeping an eye on it... Maybe.

**Comment by GoldenGnu** [comment]
This is not likely to happen, so, I'm going to close it, so it doesn't clutter the repo more than necessary.
