### ISSUE TITLE
Error 404 on /latest/search/

### ISSUE THREAD

**Issue by dunsparce9** [esi/esi-issues#1323]
# Bug

The `/search` endpoint returns `"error": "Not found"` for every type of search query.

## Request

`GET /latest/search/?datasource=tranquility`

### Status Code

`404`

### Headers
```
access-control-allow-credentials: true 
 access-control-allow-headers: Content-Type,Authorization,If-None-Match,X-User-Agent 
 access-control-allow-origin: * 
 access-control-expose-headers: Content-Type,Warning,ETag,X-Pages,X-ESI-Error-Limit-Remain,X-ESI-Error-Limit-Reset 
 access-control-max-age: 600 
 content-language: en-us 
 content-length: 21 
 content-type: application/json; charset=utf-8 
 date: Mon, 11 Jul 2022 13:03:14 GMT 
 strict-transport-security: max-age=31536000 
 vary: Accept-Language 
 x-esi-error-limit-remain: 99 
 x-esi-error-limit-reset: 46 
```

### Body

```json
{
  "error": "Not found"
}
```

## Expected
`200`

**Comment by soratidus999** [comment]
It has been communicated to me, via my available CCP channels that this is offline intentionally, without notice or update.

I welcome a more direct answer from a team responsible for ESI and would still consider this a bug or fault until an official notice of intent is given (ie via eve_status or similar)

**Comment by Jimmy062006** [comment]
extended abuse of the unauthenticated (v2 search) endpoint meant they took it down.

Apparently there is an authenticated version we can use but I cant find it.

**Comment by Slazanger** [comment]
the authenticated search is here: https://esi.evetech.net/ui/#/Search/get_characters_character_id_search

**Comment by Jimmy062006** [comment]
> the authenticated search is here: https://esi.evetech.net/ui/#/Search/get_characters_character_id_search

That endpoint doesn't seem to exist

**Comment by Haannbboo** [comment]
Response from validate_eve_jwt contains field ``'sub': 'CHARACTER:EVE:1234567890'``, which gives character_id of an authenticated user. Some other search categories are available through SDE, such as region_id, system_id, type_id, etc., not sure for corp id and alliance id.

**Comment by hregibo** [comment]
Will the `/search` authenticated endpoint be available soon with just the Bearer required, instead of a random scope?
The one linked before refers to a search with a scope `esi-search.search_structures.v1` which I find odd for searching characters (but I get it we can search for something else, my use case is characters).

This may cause various programs such as `Eve2twitch` (not actually doing SSO auth, but searching for character names based on what is input on twitch) and the CCPTV Loyalty Reward bot (which uses the eve2twitch api to find matching ingame character names for people claiming Galnet skins rewards)

**Comment by GoldenGnu** [comment]
It's worth noting that according to the changelog: https://github.com/esi/esi-issues/blob/master/changelog.md#2022-07-12
The character who is doing the searching should be the one used for auth. That means that according to changelog using a single character to do all your searching for your page/program is not how the endpoints is suppose to be used. In short if you want users to use the search endpoint, they need to auth for it.
