### ISSUE TITLE
/universe/races missing races 16, 135 from output

### ISSUE THREAD

**Issue by joaomlneto** [esi/esi-issues#1328]
# Bug

Bloodlines with IDs 9, 10, 19 have a `race_id` of 16 (probably Jovians).
Bloodlines with ID 25, 26, 27 have `race_id` 135 (Triglavians)

However, a race with this ID is not returned by the `/universe/races` endpoint.

`GET /universe/bloodlines`:

```
[
  …
  {
    "bloodline_id": 10,
    "corporation_id": 1000178,
    "description": "The different branches of Jovians (…)",
    "name": "Modifier",
    "race_id": 16,
    …
  },
  …
]
```

`GET /universe/races`:

```
[
  {
    "alliance_id": 500001,
    "description": "…",
    "name": "Caldari",
    "race_id": 1
  },
  {
    "alliance_id": 500002,
    "description": "…",
    "name": "Minmatar",
    "race_id": 2
  },
  {
    "alliance_id": 500003,
    "description": "…",
    "name": "Amarr",
    "race_id": 4
  },
  {
    "alliance_id": 500004,
    "description": "…",
    "name": "Gallente",
    "race_id": 8
  }
]
```

---

Also seen in:
- https://forums.eveonline.com/t/bug-in-esi-race-jove-blood-drfter/320149

**Comment by soratidus999** [comment]
`/v1/universe/races/` is reported to contain Jove and Trig now, awaiting cache expiry at 1105

**Comment by joaomlneto** [comment]
Will have a look and then close this :-)

**Comment by joaomlneto** [comment]
Closing — this is fixed!… but now the issue is https://github.com/esi/esi-issues/issues/1385
