### ISSUE TITLE
Missing groups in /universe/groups

### ISSUE THREAD

**Issue by joaomlneto** [esi/esi-issues#1330]
# Bug

Some groups are missing in https://esi.evetech.net/latest/universe/groups/

For example, Category 23 (https://esi.evetech.net/latest/universe/categories/23) returns `471` within its groups, but this is missing from the above endpoint.

Querying https://esi.evetech.net/latest/universe/groups/471 returns a valid response:
```
{
   "category_id":23,
   "group_id":471,
   "name":"Corporate Hangar Array",
   "published":true,
   "types":[
      17621,
      24652
   ]
}
```

**Comment by GoldenGnu** [comment]
The endpoint have pages:
https://esi.evetech.net/latest/universe/groups/?page=2 have  group 471
See https://esi.evetech.net/ui#/Universe/get_universe_groups for details
