### ISSUE TITLE
EVE v20.10 - non contested / removed FW systems appearing in /fw/systems

### ISSUE THREAD

**Issue by soratidus999** [esi/esi-issues#1337]
# Bug

Systems removed from Faction Warfare are still appearing in https://esi.evetech.net/ui/#/Faction%20Warfare/get_fw_systems
https://www.eveonline.com/news/view/patch-notes-version-20-10#spoiler

## Request

`GET https://esi.evetech.net/latest/fw/systems/?datasource=tranquility`

### Status Code

`200`

### Headers

```
[Date: Fri, 27 Apr 2018 07:22:48 GMT](date: Tue, 08 Nov 2022 13:10:12 GMT)
[[Expires](expires: Tue, 08 Nov 2022 13:22:09 GMT):](expires: Tue, 08 Nov 2022 13:22:09 GMT)
[Last-Modified:](last-modified: Tue, 08 Nov 2022 12:52:09 GMT)
[X-ESI-Request-ID: dcc736af-a73a-4c99-add5-8d66e197cec6](x-esi-request-id: 76f30b21-b4af-4991-83bc-d3ee7389f72e)
[ETag:](etag: "45d67176cb178a60a66bcb1a938209c4999c396999974e895a843846")
```

### Body

Example of Intaki
```json
... fw systems
  {
    "contested": "contested",
    "occupier_faction_id": 500001,
    "owner_faction_id": 500004,
    "solar_system_id": 30003788,
    "victory_points": 640,
    "victory_points_threshold": 75000
  },
... fw systems
```

## Expected

There should be no entry for 30003788 or any of the removed FW systems in the response

# Checklist

Check all boxes that apply to this issue:

- [x] Bug description is provided
- [x] Request path is provided
- [x] Response status code is provided
- [x] Response headers are provided
- [x] Response body is provided
- [x] Expected response is provided

**Comment by soratidus999** [comment]
Eve 2022-11-10.1 patch notes report
```
Updated ESI to no longer show systems that were removed from Factional Warfare.
```
#
I am not near an ESI client to test, I’d be very welcome if CCP would confirm and close this issue themselves

**Comment by guiguilechat** [comment]
system absent from response

![image](https://user-images.githubusercontent.com/26408407/201491080-784edcf6-e958-427d-9acf-438e921429ec.png)
