### ISSUE TITLE
/characters/CHARACTER_ID/corporationhistory/ returns empty result

### ISSUE THREAD

**Issue by truekenny** [esi/esi-issues#1342]
# Bug

Corporation history query returns empty result.

## Request

`GET /latest/characters/94998281/corporationhistory/?datasource=tranquility`

Example: https://esi.evetech.net/latest/characters/94998281/corporationhistory/?datasource=tranquility

### Status Code

`200`

### Headers

```
date: Thu, 19 Jan 2023 11:28:50 GMT
content-type: application/json; charset=UTF-8
content-length: 2
access-control-allow-credentials: true
access-control-allow-headers: Content-Type,Authorization,If-None-Match,X-User-Agent
access-control-allow-methods: GET,HEAD,OPTIONS
access-control-allow-origin: *
access-control-expose-headers: Content-Type,Warning,ETag,X-Pages,X-ESI-Error-Limit-Remain,X-ESI-Error-Limit-Reset
access-control-max-age: 600
allow: GET,HEAD,OPTIONS
cache-control: public
etag: "ed2e5773d709f4a0654d954884b08db4e152aeb8a70cb70b54e01bc4"
expires: Fri, 20 Jan 2023 11:23:13 GMT
last-modified: Thu, 19 Jan 2023 11:23:13 GMT
strict-transport-security: max-age=31536000
x-esi-error-limit-remain: 96
x-esi-error-limit-reset: 10
x-esi-request-id: 9cab2cba-6355-421b-a978-813bd592b625
```

### Body

```
[]
```

## Expected

Expected to see an array of corporations.
Something like this:
```
[
  {corporation_id: 100000001, record_id: 100001, start_date: "2020-10-10 10:10:10"},
  {corporation_id: 100000002, record_id: 100002, start_date: "2020-11-10 10:10:10"},
  {corporation_id: 100000003, record_id: 100003, start_date: "2020-12-10 10:10:10"}
]
```

# Checklist

Check all boxes that apply to this issue:

- [x] Bug description is provided
- [x] Request path is provided
- [x] Response status code is provided
- [x] Response headers are provided
- [x] Response body is provided
- [x] Expected response is provided

**Comment by LeoJian622** [comment]
收到勒。。。(-o-)／   _(_^_)_  请不要介意这封自动回复。。。。

**Comment by soratidus999** [comment]
This is sadly intentional 
https://forums.eveonline.com/t/esi-characters-corporation-history/391132
https://github.com/esi/esi-issues/commit/4f1240da92b4ec443af96f48971d68ac3851c459

**Comment by truekenny** [comment]
thanks, CCP
