### ISSUE TITLE
Localhost and ESI connections

### ISSUE THREAD

**Issue by kyle-mcknight** [esi/esi-issues#1347]
# Inconsistency

I've seen other posts about this but most have to do with SSO.

I am able to connect via SSO and get auth codes and tokens from a server hosted on my dev machine using localhost.

However, afterward, when attempting to hit a ESI endpoint such as 'characters', I start getting CORS errors connecting from localhost to ESI. 

Documentation uses localhost everywhere as examples so I would think this would work.

## Routes

All that I've tried

## Resolution

# Checklist

Check all boxes that apply to this issue:

- [x] Inconsistency description is provided
- [x] Inconsistent route(s) are provided
- [ ] Resolution [will require a version bump](https://docs.esi.evetech.net/docs/breaking_changes)
- [ ] Resolution [does not require a version bump](https://docs.esi.evetech.net/docs/breaking_changes)

**Comment by Blacksmoke16** [comment]
Do you have an actual example? The `/v5/characters/{character_id}/` endpoint has the proper CORs headers so it should work from JS.

```sh
$ curl -I https://esi.evetech.net/v5/characters/2047918291/
HTTP/2 200
date: Fri, 07 Apr 2023 14:58:48 GMT
content-type: application/json; charset=UTF-8
access-control-allow-credentials: true
access-control-allow-headers: Content-Type,Authorization,If-None-Match,X-User-Agent
access-control-allow-methods: GET,HEAD,OPTIONS
access-control-allow-origin: *
access-control-expose-headers: Content-Type,Warning,ETag,X-Pages,X-ESI-Error-Limit-Remain,X-ESI-Error-Limit-Reset
access-control-max-age: 600
allow: GET,HEAD,OPTIONS
cache-control: public
etag: "e05f3c9409463d55d2b16c183d680933142d5aad63b68ba8b54f5aa9"
expires: Sat, 08 Apr 2023 07:39:42 GMT
last-modified: Fri, 07 Apr 2023 07:39:42 GMT
strict-transport-security: max-age=31536000
x-esi-error-limit-remain: 99
x-esi-error-limit-reset: 12
x-esi-request-id: c4bb14a7-6a33-4fc1-9619-129979d1292d
```

**Comment by kyle-mcknight** [comment]
Just figured out this was an issue on my end. Forgot the character ID. Not an issue for me.

Thank you, @Blacksmoke16
