### ISSUE TITLE
How to decode value of limited time booster

### ISSUE THREAD

**Issue by Vizis** [esi/esi-issues#1357]
Hello
I've spend some time on this and i really have no idea how to convert value of "Expiry Date" of Limited Time [19] Booster
I tried to do in on example "Extended Capsuleer Day XX Cerebral Accelerator"
https://esi.evetech.net/latest/universe/types/76507/?datasource=tranquility&language=en
which dogma_attribute 2422 is: 19549.45763888889
Unit_id is 143 which is 
"description": "Date and time", 
"name": "Datetime"
but when i tring to convert this wiht php i get 1970-01-01 05:25:49 but it should be 2023-07-11 00:00:00

**Comment by Blacksmoke16** [comment]
This would probably be better suited question for the forums: https://forums.eveonline.com/c/technology-research/third-party-developers/76.
