### ISSUE TITLE
Error getting structure market price. 

### ISSUE THREAD

**Issue by YukhaMamed** [esi/esi-issues#1370]
Hello, i am trying to get market price from NPC station, and there error appear -  invalid structure identifier. Structure ID 60014269. I tried  dock my character at this station, but error not resolved.

**Comment by Blacksmoke16** [comment]
The function `markets_structures_structure` are for citadels, not NPC stations. There is no equivalent function for them either. You either need to use `markets_region_orders` and filter down to that one location, or use an aggregate service like Fuzzworks' API.
