### ISSUE TITLE
ESI API return incorrect route path

### ISSUE THREAD

**Issue by pfh59** [esi/esi-issues#1371]
# Bug

Request a route between Amarr and Ikuchi with flag set to Shortest

## Request

`GET https://esi.evetech.net/latest/route/30002187/30000138/?datasource=tranquility&flag=shortest

## Response Body

[
  30000138,
  30001379,
  30001376,
  30002813,
  30002809,
  30002811,
  30002812,
  30005334,
  30005331,
  30005203,
  30005201,
  30005199,
  30005200,
  30005205,
  30005195,
  30005194,
  30005193,
  30005192,
  30004083,
  30004081,
  30002197,
  30002193,
  30003491,
  30002187
]

**Number of jump 24...**

### Status Code

`200`

### Headers

 access-control-allow-credentials: true 
 access-control-allow-headers: Content-Type,Authorization,If-None-Match,X-User-Agent 
 access-control-allow-methods: GET,HEAD,OPTIONS 
 access-control-allow-origin: * 
 access-control-expose-headers: Content-Type,Warning,ETag,X-Pages,X-ESI-Error-Limit-Remain,X-ESI-Error-Limit-Reset 
 access-control-max-age: 600 
 allow: GET,HEAD,OPTIONS 
 cache-control: public 
 content-length: 217 
 content-type: application/json; charset=UTF-8 
 date: Tue, 16 Jan 2024 16:58:59 GMT 
 etag: "42d87f328a949841fd00d8d8fb0139bc0b69765aef2fc98f210a74be" 
 expires: Wed, 17 Jan 2024 16:58:59 GMT 
 last-modified: Tue, 16 Jan 2024 16:58:59 GMT 
 strict-transport-security: max-age=31536000 
 x-esi-error-limit-remain: 100 
 x-esi-error-limit-reset: 1 
 x-esi-request-id: 06aeb19e-12cf-4d8a-9f00-3244a572ca59 

```
Date: Fri, 27 Apr 2018 07:22:48 GMT
Expires:
Last-Modified:
X-ESI-Request-ID: dcc736af-a73a-4c99-add5-8d66e197cec6
ETag:
```

## Expected

**In game route will be 11 jumps :**

![image](https://github.com/esi/esi-issues/assets/109206285/b7f678bd-442e-4917-b1b9-772c1d83dadd)

# Checklist

Check all boxes that apply to this issue:

- [x] Bug description is provided
- [x] Request path is provided
- [x] Response status code is provided
- [x] Response headers are provided
- [x] Response body is provided
- [x] Expected response is provided

**Comment by truekenny** [comment]
Also between `Balle` and `Nifflung`:

API
---
https://esi.evetech.net/latest/route/30003448/30002634/?datasource=tranquility&flag=shortest (or secure)
`[30003448,30003447,30003433,30003430,30003428,30003396,30003395,30003393,30003384,30003385,30003386,30002048,30002682,30002681,30002641,30002634]`
15 Jumps.

INGAME
---
![изображение](https://github.com/esi/esi-issues/assets/3448197/4e8a6cda-6e1b-4435-8012-99961012b8a2)
6 Jumps.

**Comment by soratidus999** [comment]
There are esi-routes PRs open to fix this, but CCP has not pushed the button 
https://github.com/esi/esi-routes/pull/12

**Comment by pfh59** [comment]
😭

**Comment by soratidus999** [comment]
Amarr to Ikuchi is now 11 https://esi.evetech.net/latest/route/30002187/30000138/?datasource=tranquility&flag=shortest
```
[
  30002187,
  30002282,
  30004080,
  30004079,
  30004078,
  30004083,
  30005192,
  30005196,
  30000134,
  30000132,
  30000138
]
```
Balle to Nifflung is now 6 https://esi.evetech.net/latest/route/30003448/30002634/?datasource=tranquility&flag=shortest
```
[
  30003448,
  30003449,
  30003452,
  30005198,
  30004970,
  30002633,
  30002634
]
```

https://github.com/esi/esi-routes/pull/12 was merged and the endpoint is now operating as expected
