### ISSUE TITLE
/characters/{character_id}/assets/ - 'unknown location_flag (185)'

### ISSUE THREAD

**Issue by soratidus999** [esi/esi-issues#1381]
# Bug

Some assets returned from /characters/{character_id}/assets/ are not returning their location_flag, instead they are returning an "unknown location_flag (185)" breaking validation of this response data. Interfering with the normal usage of this endpoint.

This is occuring because the respective location flags have not been added to eve-glue, https://github.com/esi/eve-glue/pull/35 is pending review and merge

## Request

`GET http://characters/character_id/notifications/?datasource=tranquility`

### Status Code

`200`

### Headers

_Logging this issue on behalf of others, I dont have these new ships_

### Body

```json
[
  {
    "is_singleton": false,
    "item_id": 123456789,
    "location_flag": "unknown location_flag (185)",
    "location_id": 1234567879,
    "location_type": "item",
    "quantity": 1,
    "type_id": 32458
  },
  ...
```

## Expected

```json
[
  {
    "is_singleton": false,
    "item_id": 123456789,
    "location_flag": "InfrastructureHangar",
    "location_id": 1234567879,
    "location_type": "item",
    "quantity": 1,
    "type_id": 32458
  },
  ...
```

# Checklist

Check all boxes that apply to this issue:

- [x] Bug description is provided
- [x] Request path is provided
- [x] Response status code is provided
- [ ] Response headers are provided
- [x] Response body is provided
- [x] Expected response is provided

**Comment by pvyParts** [comment]
I'm also seeing now `"unknown location_flag (186)"`  on the corporate asset endpoints.

**Comment by soratidus999** [comment]
`/v5/characters/{character_id}/assets/` and `/v5/corporations/{corporation_id}/assets/`

Addresses these locations for both Character and Corporation Assets
