### ISSUE TITLE
/characters/{character_id}/notifications/ - unknown notification type (286)

### ISSUE THREAD

**Issue by r0kym** [esi/esi-issues#1398]
# Bug

Similar issue to #1392. 

When attempting to fetch a character than anchored mercenary dens that later got reinforced an unknown notification type is encountered: `unknown notification type (286`.
These notifications seem to be appearing for the "Merceneary Dens Reinforced" notifications.

## Request

Be sure to include the HTTP method, path (including version), and any relevant parameters. Please do not include auth tokens. E.g.:

`GET /latest/characters/{character_id}/notifications/?datasource=tranquility`

### Status Code

`200`

### Headers

Include relevant headers received. Timestamps and request ID is nice, you may not have all these values, fill out what you received (don't worry about headers not listed here, unless pertinent to your issue). E.g.:

```
 access-control-allow-credentials: true 
 access-control-allow-headers: Content-Type,Authorization,If-None-Match,X-User-Agent 
 access-control-allow-methods: GET,HEAD,OPTIONS 
 access-control-allow-origin: * 
 access-control-expose-headers: Content-Type,Warning,ETag,X-Pages,X-ESI-Error-Limit-Remain,X-ESI-Error-Limit-Reset 
 access-control-max-age: 600 
 allow: GET,HEAD,OPTIONS 
 cache-control: private 
 content-encoding: gzip 
 content-type: application/json; charset=UTF-8 
 date: Fri, 15 Nov 2024 17:01:59 GMT 
 etag: "04e49913dbdef9c015510e4d0aaa4f8e80e3ea998c16c4e70906c224" 
 expires: Fri, 15 Nov 2024 17:09:09 GMT 
 last-modified: Fri, 15 Nov 2024 16:59:09 GMT 
 strict-transport-security: max-age=31536000 
 vary: Accept-Encoding 
 x-esi-error-limit-remain: 100 
 x-esi-error-limit-reset: 1 
 x-esi-request-id: 37839e6e-f202-43fd-a3f2-b10d386a688b 
```

### Body

Please provide the response body, feel free to scrub any opsec details you wish. E.g.:

```json
...
  {
    "is_read": true,
    "notification_id": 2064679633,
    "sender_id": 1000438,
    "sender_type": "corporation",
    "text": "aggressorAllianceName: <a href=\"showinfo:16159//AGGRESSOR_ALLIANCE_ID\">AGGRESSOR_ALLIANCE_NAME</a>\naggressorCharacterID: AGGRESSOR_CHARACTER_ID\naggressorCorporationName: <a href=\"showinfo:2//AGGRESSOR_CORPORATION_ID\">AGGRESSOR_CORPORATION_ID</a>\nitemID: &id001 1047210434346\nmercenaryDenShowInfoData:\n- showinfo\n- 85230\n- *id001\nplanetID: PLANET_ID\nplanetShowInfoData:\n- showinfo\n- 11\n- PLANET_ID\nsolarsystemID: SOLAR_SYSTEM_ID\ntimestampEntered: 133761599343475662\ntimestampExited: 133762472653475662\ntypeID: 85230\n",
    "timestamp": "2024-11-15T15:59:00Z",
    "type": "unknown notification type (286)"
  },
...
```

## Expected

Please provide either the expected return code, correct response body, header value, or some combination thereof. E.g.:

`200`

```json
...
  {
    "is_read": true,
    "notification_id": 2064679633,
    "sender_id": 1000438,
    "sender_type": "corporation",
    "text": "TEXT,
    "timestamp": "2024-11-15T15:59:00Z",
    "type": "DenReinforced"
  },
...
```

# Checklist

Check all boxes that apply to this issue:

- [x] Bug description is provided
- [x] Request path is provided
- [x] Response status code is provided
- [x] Response headers are provided
- [x] Response body is provided
- [x] Expected response is provided

**Comment by soratidus999** [comment]
internal name is likely `MercenaryDenReinforced`, taken from client strings
