### ISSUE TITLE
[Proposal] New logging endpoint

### ISSUE THREAD

**Issue by cvweiss** [esi/esi-issues#223]
I'd like to propose an endpoint that returns accesses to a character's ESI endpoints. This will be an endpoint that requires authorization with a new scope:

    esi-character.read_logs

The endpoint could be something similar to:

    GET /character/{character_id}/logs/

The return would be something similar to

```
{
  "application/json": [
    {
        "type": "GET",
        "endpoint" : "/characters/1234567890/killmails/recent/",
        "access_dttm": "2017-01-09T11:57:47Z",
        "application": "zKillboard"
    },
    {
        "type": "GET",
        "endpoint" : "/characters/1234567890/assets/",
        "access_dttm": "2017-01-10T18:13:14Z",
        "application": "Eve-Contacts"
    },
    {
        "type": "PUT",
        "endpoint" : "/characters/1234567890/contacts/",
        "access_dttm": "2017-01-10T18:13:14Z".
        "application": "Eve-Contacts"
    }
  ]
}
```

* The endpoint may need to be paginated depending on available history (30-90 days) and the number of accesses that have been logged.
* This logging endpoint does not need to return any endpoint accesses that give public information about the character. Only endpoints that require authorization should be returned.
* Clarification: This endpoint is separate from SSO, since SSO is another entity, and therefore this endpoint cannot return creation of refreshTokens or creation of accessTokens. (although this would be really nice to have)

edit: IP Address removed from examples to reflect discussion below.

**Comment by Seavert** [comment]
Should it return records about itself?
Or better implement `/character/{character_id}/logs/audit/` with own scope to check who is checking?

**Comment by cvweiss** [comment]
@Seavert yes, absolutely. It should return a record that includes the name of the app that is checking.

**Comment by ddavaham** [comment]
No ip address. Just name of the app please. Ip is not revealed when logging into authorize scopes so it should not be revealed in any endpoint, even authed endpoints. However, even with this exception, recruiters will be able to use this to determine which apps characters have authenticated with. This information is usually only available to the characters themselves from the support portal. I still like the idea though

**Comment by cvweiss** [comment]
Agreed, no IP address if the App Name is provided.

**Comment by itshouldntdothis** [comment]
Not a fan of this being exposed via ESI given the possibility to ban users from using other apps. Feel this information should only be exposed to the character via the support portal similar to how XML logs were exposed.

**Comment by cvweiss** [comment]
After some discussion in #esi on slack, I have to agree that an endpoint like this would cause too much trouble and give too much power to app developers. Especially with what @itshouldntdothis pointed out. 

I am closing the issue as I do not want this endpoint anymore.
