### ISSUE TITLE
/universe/structures/{structure_id}/ does not return structure_id in the response.

### ISSUE THREAD

**Issue by MrNukealizer** [esi/esi-issues#273]
/universe/structures/{structure_id}/ does not return structure_id in the response data. All of the other /universe/xxx/{xxx_id} endpoints return xxx_id in the response, making the response for structures unique in that regard.

**Comment by Regner** [comment]
It's something they are fairly inconsistent about. The character details page for example doesn't return it either.

**Comment by ddouglas493** [comment]
Gonna chip in here. To my knowledge, no endpoint that requires an id or any type to make the request returns that id in the response. That includes Characters, Corporations, and Alliances. It would be nice if the id was included in the response body.

**Comment by MrNukealizer** [comment]
That was pretty much my point. You can request info on a station and the id is in the returned data. You can do the same for types, groups, planets, stargates, etc. When requesting information on a structure, however, if you want to associate the data with the id you need to do more work on the returned data to add it.

**Comment by a-tal** [comment]
I'm way more inclined to remove the instances where we return a param passed instead.

from a quick look at `esi-universe`, that would be:

- [ ] GET /universe/categories/{category_id}/
- [ ] GET /universe/constellations/{constellation_id}/
- [ ] GET /universe/graphics/{graphic_id}/
- [ ] GET /universe/groups/{group_id}/
- [ ] GET /universe/moons/{moon_id}/
- [ ] GET /universe/planets/{planet_id}/
- [ ] GET /universe/regions/{region_id}/
- [ ] GET /universe/stargates/{stargate_id}/
- [ ] GET /universe/stations/{station_id}/ (v2 only)
- [ ] GET /universe/systems/{system_id}/ (v2 only)
- [ ] GET /universe/types/{type_id}/ (v2 and v3)

ping @aquarhead for input/feedback

**Comment by Regner** [comment]
Why would you prefer to remove the ID instead of add it in if you don't mind me asking?

**Comment by a-tal** [comment]
it's information the requestor already has

**Comment by Robbilie** [comment]
its information the requester probably wants to store associated with the new data
(i for example dump the returned ESI data with an id added if not existant yet into a mongodb so either i create a new object with the returned stuff and the id that i already had or i just use the complete object i get from esi…)

**Comment by Regner** [comment]
The requester doesn't always have it. Links get passed around for example. The fleet links from the client for example? Or links passed from one app to another.

**Comment by aquarhead** [comment]
I'm more towards thinking of it as a part/property of the resource we're requesting. So I'd vote for having it in the response (as a representation of the resource)

**Comment by lukasni** [comment]
Closing this as it is covered by #1122 which includes more examples
