### ISSUE TITLE
Possible values for fittings_item flag are not documented

### ISSUE THREAD

**Issue by OrthoLoess** [esi/esi-issues#350]
The flag here requires an integer according to the swagger spec. Presumably the possible values should be listed in an enum or similar

https://esi.tech.ccp.is/latest/#!/Fittings/post_characters_character_id_fittings

```
post_characters_character_id_fittings_fitting {
description (string): description string ,
items (Array[post_characters_character_id_fittings_item]): items array ,
name (string): name string ,
ship_type_id (integer): ship_type_id integer
}
post_characters_character_id_fittings_item {
flag (integer): flag integer ,
quantity (integer): quantity integer ,
type_id (integer): type_id integer
}
```

**Comment by a-tal** [comment]
this request is to apply the location_flag enum from `/characters/{character_id}/assets/` to this route, in place of the integer `flag`.

makes sense, will need to create a new version to break the spec.

**Comment by a-tal** [comment]
here's the enum to use: https://github.com/ccpgames/eve-glue/blob/7ac5d1c6f04b79d418543910e9e0470530352cfb/eve_glue/location_flag.py#L7

still want to make a new version of this using the names tho

**Comment by CarbonAlabel** [comment]
Duplicate of https://github.com/esi/esi-issues/issues/896.
