### ISSUE TITLE
POST on /characters/{character_id}/mail/ results in (random) HTTP responses, and random actions.

### ISSUE THREAD

**Issue by Conjur0** [esi/esi-issues#393]
# Bug

Posting the same exact content yields different responses, randomly.
HTTP/1.0 500 Internal Server Error, mail is not sent, no response
HTTP/1.0 502 Bad Gateway, mail is sent 75% of the time, no response
HTTP/1.0 503 Service Unavailable, mail is sent 25% of the time, no response
HTTP/1.0 420 status code 420, mail is not sent, no response
HTTP/1.0 200, mail is sent, and yields a response (I believe this is the generated mail ID.. undocumented though).

I cannot confirm when this issue started, as I recently incorporated this endpoint.

**Comment by ccp-zoetrope** [comment]
This bug is not reproducible with any concrete steps but I'd wager that the stability of this route has gotten better since the reporting of this bug as we have made some improvements to the stability of ESI as of late.
