### ISSUE TITLE
Feature request: Contracts BPC/BPO

### ISSUE THREAD

**Issue by GoldenGnu** [esi/esi-issues#407]
# Feature request

### Route
`/characters/{character_id}/contracts/`
`/corporations/{corporation_id}/contracts/`

### Use case
I would like to be able to identify blueprint copies and originals in ESI once the contracts endpoint is completed.
Should work just like the ```quantity``` in the assets ESI endpoint

### Example returns
```quantity: -2```  = BPC (Blueprint Copy)
```quantity: -1```  = BPO (Blueprint Original)
```quantity: 2```  = BPO (Blueprint Original)

```quantity: 1```  = Should never be used for blueprints, use ```-1``` for BPO and ```-2``` for BPC
```quantity: 0```  = Should never be used for anything

### Previous XML or CREST route
ContractItems in the XML API

**Comment by a-tal** [comment]
does this use the same conventions as killmails?

**Comment by GoldenGnu** [comment]
I do not know that, I have never used the killmails API...

**Comment by GoldenGnu** [comment]
It does not have to use the quantity like assets. Any way you like to do it is fine by me. As long as it's possible to identify both BPO and BPC, I'm a happy man :)

**Comment by ddouglas493** [comment]
@GoldenGnu I do not understand why this is even an issue on here. The Contracts Endpoint will likely be identical to the XML Contracts Endpoint. The same conventions will be used that were used on the XML Endpoint and the XML Endpoint uses exactly what you just outlines above.

[XML API ContractItems API Documentation](http://eveonline-third-party-documentation.readthedocs.io/en/latest/xmlapi/character/char_contractitems.html#result-data)

**Comment by GoldenGnu** [comment]
To the best of my knowledge rawQuantity never actually worked in the ContractItems XML API.
Last I check, and I admit that is a while ago, rawQuantity was never returned by the XML API.
So, I just wanted to make sure it was included in ESI and working...

**Comment by CarbonAlabel** [comment]
Closing in favour of https://github.com/esi/esi-issues/issues/827.
