### ISSUE TITLE
get_markets_structures_structure_id: Regularly receiving 403 'Market access denied' for public structures with a market module installed

### ISSUE THREAD

**Issue by wtfrank** [esi/esi-issues#458]
# Bug

Receiving 403 Market Access Denied on many occasions.

For example structure 1022725140573 has been a public structure for months, but ESI gave 403 Market Access Denied on multiple occasions over the last few days. I have many other examples like this.

2017-06-14 12:01:03,121 root        : WARNING  marked 1022725140573 as market-less
2017-06-17 01:59:57,894 root        : WARNING  marked 1022725140573 as market-less
2017-06-17 03:15:54,586 root        : WARNING  marked 1022725140573 as market-less
2017-06-17 19:03:04,230 root        : WARNING  marked 1022725140573 as market-less
2017-06-17 19:10:02,825 root        : WARNING  marked 1022725140573 as market-less
2017-06-17 21:16:48,214 root        : WARNING  marked 1022725140573 as market-less
2017-06-18 01:56:14,457 root        : WARNING  marked 1022725140573 as market-less
2017-06-18 03:12:19,340 root        : WARNING  marked 1022725140573 as market-less
2017-06-18 03:54:09,732 root        : WARNING  marked 1022725140573 as market-less
2017-06-18 12:03:42,022 root        : WARNING  marked 1022725140573 as market-less
2017-06-19 02:33:12,718 root        : WARNING  marked 1022725140573 as market-less

### Request

https://esi.tech.ccp.is/latest/#!/Market/get_markets_structures_structure_id

### Response

403 error: Market access denied

### Expected
200 response, and orders

**Comment by MichelArendt** [comment]
I can confirm this... even when using from ESI website with full authorization. For example, using Jita as the station ID (60003760) - a case where it should work - returns 403.

**Comment by antihax** [comment]
The continued increase of structures for uses other than markets are causing this to exponentially become worse.. Could we have a list of accessible modules added to `/v1/universe/structures/{structure_id}/` ? This endpoint requires authentication if i am reading correctly, so the use case would be to pull `/structures/` then `/structures/{structure_id}/` to determine if we should pull the market.

**Comment by PeterGottesman** [comment]
I can confirm this is still returning a 403 error, is there any status update on this?

**Comment by ccp-zoetrope** [comment]
Unfortunately no update yet. We want to make the structure side of the API much better and useful, but it won't happen at least until all "parity" labelled issues are complete.

**Comment by Erikvv** [comment]
Maybe put a note in the Swagger docs. I've been pulling my hair out for hours why I couldn't fetch Jita orders.

**Comment by antihax** [comment]
Maybe because there are no Jita structures?

**Comment by Erikvv** [comment]
I interpreted structure as including stations. Seems intuitive but your comment leads me to believe that's wrong?

**Comment by antihax** [comment]
Correct; stations are not structures. You can use the market endpoint to get station market data such as Jita.

**Comment by Aidansavage** [comment]
Structure != Station

Jita 4-4 is a station, the "Perimeter - Who the hell owns THIS hub now?" is a structure. Structure market endpoint will only show orders from just that. The other market endpoint will show all station orders as well as (unless I'm having a case of spodbrain due to overworking) ranged buy orders (since you can sell to those _from_ a station).

**Comment by tsuthers-ccpgames** [comment]
So to clarify: a structure being public does not mean you are allowed access to it's market, if it has one. The definition of a public structure is that you are allowed to dock at it, nothing more.

However, I have just deployed a patch that adds service filters to /v1/universe/structures/

You can now pass a query param to that endpoint to filter it to structures that are publicly dockable AND have an online market that is publicly accessible, which should solve this problem.
