### ISSUE TITLE
Add owner information to the /universe/structures/{structure_id}/ endpoint

### ISSUE THREAD

**Issue by DavidEdwards** [esi/esi-issues#482]
# Feature request

It would be great to know who owns a particular citadel.

### Route

/universe/structures/{structure_id}/

### Use case

To determine who owns the citadel. I would for example, like to show only citadels from certain alliance(s), without any of the freeport fluff.

### Example returns

Not all IDs must be included. I have never placed a citadel, and I am not certain who actually "owns" a citadel. Whether it be at the personal or corporation level. 

```
{
  "name": "This is the name of a station",
  "solar_system_id": 1,
  "type_id": 35832,
  "character_id": 1,
  "corporation_id": 2,
  "alliance_id": 3,,
  "position": {
    "x": 1,
    "y": -2,
    "z": 3
  }
}
```

**Comment by ddouglas493** [comment]
Character ID would be irrelevant since you need to be in a corporation to drop a citadel.

**Comment by ErikKalkoken** [comment]
It would be fantastic to see the owner corporation ID of a structure in the API. 
I made a website that shows all public structures in Eve (see [here](http://www.kalkoken.org/apps/evestruct/) for the tool) and it would be awesome to also be able to show that information.

**Comment by Chnkr** [comment]
all i want for Christmas is this feature 👍

**Comment by tsuthers-ccpgames** [comment]
If we're in this area, also https://github.com/ccpgames/esi-issues/issues/23

**Comment by lunedis** [comment]
Is this planned or is there a game design decision pending (why?)

**Comment by BTFO** [comment]
Yes Yes Yes! 👍

**Comment by eqvinox** [comment]
+1 - just `corporation_id` would be reeeeeally cool, `alliance_id` even better (but can grab that from the corp...)

**Comment by eqvinox** [comment]
Any update on this? Can we get this before the station->citadel conversion? We can get station ownership currently, without this it's a step back...

**Comment by eqvinox** [comment]
@ccp-zoetrope @tsuthers-ccpgames pokes for notifications

**Comment by Chnkr** [comment]
I've been working on tools to keep track of citadels for some corps, not being able to know who owns one is rather annoying :-(

**Comment by dhoffend** [comment]
Waiting for this one too!

**Comment by BTFO** [comment]
Is this pending on game design feedback or something else? Looks like a trivial change imo

**Comment by ccp-zoetrope** [comment]
/v2/universe/structures/{structure_id}/ has been deployed and includes `owner_id` as an attribute.

**Comment by Chnkr** [comment]
<3
