### ISSUE TITLE
Inconsistent cache times

### ISSUE THREAD

**Issue by CarbonAlabel** [esi/esi-issues#546]
I've noticed several ESI endpoints whose cache times are inconsistent with similar endpoints and/or direct downgrades from the XML/CREST endpoints they are supposed to replace. Here is a list of them, along with my specific complaints.

- [x] https://esi.tech.ccp.is/dev/#!/Character/get_characters_character_id has a cache time of 1 hour, compared to CREST's 5 minutes. Similarly, https://esi.tech.ccp.is/dev/#!/Alliance/get_alliances_alliance_id is on 1 hour, compared to CREST's 30 minutes. I'd like to see the cache times for all public alliance, corporation and character endpoints lowered down to 5 minutes.
- [x] https://esi.tech.ccp.is/dev/#!/Clones/get_characters_character_id_implants has a cache time of 1 hour, compared to 2 minutes of https://esi.tech.ccp.is/dev/#!/Clones/get_characters_character_id_clones. The two endpoints complement each other, and both provide information which may update rapidly during normal gameplay. The cache time of the implants endpoint should be reduced to match the clones endpoint.
- [x] https://esi.tech.ccp.is/dev/#!/Killmails/get_corporations_corporation_id_killmails_recent has a cache time of 1 hour, where the character version of the endpoint is set to only 2 minutes.
- [ ] https://esi.tech.ccp.is/dev/#!/Location/get_characters_character_id_online has a cache time of 1 minute, where in CREST the online status of a character was implied by the location endpoint with a 5 second cache, just like its fellow ESI ship and location endpoints.
- [x] https://esi.tech.ccp.is/dev/#!/Loyalty/get_characters_character_id_loyalty_points doesn't appear to have a cache time set at all.
- [x] https://esi.tech.ccp.is/dev/#!/Skills/get_characters_character_id_attributes has a cache time of 1 hour, compared to the 2 minutes of the other two skill endpoints.
- [x] Nitpicking here, but https://esi.tech.ccp.is/dev/#!/Status/get_status has a cache time of 30 seconds, where in CREST the server status information was provided by the root endpoint which had a specified cache time of 20 seconds, even though I'm pretty sure the user count was actually updated less often.
- [ ] https://esi.tech.ccp.is/dev/#!/Wallet/get_characters_character_id_wallet_journal and https://esi.tech.ccp.is/dev/#!/Wallet/get_characters_character_id_wallet_transactions have a cache time of 1 hour, which is not only higher than their new corporation versions' 5 minutes, but also higher than the XML API's 30 minutes.

**Comment by aquarhead** [comment]
Fixed character lp, set to 3600 sec as in CREST.

**Comment by aquarhead** [comment]
Fixed corporation wallet journal to be 3600 sec, same as character ones.

**Comment by DaneelTrevize** [comment]
What can even change for an alliance's data? Just the executor_corporation_id, and that's not likely done every 5 minutes...

Somewhat similarly, for the character, isn't it just corporation_id and description? CREST's 30mins seems fair.

**Comment by tsuthers-ccpgames** [comment]
Apparently someone already lowered the implants cache to 5 minutes, but I don't see why it shouldn't be 2 same as clones.

**Comment by itshouldntdothis** [comment]
It would be nice if the wallet journal/transaction endpoints could have the cache reduced to allow for real-time isk generation tracking, another example would be the ability to notify a twitch stream that a donation has been made.

**Comment by tsuthers-ccpgames** [comment]
Implants and clones changes are deployed.

Twitch stream rewards is a pretty persuasive argument, but I don't know much about CCP policies in that area, I'm talking to people about it.

**Comment by CarbonAlabel** [comment]
Shortening the cache time on the wallet endpoints can be discussed in https://github.com/esi/esi-issues/issues/829. As all the other points have either been resolved or given an explanation for, I'm closing this issue.
