### ISSUE TITLE
Not found when querying structure market

### ISSUE THREAD

**Issue by krojew** [esi/esi-issues#577]
# Bug

### Request

/v1/markets/structures/1023729674815/

character id: 92990530

### Response

"{ "error": "Not found" }"

### Expected

Market data.

Original bug: https://bitbucket.org/krojew/evernus/issues/320/api-import-prices-only-from-station-item

**Comment by tsuthers-ccpgames** [comment]
There's not a lot of detail here. Do you have access to that citadel's market? What would you expect the response to be?

**Comment by krojew** [comment]
Yes, there was access to the citadel. The response should contain the order list.

**Comment by tsuthers-ccpgames** [comment]
Was the market online at the time?
Is this still reproducible?
Is/was it consistent?
Are there any other cases of this I can look at that you know of?
Does this affect other characters in the same structure?
Are there any other details you can give?

**Comment by krojew** [comment]
- yes
- don't know, can ask in the linked report
- yes
- no info on other cases
- no info
- take a look at linked issue - there may be more info there

**Comment by tsuthers-ccpgames** [comment]
There's not a lot of info here and this ticket hasn't moved in almost a year, I'm going to chalk this one up to similar problems as https://github.com/esi/esi-issues/issues/458 which now has a solution
