### ISSUE TITLE
Character Contracts Items: raw_quantity (missing) and is_singleton (wrong value)

### ISSUE THREAD

**Issue by GoldenGnu** [esi/esi-issues#578]
# Bug

``raw_quantity`` is not returned for blueprints in contracts
``is_singleton`` is ``false``, but should be ``true``

### Request
https://esi.tech.ccp.is/latest/characters/987623974/contracts/123289035/items/?datasource=tranquility

### Response
```
[
  {
    "record_id": 2373674052,
    "type_id": 1146,
    "quantity": 1,
    "is_singleton": false,
    "is_included": true
  },
  {
    "record_id": 2373674053,
    "type_id": 1153,
    "quantity": 1,
    "is_singleton": false,
    "is_included": true
  }
]
```
### Expected
```
[
  {
    "record_id": 2373674052,
    "type_id": 1146,
    "quantity": 1,
    "is_singleton": true,
    "is_included": true,
    "raw_quantity": -2
  },
  {
    "record_id": 2373674053,
    "type_id": 1153,
    "quantity": 1,
    "is_singleton": true,
    "is_included": true,
    "raw_quantity": -1
  }
]
```

### Related issues
Issue #407

**Comment by teroni** [comment]
This is halting my development as well, need to seriously be able to differentiate between BPC and BPO in contracts.

**Comment by CarbonAlabel** [comment]
Closing in favour of https://github.com/esi/esi-issues/issues/827.

Is this still a problem? If so, should consider bumping https://github.com/esi/esi-issues/issues/827 to a bug.
