### ISSUE TITLE
Bug: Corporation bluprints endpoint does not show all blueprints

### ISSUE THREAD

**Issue by ddeka** [esi/esi-issues#611]
# Bug
The corporation blueprints endpoint does not return all blueprints a corporation owns. We store most of our BPOs an BPCs in password protected containers to keep them out of the industry window. These blueprints are not returned by the endpoint. Compared to the corporation assets endpoint we have a total of 273,411 assets including 271,701 blueprints.
### Request
`/v1/corporations/{corporation_id}/blueprints/`
### Response
Returns a total of 10,176 blueprints.
### Expected
A total of 271,701 blueprints.

**Comment by Turiko** [comment]
This is probably just tied to the way the game handles things - it can't know you have the right password or not and apparently assumes not. Thus, the same thing keeping it out of the industry window is keeping it out of the endpoint result.

If you use a trick to fool the game into not seeing specific assets, you probably shouldn't be surprised if the API tied to that game is also fooled by the same thing.

**Comment by DoogeJ** [comment]
@Turiko that could make sense, but would it not be a good idea to have an exception for people that either are CEO/Director, or have roles that allow them to take out the containers anyways (password protection means nothing when they are in your own hangar, you can just repackage them).

**Comment by Turiko** [comment]
Repackaging items or handling inventory is outside of the scope of the ESI endpoint, though - it has permanent consequences for the inventory.

Audit logged containers also wouldn't work like that since AFAIK they need to be empty for some time before they can be repackaged. In the end, this is likely a "bug" in the game's code causing it to be unable to be seen without a player accessing it in the game directly, and fixing that would remove the reason these blueprints were placed in passworded containers in the first place.

**Comment by DoogeJ** [comment]
Well yes obviously it is, I was just meaning to say that the people with those roles already have the ability to see the contents of those containers anyway :)

**Comment by Turiko** [comment]
Well, no, not really. They can't see within the containers, they would have to repackage the containers and thus change the inventory. A read-only way to look into that passworded container without a check for the password (whcih seems only possible in the game client?) doesn't appear to be possible. Remember this is an endpoint with a GET request, it can only read data, not change anything.

**Comment by ccp-zoetrope** [comment]
I would not consider this a bug and @Turiko summed it up nicely:
>If you use a trick to fool the game into not seeing specific assets, you probably shouldn't be surprised if the API tied to that game is also fooled by the same thing.

You will have to use the assets route to get all your blueprints in this case 😄.
