### ISSUE TITLE
There is corp courier contract is ESI output, but no ingame

### ISSUE THREAD

**Issue by nsdonner** [esi/esi-issues#626]
# Bug
I'm not sure that is an ESI bug, but CCP Dev in EBR-136226 forwards me here. 
### Request
So in https://esi.tech.ccp.is/latest/corporations/98378760/contracts/?datasource=tranquility
(in XML API the same)
### Response
i have this contract
...
{
    "contract_id": 123702922,
    "issuer_id": 2009146769,
    "issuer_corporation_id": 1722847451,
    "assignee_id": 1220922756,
    "acceptor_id": 0,
    "type": "courier",
    "status": "outstanding",
    "for_corporation": false,
    "availability": "personal",
    "date_issued": "2017-10-11T19:38:43Z",
    "date_expired": "2017-10-25T19:38:43Z",
    "start_location_id": 60003760,
    "end_location_id": 1023490069862,
    "title": "",
    "date_accepted": "2017-10-11T19:38:43Z",
    "days_to_complete": 14,
    "date_completed": "2017-10-11T19:38:43Z",
    "price": 0,
    "reward": 3000000,
    "collateral": 15000000,
    "volume": 0.6500000000000004
  }
...
### Expected

But there is no such contract ingame, me and others can see other outstanding/finished corporation contracts, (my char have additional rights), but there is no contract from Orfeja (2009146769), and this contract at least should now be "expired", but it still "outstanding"

**Comment by Blacksmoke16** [comment]
Try using the `/ui/openwindow/contract/` endpoint to open that courier and see what it is.

**Comment by tsuthers-ccpgames** [comment]
ESI forwards what's in the DB. If you've got a wedged contract you'll need to file a ticket with the GM's.
