### ISSUE TITLE
Return whether the character is the boss of the fleet on /characters/{id}/fleet/

### ISSUE THREAD

**Issue by PrometheusSatyen** [esi/esi-issues#639]
# Feature request

### Route
/characters/{id}/fleet/
https://esi.tech.ccp.is/latest/#!/Fleets/get_characters_character_id_fleet

### Authentication
SSO with scope esi-fleets.read_fleet.v1

### Use case
* Sometimes I will be querying a fleet endpoint and inadvertently trigger errors because the fleet boss has changed, this endpoint would allow me to periodically check if the boss has changed without causing errors (errors can cause rate limits, rate limits are bad)
* I may know that the boss has been passed to one of a user's 5 registered characters, with this endpoint I can quickly pull and check each character's fleet information until I find the new boss.

### Example returns
```json
{
  "fleet_id": 1083711379940,
  "wing_id": 2096011379940,
  "squad_id": 3171811379940,
  "role": "squad_member",
  "is_boss": true
}
```

### Previous XML or CREST route
N/A

**Comment by lukasni** [comment]
This can be now done by checking the `fleet_boss_id` returned in the v2 response. Not the requested boolean, but fulfils the same role.
