### ISSUE TITLE
Bug: "Role squad_commander requires both wing_id and squad_id" when valid wing_id and squad_id are given

### ISSUE THREAD

**Issue by KevinNortier** [esi/esi-issues#690]
# Bug

When trying to move a fleet member to the squad_commander position an error is returned requesting that both wing_id and squad_id should be given (tho both are already given).

### Request

The following endpoint:
`https://esi.tech.ccp.is/latest/fleets/<fleet_id>/members/<fleet_memeber_id>/`
With the following movement data:
```
{
  "role": " squad_commander",
  "wing_id": <wing_id>,
   "squad_id": <squad_id>
}
```

### Response

`Role squad_commander requires both wing_id and squad_id`

### Expected

Fleet member to be moved to the squad_commader position of the given squad of the given wing.  
(Or an error message if the position is already taken).

**Comment by BuumEdzott** [comment]
In your PUT body, are you actually using `=>` instead of `:` after `”wing_id”` and `”squad_id”`?

**Comment by KevinNortier** [comment]
Nope, that was a typo. Fixed now.

**Comment by seraphx2** [comment]
any ETA? This would be immensely useful.

**Comment by seraphx2** [comment]
Pleeeeeeaaaaassseeeeee

**Comment by CatPlanet** [comment]
Please respond, everything in /fleets endpoint works for me, except this one.

**Comment by ddavaham** [comment]
Please use the thumbs up feature to inform the developers of desired features. Thanks for your feedback

**Comment by a-tal** [comment]
if that response is accurate... I'm guessing this is has a `520` status?

if so this is a monolith error

**Comment by CatPlanet** [comment]
It's `422: Errors in invitation` on attempt to move member to "squad_commander" position.

**Comment by a-tal** [comment]
can confirm, this is a monolith error.

the exact return is:

```
422 

{
  "error": "Role squad_commander requires both wing_id and squad_id"
}
```

when I remove either `wing_id` or `squad_id` I get the endpoint validation error:

```
422

{
  "error": "both `wing_id` and `squad_id` should be specified for squad_commander"
}
```

@ccp_zoetrope the monolith is performing a secondary validation here, incorrectly

**Comment by Lorisu** [comment]
This seems also the case on inviting members to the fleet ?
`POST /fleets/{fleet_id}/members/`

**Comment by Nuramori** [comment]
This would be an important bug to address, as it's highly restrictive to the usefulness of the endpoint

**Comment by tsuthers-ccpgames** [comment]
I've found the root cause of this bug but it looks like there's a strata of other bugs below it, looking at them now.

**Comment by seraphx2** [comment]
@tsuthers-ccpgames things that have to be fixed to be able to fix this or just other stuff that may be more important?

**Comment by tsuthers-ccpgames** [comment]
Ok, fix looks good, it affects both put and post, should roll out next tuesday.

**Comment by tsuthers-ccpgames** [comment]
@seraphx2 turns out not to be that big a deal, I assumed that wing and squad ID's were zero-indexed and relative to the fleet, but they're not, they're globally unique just like fleet ID's. The lower-level bug was just that if you make the same assumption and pass in 0/0 for the wing and squad ID for the first invite you get a runtime error. Now you get a message telling you that the combination of wing/squad/role you gave is invalid.

**Comment by seraphx2** [comment]
Just want to be sure my dream has come true 😂 So this will mean starting next week we can assign wing and squad commanders? 😍 if so. this will finally allow me to complete the functionality on my website regarding fleets.
