### ISSUE TITLE
Unhandled internal error in corporation contract get items endpoint

### ISSUE THREAD

**Issue by irwiss** [esi/esi-issues#697]
# Bug

Getting the error listed below when feeding it `courier` type contracts.

### Request
`https://esi.tech.ccp.is/v1/corporations/{CorporationId}/contracts/{ContractId}/items/?datasource=tranquility`
With access token in headers

### Response
```json
{"error":"Unhandled internal error encountered!"}
```

### Expected
Any error that should give indication suggesting you're feeding it a courier type contract.

**Comment by ccp-zoetrope** [comment]
This was fixed after downtime today. It will not throw `Unhandled internal error` anymore and will return `[]`.
