### ISSUE TITLE
Bug: Assets included items that was destroyed in-game

### ISSUE THREAD

**Issue by GoldenGnu** [esi/esi-issues#698]
# Bug
Character Assets include items that no longer exist in game.
Example: The assets endpoint will return items fitted to ships that was destroyed (It only returns the items that did not drop).

### Route
`/characters/{character_id}/assets/`
Note: It may also affect the corporation endpoint, as I have reports of this happening when trashing assets too.

### Response
Reproduce with `uhnboy ghost`
Here is a list of ItemIDs that may fit the above description:
https://gist.github.com/GoldenGnu/bbd53ed0a42deea9b8f48bd07a40d2a7
They won't all match the description, but, some of them should. (I apologize for the overflow of data)

### Expected
Only assets that still exist

**Comment by tsuthers-ccpgames** [comment]
A quick snoop on some of these items shows that these are all inside containers of some kind, I've seen ships and cargo containers. The container itself is in the junkyard, we're probably not recursing back up the tree far enough.

**Comment by GoldenGnu** [comment]
I'm so happy you're able to reproduce this, thank you for looking into it. :)

**Comment by Kupuyc** [comment]
Similar situation with corporation assest. Some items (ihub upgrades) in list may have location_id which are not in list. For example upgrade
`{"is_singleton":true,"item_id":1024930875660,"location_flag":"StructureInactive","location_id":1022890269606,"location_type":"other","quantity":1,"type_id":2027}`
There is no ihub with item_id 1022890269606.

**Comment by CarbonAlabel** [comment]
See #792.

**Comment by Blacksmoke16** [comment]
Duplicate of #792.
