### ISSUE TITLE
Feature request - POST /ui/openwindow/fittingpreview.

### ISSUE THREAD

**Issue by samuelgrant** [esi/esi-issues#713]
# Feature request
Allow websites to show a fitting in game without saving it to a player account, much like the old system within the IGB.

### Route
POST /ui/openwindow/fitting/

### Authentication
esi-ui.open_window.v1

### Use case
Currently for an application/website to show a pilot a fit, they need to have their own UI or use a third-party tool. Allowing an application to open a fit in-game would give players easier access to the simulation tool/checking skills/multibuy etc and so on without having to save the fit and then find it.

### Previous XML or CREST route
n/a

**Comment by samuelgrant** [comment]
Came across a similar issue today: https://github.com/ccpgames/esi-issues/issues/341 . Thought I would reference it to avoid having multiple issues on a similar request.

**Comment by ddavaham** [comment]
Duplicate of #341. The original is pending GD Feedback right now.
