### ISSUE TITLE
Bug report /alliance/names/

### ISSUE THREAD

**Issue by Aidansavage** [esi/esi-issues#721]
I blame slack for this bug report. Just gonna get that out of the way first.

`https://esi.tech.ccp.is/latest/alliances/names/?alliance_ids=1498700176&datasource=tranquility` => 
```
[
  {
    "alliance_id": 1498700176,
    "alliance_name": "Krysenth"
  }
]
```

Pretty sure this should flat out error with an "`invalid alliance_id`" response. 

edit: Given that /universe/names/ returns the relevant entity type (char/corp/alliance) for each ID passed, would it make more sense to drop the non-universe /names/ endpoints? Or make it more flexible by aliasing /*/names/ to use the framework behind /universe/names/?

**Comment by Aidansavage** [comment]
update- to paraphrase Zoetrope: "Endpoint has outlived it's usefulness." (ie potentially dead soon after parity)

Referencing this to #722 and #723 as well.

**Comment by itshouldntdothis** [comment]
Removed from spec for similar reasons to `/corporations/names/` and` /characters/names/` as detailed in this [blog](https://developers.eveonline.com/blog/article/breaking-changes-to-characters-names-and-corporation-names) with the same resolution of `/universe/names/` as the combined route.
