### ISSUE TITLE
Bug Report /corporations/names/

### ISSUE THREAD

**Issue by Aidansavage** [esi/esi-issues#722]
I blame slack for this one too. Related to #721 

`https://esi.tech.ccp.is/latest/corporations/names/?corporation_ids=1498700176&datasource=tranquility` =>
```
[
  {
    "corporation_id": 1498700176,
    "corporation_name": "Krysenth"
  }
]
```
Should potentially be an error as well instead?

edit: Given that /universe/names/ returns the relevant entity type (char/corp/alliance) for each ID passed, would it make more sense to drop the non-universe /names/ endpoints? Or make it more flexible by aliasing /*/names/ to use the framework behind /universe/names/?

**Comment by Aidansavage** [comment]
update- to paraphrase Zoetrope: "Endpoint has outlived it's usefulness." (ie potentially dead soon after parity)

**Comment by itshouldntdothis** [comment]
Resolved via [blog post](https://developers.eveonline.com/blog/article/breaking-changes-to-characters-names-and-corporation-names) `/universe/names/` should be used as a replacement.
