### ISSUE TITLE
Bug Report /characters/names/

### ISSUE THREAD

**Issue by Aidansavage** [esi/esi-issues#723]
I'm sorry. Related to #721 and #722  

`https://esi.tech.ccp.is/latest/characters/names/?character_ids=98203328&datasource=tranquility`  =>

```
[
  {
    "character_id": 98203328,
    "character_name": "Sanctuary of Shadows"
  }
]
```
No such character actually exists.  Given that /universe/names/ returns the relevant entity type (char/corp/alliance) for each ID passed, would it make more sense to drop the non-universe /names/ endpoints? Or make it more flexible by aliasing /*/names/ to use the framework behind /universe/names/?

**Comment by Aidansavage** [comment]
update- to paraphrase Zoetrope: "Endpoint has outlived it's usefulness." (ie potentially dead soon after parity)

**Comment by itshouldntdothis** [comment]
Resolved via [blog post](https://developers.eveonline.com/blog/article/breaking-changes-to-characters-names-and-corporation-names) `/universe/names/` should be used as a replacement.

**Comment by ccp-zoetrope** [comment]
Thanks for closing this @itshouldntdothis
