### ISSUE TITLE
Deduplicate /markets/{region_id}/types/

### ISSUE THREAD

**Issue by a-tal** [esi/esi-issues#726]
# Bug

As an example, the forge currently returns 288360 items over 289 pages, however, it only has 13 pages worth of unique items:

```python
>>> len(all_types)
288360
>>> len(set(all_types))
12432
```

### Request

https://esi.tech.ccp.is/latest/markets/10000002/types/

### Response

header `x-pages: 289`

### Expected

header `x-pages: 13`

**Comment by cyberwolfru** [comment]
Any updates on this? It's designed for efficient market indexing, but currently not very usable.

**Comment by tsuthers-ccpgames** [comment]
Fix submitted, probably going out tomorrow.
