### ISSUE TITLE
Feature/consistency request - character stats

### ISSUE THREAD

**Issue by Seavert** [esi/esi-issues#740]
# Feature request

### Route
https://esi.tech.ccp.is/ui/?version=latest#/Character/get_characters_character_id_stats
### Description
get_characters_character_id_stats_travel doesnt have number of wormhole docks  - which became possible with 2014 Thera and 2016 citadels appearances.
### Resolution
Add docks_wormhole to response.

**Comment by lukasni** [comment]
Closing this since the character stats endpoint has been deprecated and is no longer being updated. A potential new stats endpoint would likely use activity tracker data but is currently not yet in the works.
