### ISSUE TITLE
/corporations/{corporation_id}/customs_offices/ returns error 500

### ISSUE THREAD

**Issue by ErikKalkoken** [esi/esi-issues#755]
# Bug

### Request
`curl -X GET "https://esi.tech.ccp.is/latest/corporations/98397665/customs_offices/?token=MY_TOKEN" -H  "accept: application/json"`

### Response
http code: 500
body: `{"error":"Unhandled internal error encountered!"}`

### Expected
http code: 200
body: List of custom offices owned by this corporation as JSON array

### Analysis
An analysis by CCP Zoetrope revealed that the error is most likely caused by a custom office that has not yet been configured by a player. Configuring the customs office in question solved the issue. 

Still the endpoint should be able to respond to this situation without breaking.

For comparison: the deprecated XML API (route `/corp/CustomsOffices.xml.aspx`) showed the following result for the same customs office (before applying the workaround):

 `<row itemID="1026790155342" solarSystemID="30002514" solarSystemName="Bosboger" reinforceHour="0" allowAlliance="False" allowStandings="False" standingLevel="0" taxRateAlliance="0" taxRateCorp="0" taxRateStandingHigh="0" taxRateStandingGood="0" taxRateStandingNeutral="0" taxRateStandingBad="0" taxRateStandingHorrible="0" />`

**Comment by tsuthers-ccpgames** [comment]
Not just needs to be configured but needs to go through a server shutdown and reboot after being configured.

**Comment by tsuthers-ccpgames** [comment]
This is a two-part fix, I've deployed the ESI side of the fixes now, and solved a problem with not being able to see alliance tax rates in the process.

The monolith fix has been submitted and will probably go out tomorrow, at which point this issue will resolve.
