### ISSUE TITLE
/universe/groups/{group_id} always return English names

### ISSUE THREAD

**Issue by copyliu** [esi/esi-issues#761]
# Bug

### Request
`curl -i --compressed -X GET --header 'Accept: application/json' 'https://esi.tech.ccp.is/latest/universe/groups/0/?datasource=tranquility&language=ru'`
### Response
`{
  "group_id": 0,
  "name": "#System",
  "published": false,
  "category_id": 0,
  "types": [
    0
  ]
}`
### Expected
`{
  "group_id": 0,
  "name": "#Система",
  "published": false,
  "category_id": 0,
  "types": [
    0
  ]
}`

The group names translation can be found at SDE groupIDs.yaml

**Comment by aquarhead** [comment]
This should have been fixed (a long time ago actually)
