### ISSUE TITLE
Get the new boss of a fleet

### ISSUE THREAD

**Issue by Makeshift** [esi/esi-issues#773]
# Feature request
Not sure if this one would be possible, but I'll try for it anyway.
I'm currently writing a fleet management tool. When the boss of a fleet disconnects or otherwise changes their role in the fleet, you no longer have any access to the fleet, so out of game tools stop working (and it means your error count starts going up! I have it automatically delete after 5, but sometimes this isn't ideal).

It would be really nice to either
1) Be able to see who the fleet boss is in the error message, so I can search through my DB to find their refresh token and continue maintaining the fleet
2) Be able to use anybody in the fleets token to see the member list with roles, so I can check who the boss is and swap to them

### Route
`/fleets/{fleet_id}/members/`
### Authentication
Either none OR use the authentication for get `/fleets/{fleet_id}/members/` auth for ANY member of fleet
### Use case
When the fleet composition changes eg. due to disconnect or swapping FCs, it can break out of game tools that are essential to a lot of fleets. One of these changes would allow us to get the new boss and start receiving/sending information with the fleet again via ESI.
### Example returns
As before

**Comment by DaneelTrevize** [comment]
The proposal involving no authentication is surely a non-starter.

The proposal of being able to access a fleet's members listing via any fleet member's authentication might sound reasonable as a way to smoothly transition to using the new boss's token, but in reality the members endpoint exposes far more data than an in-game squad member can see, such as everyone's ship types and locations. This data should remain restricted to the boss/higher tier fleet commander positions for consistency.

As a solution to the boss changing, this also still actually depends upon trying /members/ for each remembered fleet member's character ID & stored authentication, until you find one that works, to then learn the new boss's character ID.

The only sane solution seems to involve either #774's proposal to not bypass fleet data access consistency (but requires trying member character IDs), or some new unauthenticated `GET /fleets/{fleet_id}/` endpoint or response which simply returns the boss's character ID, in order for those tools that had previously obtained a fleet_id to carry on smoothly via different refresh tokens they have already been trusted with.

**Comment by Aidansavage** [comment]
Alternatively, just include `boss_id` or whatever in the return of `/characters/{character_id}/fleet/`. Fleet boss identity is freely given for fleets you are eligible for ingame. This would merely allow ESI to adhere as close to game design as possible, for now. Not to mention reduces the amount of "discovery" requests to just _one_.

**Comment by tsuthers-ccpgames** [comment]
Yep, https://github.com/esi/esi-issues/issues/774 wins this one, closing in favor of that.
