### ISSUE TITLE
Add structure shield/armor/hull information to the /universe/structures/{structure_id}/ endpoint

### ISSUE THREAD

**Issue by BTFO** [esi/esi-issues#776]
# Feature request

### Route

`/universe/structures/{structure_id}/`

### Authentication

Station Manager role

### Use case

Notifications already push this information, but those are only sent once, adding this information to the structure block, or another call will allow corporations to know if their structure is shot at for real, or if it's just someone pinging their structure for shits and giggles.

**Comment by lukasni** [comment]
As in, current hitpoints? That might be overkill for ESI, you should still have to log on for _some_ things ^^

**Comment by BTFO** [comment]
Correct, when you run into having more than 1,000 anchored structures the amount of notification spam you receive is rather insane during the weekends, so having this endpoint would make it easier to reduce the possible spam and only forward the ones that are actually being shot at.

**Comment by Makeshift** [comment]
This would require a hella low cache timer though, aren't most of the structure requests quite intensive?

**Comment by ErikKalkoken** [comment]
I can understand your viewpoint, but I don't think this should be implemented. It would only benefit a very small amount of players (only very few have to manage that many structures) and there are way more important feature request that should get priority. 

So just do what everyone else does: Undock and check out what is happening at your structure (or sent someone) after you received the notification ;-)

**Comment by jowrjowr** [comment]
since the notification already pushes this information, and the notification is already triggered at 95%, there's next to no chance of this happening. if you feel strongly about it, get bartender to re-open.

**Comment by CarbonAlabel** [comment]
The [corporation structures endpoint](https://esi.evetech.net/ui/?version=_dev#/Corporation/get_corporations_corporation_id_structures) already returns this info; the `state` parameter will tell you the current reinforcement state of the structure.
