### ISSUE TITLE
Clear other waypoints does not work if desto is already in waypoints

### ISSUE THREAD

**Issue by guiguilechat** [esi/esi-issues#778]
# Bug

The flag clear_other_waypoints=true of path https://esi.evetech.net/latest/#!/User32Interface/post_ui_autopilot_waypoint is not respected.

## Request
GET https://esi.evetech.net/latest/ui/autopilot/waypoint/?clear_other_waypoints=true&destination_id={SYSTEM_ID}

## Response

200

### Status Code

200

### Headers

irrelevant.

### Body

200 ok{}

## Expected

The return type is okay.

However, if the target id is already in the route, the route is not cleared even with the flag clear_other_waypoint set to true.

Instead, if the user is connected, he receives an audio "I can't set a waypoint to the same location twice".
From the esi client perspective, there is no error : the route has been set to the given destination, whether the destination was already present or not.

# Checklist

Check all boxes that apply to this issue:

- [x] Bug description is provided
- [x] Request path is provided
- [x] Response status code is provided
- [x] Response headers are provided
- [x] Response body is provided
- [x] Expected response is provided

**Comment by tsuthers-ccpgames** [comment]
This seems to work fine for me, what error are you seeing exactly?

**Comment by guiguilechat** [comment]
Well, there is no error because the gui call does not return anything.

So if I have a route set to Jita-Amarr-Hek.
And I set it to Hek using this call (with clear_other_waypoints = true).
Then it won't do a thing and I won't know it (actually there will be an audio feedback "I can't set a waypoint, to the same destination twice", but the program that sent the ui request will received null)

A fix would be to call clear_waypoint from the esi before sending the add_waypoint whenever clear_other_waypoint is set to true.

**Comment by tsuthers-ccpgames** [comment]
Oh right, I misread the title. Yup, that makes sense and is consistent with what I'm seeing.

**Comment by guiguilechat** [comment]
Yeah, even reading the OP again I was thinking "WTF does this guy mean ?". But since I tried to use it I remembered all the failures and sweat and the anger of this guy.

I should have specified that the issue was the flag clear_other_waypoint was not respected.

**Comment by tsuthers-ccpgames** [comment]
I've submitted a fix for this, should come out tomorrow.

**Comment by tsuthers-ccpgames** [comment]
This has been delayed due to internal patch scheduling decisions, it'll probably bubble through on tuesday.

**Comment by guiguilechat** [comment]
Yeah it's not a critical bug. What solution did you implement ?

**Comment by tsuthers-ccpgames** [comment]
I reordered the code a little to make it clear existing waypoints before testing to see if the provided waypoint was in the current list. It'll still check to make sure the new destination is actually a system before doing the clearing though.

**Comment by tsuthers-ccpgames** [comment]
This is still working it's way through the bureaucracy, it'll probably make it out the door next Tuesday. :grimacing:

**Comment by guiguilechat** [comment]
I can confirm it's working in monolith now, I don't have the "I can't set the destination to the same destination twice" anymore.
I can't remind having seen an official notice of this. Since this is affecting everybody, maybe tell about it in the next patch information ?
"allow to set the destination to a system already in route, thus clearing the route before adding the system"
