### ISSUE TITLE
Invalid 200 response on /characters/{character_id}/chat_channels/

### ISSUE THREAD

**Issue by Foiritain** [esi/esi-issues#786]
# Bug

Pulling the chat channels for my main char (Joshua Foiritain / 1370443714) returns both an error and the data. One of the channels i'm in (The Coil) has 2 npc factions on the allowed list, no other usage of the word faction in the response data.

### Request
/characters/1370443714/chat_channels/
### Response
"Invalid 200 response: 'faction' is not valid, 'faction' is not valid" as well as all the actual data.
### Expected
All the data without the error.

**Comment by CarbonAlabel** [comment]
Shouldn't be a problem anymore.
