### ISSUE TITLE
characters/{character_id}/notifications/ inconsistencies

### ISSUE THREAD

**Issue by ImSuperlative** [esi/esi-issues#790]
# Inconsistency

### Routes
`characters/{character_id}/notifications/`

### Description
All `structure*` events returns `solarsystemID` instead of `solarSystemID`

`TowerAlertMsg` returns `shieldValue: 1.0` 
`structure*` returns `shieldPercentage: 100.0`
`OrbitalAttacked` returns `shieldLevel: 0.9...`

There's a bunch more like `charID` and `characterName` to name a few. Basically every event group uses a different naming scheme.

**Comment by panthernet** [comment]
I've also stumbled upon this today. Would be nice to have consistent field names.

**Comment by jowrjowr** [comment]
i like #1127 for this better anyway because in order to do that (stop using yaml), field names need to stop being moving targets.
