### ISSUE TITLE
404 on npc corp with no LPStore

### ISSUE THREAD

**Issue by guiguilechat** [esi/esi-issues#798]
https://esi.evetech.net/latest/loyalty/stores/1000174/offers/
returns 

  error | "No loyalty point store found for the provided corporation"

Should return an empty list and not a 404.

**Comment by tsuthers-ccpgames** [comment]
Debatable, it also returns this error if you give it something that's not a corporation ID. What's your argument that this shouldn't be a 404?

**Comment by guiguilechat** [comment]
Because 404 means it's a client error, not that the data is empty.
However the client can't know if this specific corporation has LP offers or not without asking this specific URL.
So If I want to know if the corporation has or not some LP offers, I NEED to use this URL and check if I get a 404.
That's how it is now : you want a valid resource and you need to check for 404 ?

It adds overall complexity, error-driven programming for the user, caching issues for the user, and goes against usual programing convention : when you can return an empty list, you return an empty list instead of a null pointer.

It's not even remotely debatable, it's dumb. 404 are meant when the server does not understand the request, not when the resource is empty. What's the next step, when there is only one offer the servers returns a 404 with error message "this corporation has only one offer, please use the path dedicated to 1-offer corporations" ? When I ask you what are you moon stations, you answer "I have none", not "sorry I can't own moon stations - please ask this question to someone else".

**Comment by guiguilechat** [comment]
I understand that present behavior may be the result of the update algorithm in esi : make the table of offers, then group the offers by corporation id, and push each group in the cache. Then of course if there was no offer for a corporation, then there is no group for it, and the cache holds no list.
If that's the case, then the solution is to iterate not over the groups but over the corporations.

**Comment by CarbonAlabel** [comment]
This is a problem because those 404s count against the error limit, but there is no way to know ahead of time whether a corporation returned by https://esi.evetech.net/v1/corporations/npccorps/ has an LP store or not.

The endpoint should only be returning a 404 if someone tries to request LP store offers for a player corporation, or something that isn't a corporation at all.

**Comment by Seavert** [comment]
Alternative solution - add endpoint with list of LP store owners.

**Comment by CarbonAlabel** [comment]
The loyalty store endpoint is now returning an empty array instead of 404 responses.
