### ISSUE TITLE
/universe/post_universe_ids returning unrelated Corporations when submitting Character names to resolve

### ISSUE THREAD

**Issue by DaneelTrevize** [esi/esi-issues#806]
# Bug

### Request
`curl -X POST "https://esi.tech.ccp.is/latest/universe/ids/" -H  "accept: application/json" -H  "Content-Type: application/json" -d "[  \"afk x\"]"`

### Response
`{
  "corporations": [
    {
      "id": 98364532,
      "name": "HaHa Hab dich"
    }
  ]
}`

### Expected
`{
  "characters": [
    {
      "id": 95934406,
      "name": "afk x"
    }
  ]
}`

They exist, as per `https://esi.tech.ccp.is/latest/search/?categories=character&search=afk%20x&strict=true`, https://zkillboard.com/character/95934406/ and Jita local in-game very recently.

**Comment by a-tal** [comment]
that's not an unrelated corporation, that corporation's ticker is 'afk x'. it should be returning both categories though...

we should maybe remove this endpoint anyway though. @ccp-zoetrope thoughts?

@DaneelTrevize for an immediate workaround, use the /search/ endpoint instead:

`curl -X GET "https://esi.tech.ccp.is/latest/search/?categories=character,corporation&search=afk%20x&strict=true" -H "accept: application/json"`

**Comment by DaneelTrevize** [comment]
Gah, this endpoint was added to finally resolve issue #27 which is most needed for Local Scan parsers.

**Comment by ccp-zoetrope** [comment]
Seems this is cache based again because it works correctly the first time you do it but if it pulls from the cache it will only return "HaHa Hab dich". 

@a-tal why should we remove this endpoint?

**Comment by DaneelTrevize** [comment]
Related caching issues: #811

**Comment by Shegox** [comment]
got the same problem, I found out that this happens with 5 char long character (["Latch", "Hungo", "Dalic"]) names in my case. 
The following is what I saw: 
Request: 
```
curl -i --compressed -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' -d '["Latch", "Hungo", "Dalic"]' 'https://esi.tech.ccp.is/latest/universe/ids/?datasource=tranquility&language=en-us'
```
Response: 
```json
{
  "corporations": [
    {
      "id": 98022707,
      "name": "Latchkey Kids"
    },
    {
      "id": 98311751,
      "name": "Im Hungover"
    },
    {
      "id": 98546273,
      "name": "Dallocort Corporation"
    }
  ]
}
```
Expected 3 Character Ids, is there a patch planned or some workaround?

**Comment by iay** [comment]
Observation: those five-character strings are the corporation tickers for the corporations in question.

**Comment by Shegox** [comment]
that makes sense @iay , would be cool in that case to allow a flag to filter for character, or return both values under the characters & corperations names.

**Comment by DaneelTrevize** [comment]
Read up, the first reply was CCP confirming it's tickers-related and that "it should be returning both categories though".

**Comment by ccp-zoetrope** [comment]
@Shegox the real problem here is that both those corporations and the characters should be showing up, but due to a caching problem they are not. A fix is in the works but fanfest craziness has pushed this back a bit.

**Comment by Shegox** [comment]
Any update on this issues? I just tested and got on the first try both (chars and corp) returned, afterwards only the corps. 
As I'm looking to switch from the /search endpoint for mass characterId lookup and reduce the request amount.
@ccp-zoetrope @a-tal

**Comment by jowrjowr** [comment]
running into an instance of this on my side

character: bgtop (92482138)
corp: bgtop (98054246)

what's interesting is the corp isn't actually named bgtop but that is rather their ticker

this is what ESI returns:

```$ curl -d '["BGTOP"]' -X POST "https://esi.evetech.net/latest/universe/ids/"
{"corporations":[{"id":98054246,"name":"The Circus Corp"}]}```

returning everything in the case of degeneracies would be the ideal solution here

the mitigation right now is the search endpoint but that doesn't accept bulk requests

**Comment by WhiteRusssian** [comment]
@ccp-zoetrope , any idea when we should expect this issue to be fixed? Is this a matter of weeks or months?

**Comment by Aidansavage** [comment]
Soon(tm)

**Comment by ccp-zoetrope** [comment]
@WhiteRusssian a fix for this is slated for release so this will be coming out soon

**Comment by a-tal** [comment]
this fix was pushed to prod
