### ISSUE TITLE
v3 corporation wallet journal - some ref types missing basic information

### ISSUE THREAD

**Issue by galister** [esi/esi-issues#809]
# Inconsistency

### Routes
`/v3/corporations/{corporation_id}/wallets/{division}/journal/`

### Description

These 2 ref types are missing basic information about the transaction:

```
{
  "date": "2018-03-18Txx:xx:xxZ",
  "id": 1531218xxxx,
  "ref_type": "reprocessing_tax",
  "amount": 178xxxx.xx,
  "balance": 2005xxxxxx.xxxx,
  "description": "Fee for reprocessing"
}
```

```
{
  "date": "2018-03-13Txx:xx:xxZ",
  "id": 1529319xxxx,
  "ref_type": "corporate_reward_payout",
  "amount": 4500000.0,
  "reason": "",
  "balance": 163597xxxx.xxxx,
  "description": "CONCORD rewarded Character Name for services performed."
}
```

### Resolution

I would expect to see a first party and second party on both entries. Also, the corporate_reward_payout should have the id of the character (named in the description) as context_id.

With these changes, all ref types (that I could check) would be providing both first and second party IDs.

**Comment by cvweiss** [comment]
What, no mention of the missing ref_id?

**Comment by galister** [comment]
the `id` field is equivalent to the old `ref_id`.

**Comment by cvweiss** [comment]
ref_type and ref_id go hand in hand, id has nothing to do with ref_id

**Comment by cvweiss** [comment]
Meh, you're right, I'm referring to ref_type_id which is missing

**Comment by ccp-zoetrope** [comment]
@cvweiss `ref_type_id` is not a an attribute on this route. Maybe you're thinking of `context_id_type`? `first_party_id`, `second_party_id` and `context_id` are never guaranteed to exist. In particular for these two ref_types, they have no `context_id` that comes along with it. 

It would make sense that these have first and second party ID's, so I am keeping this open only to check if those are being snipped out on accident. However, if the data that is being gathered never actually returns first or second party IDs for these ref_types then these two will simply just not come with those unfortunately.

**Comment by galister** [comment]
The `corporate_reward_payout` mentions a character in the description, this character should be the context_id. This is data clearly included as text both here and in-game and without context_id, people are going to just regex capture the name and use the search endpoint to get the same information, which is a waste of resources.

You can also clearly tell that CONCORD is one party and the owner's corporation is the other, wouldn't it make sense to just include that on the entry? Sure you can use logic to figure it out, but this poses the same problem as the previous wallet endpoint version: people need to write if statements to deal with different ref types instead of just being able to display the information that was received.

I've double checked the `reprocessing_tax` type and it doesn't actually show the other party in-game. This makes me sad because all of the other ref types I could find on various corps and characters show both party IDs, but since it doesn't actually show in-game, it's not going to happen on the endpoint either.

**Comment by SpeedProg** [comment]
I think this actually deserves a parity tag since (at least the corporate_reward_payout) has this info in XML :(

Would really be nice to have this fixed before XML goes down

**Comment by ccp-zoetrope** [comment]
The reference types `reprocessing_tax` and `corporate_reward_payout` do not have any `context_ids`, however there was a bug snipping out the `first_party_id` and `second_party_id` for these ref_types which has been removed. 

So, after downtime on May 29th you should start seeing `first_party_id` and `second_party_id` for these ref types to start showing up.

**Comment by ccp-zoetrope** [comment]
I'm going to reopen this as it shouldn't have actually been closed until confirmation that it was showing up :)

**Comment by CarbonAlabel** [comment]
Is this solved now? @ccp-zoetrope

**Comment by ccp-zoetrope** [comment]
As far as I know this is solved, please comment if you personally know that's not the case.
