### ISSUE TITLE
Feature Request: Enhance Character Chat Channels endpoint to also list Approved-status channels

### ISSUE THREAD

**Issue by DaneelTrevize** [esi/esi-issues#815]
# Feature request
The current character's chat channel endpoint lists player channels which the character either is the owner of, or on the operators list for. I am proposing that this list also include the default-access:Blocked channels that the character is on the approved list for.  
(Actually I'd like to have it list all not-default-Allowed access channels for the character, but I'm not sure how trivial that'd be for passworded channels, and I can't remember or find reference to what Moderated default mode does vs blocked, or whether slash commands for setting moderator or operator passwords are valid these days: /chtsetmodpassword & /chtsetoperpassword vs /chtsetpassword).

### Route
As per current: /characters/{character_id}/chat_channels/

### Authentication
Scope as per current: esi-characters.read_chat_channels.v1

### Example returns
*Additional character-related channels in the top-level list of channels returned*

### Use case
This should be a low-complexity mechanism (assuming a sane relational model of operator characterIDs to channelIDs) to provide a more complete list of the actual channels a character can & does access via their game client. An API to access this list can be used to confirm a character has been granted proper rights as per a player organisation/community's hierarchy. E.g. to ensure a new FC has access to an FCs-only channel.

The basic FR implementation need not touch the aspect of channels for which a character has password-based access (or just public access & currently open/has opened in their client), as I suspect they're stored relative to client settings, possibly only client-side, and typically aren't channels managed & used by player organisations in the same manner as ones with in-game visible lists of Allowed/Operators. Feel free to spin that idea off into a FR for something under the /ui/ category of endpoints. Though I would raise the point that channels might want to be considered top-level entities, as they're aspects of corps & alliances and not just tied to or always owned by characters.

P.S. Splitting /{channel_id} filtering FR off into separate issue #818

**Comment by lukasni** [comment]
Chat endpoints have been removed for a while now, can re-visit this if they ever come back and it still applies then.
