### ISSUE TITLE
Feature Request: Enhance Character Chat Channel endpoint to reference who changed channel attributes

### ISSUE THREAD

**Issue by DaneelTrevize** [esi/esi-issues#817]
# Feature request
In-game, characters can see who changes a channel's MOTD as the name is appended when the new MOTD is then echoed/printed in the open chat channel conversation field.  
This request is for comparable API visibility of this meta-data, the simplest incarnation being a single pair of attributes of which characterID changed the channel attributes (MOTD, operators list, etc) and the datetime of when they changed them.

A more complete implementation might be a list/log of each change to attributes, involving which characterID, the datetime, the attributes changed (IIRC several different lists & values can be modified before being applied simultaneously by closing the channel settings window), and their new values.

### Route
As per current: /characters/{character_id}/chat_channels/

### Authentication
Scope as per current: esi-characters.read_chat_channels.v1

### Use case
Various groups (especially NPSI communities operating without Corp/Alliance mechanisms) operate chat channels where their access is to be kept synchronised with external hierarchies, such as all FCs can modify the channel MOTD, or such that a uniform Banned users list matches the blocked characterIDs list. Being able to accurately log & blame the channel attribute changes via an API enables the identification of those characters that break any formatting rules, abuse the banned/muted lists, or attempt to plant alt characters as operators. Being able to generate this log via API rather than by leaving a game client running, logged in and with chat channels open in order to produce client chatlog text files that detail some of this meta-data would be far more efficient for the involved groups, and slightly more efficient for CCP's servers.

### Example returns
Below shows the additional channel attribute of "last_changed", which shows the channel owner as being the characterID that set a new 'silly' MOTD as well as emptying the operators list.
```
[
  {
    "channel_id": -69329950,
    "name": "Players' Haven",
    "owner_id": 95578451,
    "comparison_key": "players'haven",
    "has_password": false,
    "motd": "Silly new MOTD",
    "allowed": [],
    "operators": [],
    "blocked": [],
    "muted": [],
    "last_changed": {
      "changer_id": 95578451,
      "timestamp": "2018-03-27T11:40:00Z",
      "changes": [
        {
          "change_type": "motd",
          "change_value": "Silly new MOTD"
        },
        {
          "change_type": "operators",
          "change_value": []
        }
      ]
    }
  }
]
```

Were a log/list of all (recent) changes to be implemented, this would probably involve a different name for the "last_changed" attribute, as well as making it a list of objects rather than an object. Or moving the changes list to a new endpoint such as /characters/{character_id}/chat_channels/{channel_id}/changes

Suggested esi label: chat_channels (as esi-channels seems to be retired?)

P.S. This FR is of significantly lower quality-of-life improvement than #349 would be, and should be ignored if implementing it would negatively impact the ease & completeness of implementing 349, or at least writable MOTDs from that FR.

**Comment by lukasni** [comment]
Chat endpoints have been removed for a while now, can re-visit this if they ever come back and it still applies then.
