### ISSUE TITLE
Feature Request: Enhance Character Chat Channel endpoint to only detail specific channels

### ISSUE THREAD

**Issue by DaneelTrevize** [esi/esi-issues#818]
# Feature request
I'm not sure that most use-cases of the current /characters/{character_id}/chat_channels/ would actually want to pull all the channelIDs & all related access character lists at once, but rather a single/few specific channelIDs-worth. Being able to narrow the results via a parameter would be nice for ESI servers & clients.

Tangentially it could be very beneficial to have an in-game feature to opt a channel in/out (ideally opt in, channels default out) of being listed via the current /characters/{character_id}/chat_channels/ endpoint.

### Route
As per current: /characters/{character_id}/chat_channels/  
but with a GET parameter of a list of channelIDs (similar to GET /v1/characters/names/ list of character_ids)  
Or:  
/characters/{character_id}/chat_channels/{channel_id}  
for pulling individual channel data. Discovery of all available channel_ids could still come from the current endpoint, or that could be refactored to just list the IDs and not the details.

### Authentication
Scope as per current: esi-characters.read_chat_channels.v1

### Use case
A player group might desire constant external visibility of a single in-game channel's MOTD (e.g. this is the data that drives https://spectrefleet.com/activity/fleets and is polled every 15 minutes, soon to be every 5minutes as per the cache expires timer), yet the API returns an unfiltered list of all channels that a character is owner/operator(/ideally also accessor, see #815) of, which results in the channels list simply being iterated through until the 1 matching channel is found, data isolated, and the rest of ESI's reponse discarded as waste. Being able to specify the channel(s) that are actually desired could benefit both ESI and its users.

### Example returns
*Filtered character-related channels in the top-level list of channels returned, or a single channel object rather than a list of them*. Otherwise as per current for /characters/{character_id}/chat_channels/

**Comment by lukasni** [comment]
Chat endpoints have been removed for a while now, can re-visit this if they ever come back and it still applies then.
