### ISSUE TITLE
Dev Wallet Journal Returning Un-resolvable Party ID

### ISSUE THREAD

**Issue by galister** [esi/esi-issues#839]
# Bug

This is happening on the dev versions:
```
/v4/characters/{character_id}/wallet/journal/
/v3/corporations/{corporation_id}/wallets/{division}/journal/
```

* Entries of ref type `project_discovery_reward` have a `first_party_id` of `500016`.
* Trying to resolve this ID via `v2/universe/names` results in `404` `{ "error": "Ensure all IDs are valid before resolving." }`.

### Expected

* Any `first_party_id` or `second_party_id` should be resolvable via `universe/names`.

**Comment by ddavaham** [comment]
https://esi.tech.ccp.is/ui/#/Universe/post_universe_names

```
Resolve a set of IDs to names and categories. Supported ID’s for resolving are: Characters, Corporations, Alliances, Stations, Solar Systems, Constellations, Regions, Types.
```

[500016 is a faction id](https://i.imgur.com/Cg3kftb.png)

https://gist.github.com/a-tal/5ff5199fdbeb745b77cb633b7f4400bb

**Comment by CarbonAlabel** [comment]
The problem here is that the documentation for the wallet endpoints explicitly directs ESI users to utilize that endpoint for determining the type of the party.

>The id of the first/second party involved in the transaction. This attribute has no consistency and is different or non existant for particular ref_types. The description attribute will help make sense of what this attribute means. **For more info about the given ID it can be dropped into the /universe/names/ ESI route to determine its type and name**

@ccp-zoetrope should probably take a look at this.

**Comment by ddavaham** [comment]
Okay, I apologize, I have been working with the API for so long that I immediately recognized the id as a faction id and knew that `/universe/names/` did not support it. Thanks for catching that @CarbonAlabel

**Comment by jennej** [comment]
I would be thrilled if we could add factions to universe/names. Is there a design reason they have to stay separate? Cause logically, I consider them to be entities like corporations and alliances and thus expect them in names...

**Comment by CarbonAlabel** [comment]
It should be noted that the /universe/ids/ endpoint already supports converting faction names to their respective IDs, it's just the /universe/names/ endpoint that doesn't support the reverse.

**Comment by asvpdev** [comment]
https://github.com/esi/esi-issues/issues/879#issue-317583578

There is still no answer.

**Comment by tsuthers-ccpgames** [comment]
Yep, this is a subticket of 879, linking tickets and closing this one.
