### ISSUE TITLE
List of Responses for Calendar Event not being returned because Event cannot be found

### ISSUE THREAD

**Issue by seraphx2** [esi/esi-issues#841]
# Bug
A valid Event ID is given (used it on "/characters/{character_id}/calendar/{event_id}/" successfully) but no list of responses are returned
### Request
"/characters/{character_id}/calendar/{event_id}/attendees/"
### Response
404: "Event Not Found"
### Expected
List of Character IDs with their response to the calendar event.

**Comment by ccp-zoetrope** [comment]
This was due to the fact that this route only allowed the "owner" of the event to see attendees. However this has been updated so that it works more like it does in client. If you are on the attendee list you should be able to see the event attendees.
