### ISSUE TITLE
Question/documentation: ordering within /characters/{character_id}/notifications/

### ISSUE THREAD

**Issue by BoraVyvorant** [esi/esi-issues#843]
### Route

`/characters/{character_id}/notifications/`

### Description

It would be valuable to have some idea about guarantees for the ordering of notifications returned by this route, so that an application processing notifications doesn't have to keep a long term record of what it has seen in order to avoid processing the same notification twice.

It _looks_ like:

* Notifications are presented in descending order of `notification_id`,
* This corresponds to descending order of timestamp
* If you make another call, you'll probably get the same notifications again with some new ones added to the front.

It would be nice to have the following guarantees:

* Notifications are presented in descending order of `notification_id`.
* If you make another call, any new notifications added to the front will have larger values of `notification_id`. (I.e., if you get back IDs 5000, 4000, 3000 then next time you will _not_ get 5000, 4500, 3000)

This would allow an application to discard any notifications after the highest-numbered one it has already processed without worrying about duplication or loss.

**Comment by jowrjowr** [comment]
notification IDs are globally unique and increment as they are generated. they don't jump around all over the place in the namespace.

if there's questions about this, feel free to come to #esi on tweetfleet and ask questions.
