### ISSUE TITLE
Item attributes of Mutaplasmid altered modules

### ISSUE THREAD

**Issue by rawrasaur** [esi/esi-issues#847]
# Feature request

Trading the new mutaplasmid modified modules will be annoying unless we can have some sort of way of searching for the attributes of them. Since this will probably not be available in contracts search in game on launch it would be nice if ESI could fill that niche.

### Route

 - `/characters/{character_id}/contracts/{contract_id}/items/`
 - `/corporations/{corporation_id}/contracts/{contract_id}/items/`

### Authentication

Yes.

### Use case

Building internal tools for trading abyssal modules in your corporation or as some sort of eBay for abyssal modules.

### Example returns

I don't know how this _actually_ ties into Dogma, so cannot make an example return yet, will come back with more information.

### Previous XML or CREST route

No

**Comment by tsuthers-ccpgames** [comment]
This endpoint already exists: https://esi.evetech.net/ui/#/Dogma/get_dogma_dynamic_items_type_id_item_id

If you know the type and item_id of an abyssal module, you can see it's attributes. The public contract items endpoint exposes both. We intended to bring this to the private contract endpoints next time we're in the area.
