### ISSUE TITLE
[Feature Request] characters/{character_id}/notifications/

### ISSUE THREAD

**Issue by panthernet** [esi/esi-issues#862]
### Route: characters/{character_id}/notifications/

_Request_
Include **structureName** string information into the **text** property of the notifications related to the structures.  **structureName** should be dated by the notification **timestamp**. Currently, exactly the same logic exists only for new notifications such as **MoonminingLaserFired**. 

_Additional information_
There are constant issues to resolve citadel names by Id supplied in notifications even with citadels I've deployed myself or destroyed citadels. This feature should be secure as notifications require **token** meaning user already have access to the character with the notification containing citadel name at the time of the notification has been generated (literally, old name).

**Comment by BTFO** [comment]
> There are constant issues to resolve citadel names by Id supplied in notifications even with citadels I've deployed myself.

You can only resolve a citadel by `structure_id` if you have docking rights

**Comment by panthernet** [comment]
This is my citadels, why I shouldn't have rights to dock to them?

**Comment by panthernet** [comment]
I don't know when docking check comes into play but the notifications about anchoring and onlining a citadel always returns Forbidden for me. This change will get rid of it if there are no backside issues I haven't forseen.

**Comment by SpeedProg** [comment]
I mean I think you can revoke the owning corps rights to dock to a citadel (or specific characters of the corp) so did you actually check you are on the docking ACL?

**Comment by panthernet** [comment]
Notifications has nothing to do with docking rights. If you've got structure notification it is available to you at any time. And it should contain structure name at the time of the notification timestamp. For example, I think I will not be able to process older notifications for destroyed citadels. I mean the NAME in NOTIFICATIONS are safe as I already have access to those notifications.

Only WHEN user will try to get actual structure data by Id it will require docking rights.

**Comment by ErikKalkoken** [comment]
I think adding structure names to all structure notifications would be a great idea. Currently, your app needs additional scopes and make additional requests to get the structure names, except for the newer moon mining notifications, where they already are included. So apparently CCP agrees that this is a good idea in general.

**Comment by jowrjowr** [comment]
stuff adjacent to this has been repeatedly asked for (by myself and others) and denied explicitly due to GD choices and how ESI is structured to not replicate information.

if bartender thinks this is a good idea it can be re-opened.

**Comment by panthernet** [comment]
Not replicate info and unable to provide it on the other side of the same stick. Looking at how slow is the process of ESI improvements makes me sad.
