### ISSUE TITLE
No endpoint to lookup agents (location & description etc)

### ISSUE THREAD

**Issue by wvdvegt** [esi/esi-issues#863]
# Feature request

There seems to be no endpoint path for retrieving agent data like station_id. It's needed to properly decode notifications for example.
Neither /characters/{character_id}/ nor /universe/names/ do return the info

**Comment by NexusInk** [comment]
imho, the Agency service would be welcome to be released as part of the esi

**Comment by lukasni** [comment]
Closing this in favour of #1064
