### ISSUE TITLE
/industry/jobs/ for characters or corporations doesn't return completed jobs

### ISSUE THREAD

**Issue by Zifrian** [esi/esi-issues#875]
# Bug
https://esi.tech.ccp.is/latest/characters/{char id}/industry/jobs/?datasource=tranquility&include_completed=true&token={mytoken}

Returns an empty set. I had a job running that would show without the flag set, but when set nothing returned. Additionally, setting it to false also returns an empty set even if there are active jobs.

### Expected

Call should return jobs that are completed or not depending on the flag set. Additionally, the status field should indicate what jobs are which.

**Comment by Zifrian** [comment]
Hmm, maybe this is an Omega vs basic account thing? I'm not subscribed as an Omega right now so maybe that's it? Would be weird to do though.

**Comment by Aidansavage** [comment]
I strongly doubt it's related to account status. Being an alpha doesnt impact the industry jobs you've done _previously_.
