### ISSUE TITLE
Feature request: Add in /universe/names/ support factions

### ISSUE THREAD

**Issue by asvpdev** [esi/esi-issues#879]
dev/characters/{character_id}/wallet/journal/
**first_party_id** and **second_party_id**

_The id of the first party involved in the transaction. This attribute has no consistency and is different or non existant for particular ref_types. The description attribute will help make sense of what this attribute means. **For more info about the given ID it can be dropped into the /universe/names/ ESI route to determine its type and name**_

#### Reqest
https://esi.tech.ccp.is/dev/characters/**********/wallet/journal/?datasource=tranquility&page=1&token=*************

#### Response

{
    "date": "2018-04-25T06:51:48Z",
    "id": 15450049761,
    "ref_type": "project_discovery_reward",
    "description": "Reward given for scientific contribution to Project Discovery.",
    "first_party_id": 500016,
    "second_party_id": **********,
    "amount": 1514700,
    "reason": "",
    "balance": ********.**
  },

#### Reqest

curl -X POST "https://esi.tech.ccp.is/dev/universe/names/?datasource=tranquility" -H "accept: application/json" -H "Content-Type: application/json" -d "[500016]"

#### Response

{
  "error": "Ensure all IDs are valid before resolving."
}

#### Expected

[
  {
    "id": 500016,
    "name": "Servant Sisters of EVE",
    "category": "faction"
  }
]

#### Reqest
https://esi.tech.ccp.is/dev/universe/factions/?datasource=tranquility&language=en-us

#### Response
{
    "faction_id": 500016,
    "name": "Servant Sisters of EVE",
    "description": "The Sisters of EVE are mainly known for their humanitarian aid efforts to those suffering because of war, famine or even just being lost in space. But the Sisters of EVE base their existence on strong religious beliefs, which they have coupled with scientific facts. They believe that the EVE gate is a gateway to heaven - that god resides on the other side of the gate. As well as dedicating themselves to aiding those in need they are also busy with scientific experiments around the EVE gate, hoping to gain a better understanding of the forces at work there.",
    "size_factor": 3,
    "station_count": 48,
    "station_system_count": 38,
    "is_unique": true,
    "solar_system_id": 30001978,
    "corporation_id": 1000130
  },

**Comment by GoldenGnu** [comment]
This should be marked parity, as it was possible in XML.
It was already plan but got lost, as it was attached to another issue, that was closed.
See: https://github.com/ccpgames/esi-issues/issues/736

**Comment by tsuthers-ccpgames** [comment]
related: https://github.com/esi/esi-issues/issues/839

**Comment by tsuthers-ccpgames** [comment]
I've got a patch in review for this, hopefully I'll be able to get it out some time next week.

**Comment by tsuthers-ccpgames** [comment]
on track for thursday release.

**Comment by CarbonAlabel** [comment]
Seems to be working.

**Comment by asvpdev** [comment]
Yes. Works. Thanks.
