### ISSUE TITLE
Killmail and fitting endpoints still using location flag IDs

### ISSUE THREAD

**Issue by CarbonAlabel** [esi/esi-issues#896]
# Inconsistency
The killmail endpoint and the character fittings endpoints still use location flag IDs instead of names.

## Routes
https://esi.evetech.net/ui/?version=dev#/Killmails/get_killmails_killmail_id_killmail_hash
https://esi.evetech.net/ui/?version=dev#/Fittings/get_characters_character_id_fittings
https://esi.evetech.net/ui/?version=dev#/Fittings/post_characters_character_id_fittings

## Resolution
Make the endpoints return location flag enums, as the [assets endpoints](https://esi.evetech.net/ui/?version=dev#/Assets) already do.

# Checklist
- [x] Inconsistency description is provided
- [x] Inconsistent route(s) are provided
- [x] Resolution [will require a version bump](https://ccpgames.github.io/esi-issues/breaking_changes)
- [ ] Resolution [does not require a version bump](https://ccpgames.github.io/esi-issues/breaking_changes)

**Comment by tsuthers-ccpgames** [comment]
The killmail endpoint should be a separate issue from the fittings endpoints, as it will need to be handled quite differently. I'm going to fold this ticket in under https://github.com/esi/esi-issues/issues/1038

Please open a separate issue for the killmails and reference this ticket from there?
