### ISSUE TITLE
Feature request: add type_id paramater to /markets/structures/{structure_id}/

### ISSUE THREAD

**Issue by aldenbe** [esi/esi-issues#903]
# Feature Request

Add a type_id parameter to /markets/structures/{structure_id}/ to filter only those item types, similar to /markets/{region_id}/orders/

## Use case

Any use case that would like to keep tabs on specific item prices in specific citadels. Could be used for manufacturing apps, logistics apps, etc... Easier to filter responses, smaller responses, decreases the need to make multiple requests to handle multiple pages.

## Authentication

No new scopes required

Check all boxes that apply to this issue:

- [x] Feature request description is provided
- [x] Use case exists
- [ ] Feature requires a new route
- [ ] Feature adds data to existing route
- [ ] Feature requires new auth scope
- [x] Feature can reuse existing scope
- [ ] Feature does not require auth
- [ ] Meta feature, applies to all routes

**Comment by aldenbe** [comment]
I would also like the order_type parameter to be able to filter either buy or sell orders only, this is also already implemented in /markets/{region_id}/orders/

**Comment by Aidansavage** [comment]
Generally speaking, filtering is left up to us developers as too fine of a granularity can cause unnecessary load (by rendering the cache irrelevant for example). WRT to structure markets, unless you had an equivalent market share compared to jita, it's not an undue burden for you to filter the results yourself by `type_id`.

Buy&sell are less of an issue imo.

**Comment by CarbonAlabel** [comment]
@Aidansavage the use case described in the issue would be the most applicable to staging citadels of large nullsec blocs, which can and do have incredibly large markets.

**Comment by tsuthers-ccpgames** [comment]
Sorry, but I agree with Aidan. Providing filters on authed endpoints that can only be used by a subset of players lowers our cache hit rate and raises our server-side and DB processing load. We need cache hits to be high and sol/DB load to be low for no rate limits to be a viable policy, so we generally avoid filters on authed endpoints, especially for market stuff.
