### ISSUE TITLE
Return code 420 not documented

### ISSUE THREAD

**Issue by wvdvegt** [esi/esi-issues#915]
# Bug

During testing I probably hit the error count and start receiving undocumented (in swagger) 420 response codes. Googling shows it means something like 'Keep calm'.

### Status Code

`420`

## Expected

Should be documented, I pass all documented response code into my http handler so they do not generate exceptions. As 420 is undocumented it does slip through.

# Checklist

Check all boxes that apply to this issue:

- [x] Bug description is provided
- [x] Response status code is provided
- [x] Expected response is provided

**Comment by wvdvegt** [comment]
Thx, 

But it's still not documented in the swagger definition (where it should imho).

**Comment by a-tal** [comment]
resolved, thanks
