### ISSUE TITLE
Return the NPC faction of any NPC corporation.

### ISSUE THREAD

**Issue by christianrickert** [esi/esi-issues#917]
# Feature Request

Please enable a straight-forward way to identify the NPC faction of any NPC corporation:
I would like to be able to identify both the corporation _and_ the faction of an NPC station,
using the NPC corporation ID.

There is an indirect way to identify a limited number (21) of faction IDs by looking up the _founding corporation?_ IDs in the public information about factions:
>https://esi.evetech.net/latest/universe/factions/
```json
[
  {
    **"corporation_id": 1000035,**
    "description": "The Caldari State is ruled by several mega-corporations. There is no central government to speak of - all territories within the State are owned and ruled by corporations. Duty and discipline are required traits in Caldari citizens, plus unquestioning loyalty to the corporation they live to serve. The corporations compete aggressively amongst themselves and with companies outside the State, resulting in a highly capitalistic society.",
    **"faction_id": 500001,**
    "is_unique": true,
    "militia_corporation_id": 1000180,
    "name": "Caldari State",
    "size_factor": 5,
    "solar_system_id": 30000145,
    "station_count": 1503,
    "station_system_count": 503
  },
```
## Use case

Anybody participating in market trading from a NPC station, who wants to calculate the (standing-depending) Brokers fee.

## Authentication

A public route, no auth required.

## Example return

The public information about a corporation could easily provide the faction ID as well:
>https://esi.evetech.net/latest/corporations/1000035/
```json
{
  "ceo_id": 3004069,
  "creator_id": 1,
  "description": "The Caldari Navy is smaller in personnel and total ships than both the Federation Navy and the Imperial Navy, yet they have more battleships than any other fleet and the average age of the Caldari ships is considerably less. This is because the Caldari are constantly replacing their oldest ships with newer ones, with better hi-tech equipment. The strategic doctrine of the Caldari Navy is simple: to be able to defeat any other navy in the world. Most experts believe it is.",
  **"faction_id": 500001,**
  "home_station_id": 60003754,
  "member_count": 159,
  "name": "Caldari Navy",
  "shares": 100000000,
  "tax_rate": 0,
  "ticker": "CN"
}
```

# Checklist

Check all boxes that apply to this issue:

- [x] Feature request description is provided
- [x] Use case exists
- [x] Feature adds data to existing route
- [x] Feature does not require auth

**Comment by CarbonAlabel** [comment]
Related to #765.

**Comment by crickert1234** [comment]
@CarbonAlabel Thanks! I read that issue and thought about adding a comment to it. However, the discussion seemed to finally focus on definitions of "allicance_id" vs "faction_id".

**Comment by guiguilechat** [comment]
That most likely mean the feature is not on top of the priority list.

**Comment by crickert1234** [comment]
> That most likely mean the feature is not on top of the priority list.
As much as I would like this enhancement to become reality (it's pretty trivial, isn't it) - fixing bugs and performance issues are always on top of the priority list.
