### ISSUE TITLE
Inventory types - metagroup

### ISSUE THREAD

**Issue by Seavert** [esi/esi-issues#921]
# Inconsistency
Dogma attribute `1692` missing in a lot of (probably all) types named "Tech I", "Tech II" and "Tech III".
## Routes
Missing:
- https://esi.evetech.net/v3/universe/types/5971/ `tech I`
- https://esi.evetech.net/v3/universe/types/440/ `tech II`
- https://esi.evetech.net/v3/universe/types/29984/ `tech III`

Assigned:
- https://esi.evetech.net/v3/universe/types/21476/ `storyline`
- https://esi.evetech.net/v3/universe/types/15759/ `faction`
- https://esi.evetech.net/v3/universe/types/19313/ `deadspace`
- https://esi.evetech.net/v3/universe/types/14648/ `officer`
## Resolution
Add metagroup where possible.
It listed for "Tech I" and "Tech II"  in SDE.
# Checklist
- [x] Inconsistency description is provided
- [x] Inconsistent route(s) are provided
- [ ] Resolution [will require a version bump](https://ccpgames.github.io/esi-issues/breaking_changes)
- [x] Resolution [does not require a version bump](https://ccpgames.github.io/esi-issues/breaking_changes)

**Comment by itshouldntdothis** [comment]
This bug appears to have coincided with the image server removing tech level overlays from some icons, for example, [T2 Damage Control](https://imageserver.eveonline.com/Type/2048_64.png) possibly the same base cause.

**Comment by CarbonAlabel** [comment]
Looking at http://hoboleaks.space/, it seems like these attributes are due to be added to those types on Tranquility in the next patch.

I also could not find those attributes in my copy of the SDE.

Unless there's something I'm missing, ESI is properly returning the attributes of these items as they are currently on Tranquility.

**Comment by Seavert** [comment]
It presented in `invMetaTypes.yaml`.
Both SDE and site above missing T3 ships - not critical untill epoch of something like Tech 3 faction stuff.

**Comment by CarbonAlabel** [comment]
Interesting.

Looks like ESI is only returning that attribute for types where it is explicitly defined as such in the `dgmTypeAttributes.yaml` file from the SDE, and the image server fails to include the tech level indicator for types which (mistakenly?) have that attribute set to zero.

Worth some further investigation.

**Comment by aquarhead** [comment]
>This bug appears to have coincided with the image server removing tech level overlays from some icons

@itshouldntdothis do you know when did this happen? recently or have it been the case for a long time?

---

You should look for the "techLevel" dogma attribute (id 422, for now) regarding tech level information.

The overlapping functionalities of "metaGroup" and "techLevel" will need Game Design to clarify and clean up, ESI returns technically correct information in this case.

If you have specific use cases of this information and/or further questions feel free to grab me (ccp_aquarhead) on the tweetfleet slack.

**Comment by aquarhead** [comment]
Closing this for now.

The ImageSet (image server) will be fixed with next deployment.
