### ISSUE TITLE
Type - time headers

### ISSUE THREAD

**Issue by Seavert** [esi/esi-issues#924]
# Bug
Looks like `Last-Modified` is 1 day delayed.
## Request
https://esi.evetech.net/v3/universe/types/10795/
### Status Code
`200`
### Headers
```
Date: Thu, 17 May 2018 10:05:12 GMT
Expires: Thu, 17 May 2018 11:05:00 GMT
Last-Modified: Tue, 15 May 2018 11:12:13 GMT
```
```
Date: Thu, 17 May 2018 14:30:51 GMT
Expires: Fri, 18 May 2018 11:05:00 GMT
Last-Modified: Wed, 16 May 2018 11:04:07 GMT
```
## Expected
Fresh data and proper time headers.
# Checklist
- [x] Bug description is provided
- [x] Request path is provided
- [x] Response status code is provided
- [x] Response headers are provided
- [ ] Response body is provided
- [ ] Expected response is provided

**Comment by Seavert** [comment]
@NathenSample 
As I know, Last-Modifeid has nothing common with actual change of content, but just time when content was created.
My first request (and endpoint description) say that it had to be cleared in 11:05 today.
And later requests should generate new data with Last-Modifed >=11:05 today.

**Comment by a-tal** [comment]
not necessarily. `Expires` is when the current content _might_ be updated. if after checking you get a new `Expires` but not a new `Last-Modified`, it means the content hasn't changed, and can't change until the new `Expires` time is in the past

**Comment by Seavert** [comment]
@a-tal 
In my particular cases ESI firstly said there wasnt update during `15.05.2018 11:12:13` - `17.05.2018 10:05:12`.
But then it suddenly said that update was in `16.05.2018 11:04:07` - right in first interval.
Is it accepted behavior?

**Comment by a-tal** [comment]
a pod could of restarted, in which case it wouldn't have the correct last-modified time
