### ISSUE TITLE
/characters/{character_id}/opportunites/ always returns 500 for specific character

### ISSUE THREAD

**Issue by deadlybulb** [esi/esi-issues#929]
# Bug

Calling this endpoint with character ID 1801683792 consistently returns 500 with:

{
  “error”: “Unhandled internal error encountered!”
}

## Request

`GET https://esi.evetech.net/latest/characters/1801683792/opportunities/?datasource=tranquility`

## Response

```json
{
  “error”: “Unhandled internal error encountered!”
}
```

### Status Code

`500`

### Headers

```json
{
  "date": "Sun, 20 May 2018 18:18:05 GMT",
  "status": "500",
  "access-control-max-age": "600",
  "strict-transport-security": "max-age=31536000",
  "content-length": "49",
  "x-esi-request-id": "545adbea-031d-4f1c-98a1-ad1fecf3557f",
  "allow": "GET,HEAD,OPTIONS",
  "x-esi-error-limit-reset": "55",
  "vary": "Accept-Encoding",
  "access-control-allow-methods": "GET,HEAD,OPTIONS",
  "content-type": "application/json; charset=UTF-8",
  "access-control-allow-origin": "*",
  "access-control-expose-headers": "Content-Type,Warning,ETag,X-Pages,X-ESI-Error-Limit-Remain,X-ESI-Error-Limit-Reset",
  "x-esi-error-limit-remain": "100",
  "access-control-allow-credentials": "true",
  "access-control-allow-headers": "Content-Type,Authorization,If-None-Match,X-User-Agent"
}
```

### Body

N/A

## Expected

200 with a list of completed opportunities

# Checklist

Check all boxes that apply to this issue:

- [x] Bug description is provided
- [x] Request path is provided
- [x] Response status code is provided
- [x] Response headers are provided
- [x] Response body is provided
- [x] Expected response is provided

**Comment by tsuthers-ccpgames** [comment]
edited ticket name for accuracy

**Comment by deadlybulb** [comment]
Still fails for this character, identical error message as above.  I thought at one point we thought this was only happening with old characters.  This character is at least 8 years old.

**Comment by deadlybulb** [comment]
Also fails with character 90166386, which is of a similar vintage.  I'll try with a newer character.

**Comment by deadlybulb** [comment]
Also fails with character 2112899899.  That's an alpha clone about 1.5 years old.  Apparently this endpoint works for others?

**Comment by tsuthers-ccpgames** [comment]
I see what's happening. It's only breaking in multinode environments.

**Comment by tsuthers-ccpgames** [comment]
I've submitted a fix for this, probably going out next week.

**Comment by deadlybulb** [comment]
awesome, i'll verify then.

**Comment by deadlybulb** [comment]
Verified this works.  Yay!
