### ISSUE TITLE
[dogma] [question] web and propmodules use same attribute speedFactor (id 20)

### ISSUE THREAD

**Issue by guiguilechat** [esi/esi-issues#931]
Both propulsion modules and stasis webifiers use this attribute.

attribute is https://esi.evetech.net/latest/dogma/attributes/20/?datasource=tranquility
webifier II : https://esi.evetech.net/latest/universe/types/527/?datasource=tranquility&language=en-us
10mn II : https://esi.evetech.net/latest/universe/types/12058/?datasource=tranquility&language=en-us

This leads to two theorical issues : 
 - propmod and webs share the "stacking reduction", which means that webs are already stack reduced by the propmod. This means that a 90% dd web is actually 77% reduction if web is active.
 - stasis webifier 's negative effect is considered as "high is good", which means that when a -60% and a -50% web both take effect, the -60% is stack reduced instead of the -50%

I tested on sisi, 
 - inty going 4.1 m/s when webbed down by 4 90% vigilant webs
 - did not gain speed when my sw-300 webbed him
 - was going 28.3 m/s with mwd on, which is expected from the 525/3606 max speed tooltip on the mwd.

So what it means is : the web and and propmod are not actually considered as the same effect.

To me, it looks likes an inconsistency. Someone knows why it is so ?

**Comment by SpeedProg** [comment]
Because you are implying things that are not like that and they have their own stacking.
How is this an esi question?

**Comment by NathenSample** [comment]
Hi @guiguilechat,

It seems that this is likely a mis-understanding/discrepancy within the game itself, rather than specifically ESI.

As such I'm going to close this.

Feel free to grab me in #esi if you disagree.

N

**Comment by guiguilechat** [comment]
@SpeedProg 
Please read my question, I say "it is not how I thought it would work" . Your comment is completely useless.
