### ISSUE TITLE
Assets endpoint not working on Singularity

### ISSUE THREAD

**Issue by CarbonAlabel** [esi/esi-issues#932]
# Bug
Trying to use the character assets endpoint on Singularity produces an error.

## Request
`GET https://esi.evetech.net/dev/characters/93265215/assets/?datasource=singularity`

### Status Code
`500`

### Headers
```http
 access-control-allow-credentials: true 
 access-control-allow-headers: Content-Type,Authorization,If-None-Match,X-User-Agent 
 access-control-allow-methods: GET,HEAD,OPTIONS 
 access-control-allow-origin: * 
 access-control-expose-headers: Content-Type,Warning,ETag,X-Pages,X-ESI-Error-Limit-Remain,X-ESI-Error-Limit-Reset 
 access-control-max-age: 600 
 allow: GET,HEAD,OPTIONS 
 content-length: 49 
 content-type: application/json; charset=UTF-8 
 date: Wed, 23 May 2018 15:39:12 GMT 
 status: 500 
 strict-transport-security: max-age=31536000 
 vary: Accept-Encoding 
 x-esi-error-limit-remain: 100 
 x-esi-error-limit-reset: 48 
 x-esi-request-id: c1190a12-8a09-45a2-af53-19e52706ef6f 
```

### Body
```json
{
  "error": "Unhandled internal error encountered!"
}
```

## Expected
No errors.

# Checklist
- [x] Bug description is provided
- [x] Request path is provided
- [x] Response status code is provided
- [x] Response headers are provided
- [x] Response body is provided
- [x] Expected response is provided

**Comment by ccp-zoetrope** [comment]
We have determined the issue and it's actively being fixed :)

**Comment by tsuthers-ccpgames** [comment]
I forgot to check some important things in, fixing it now :sweat_smile:
