### ISSUE TITLE
Swagger UI cannot use underscore versions of specs

### ISSUE THREAD

**Issue by CarbonAlabel** [esi/esi-issues#933]
# Bug
The UI can be used to open various versions of the swagger spec, but doesn't work with underscore specs.

Working:
https://esi.evetech.net/ui/?version=dev
https://esi.evetech.net/ui/?version=v4
https://esi.evetech.net/ui/?version=meta

## Request
https://esi.evetech.net/ui/?version=_dev

### Status Code
`404`

### Body
```json
{
"error": "Not found"
}
```

## Expected
Work properly.

**Comment by a-tal** [comment]
thanks!
