### ISSUE TITLE
Client ID the Swagger UI uses for Singularity produces account tokens

### ISSUE THREAD

**Issue by CarbonAlabel** [esi/esi-issues#935]
# Bug
When using the Swagger UI to get a scoped access token for Singularity, the SSO skips the authorization step, and returns the user straight to the UI. After that, when trying to use any authed endpoint, the following error is shown:
```json
{
  "error": "SSO response does not contain a character ID",
  "sso_status": 403
}
```

Feeding the token the UI uses directly into the SSO's verify endpoint returns the following:
```json
{
  "ExpiresOn": "2018-05-24T22:51:30",
  "Scopes": "esi-assets.read_assets.v1",
  "UserID": 123456,
  "UserName": "username",
  "TokenType": "User",
  "IntellectualProperty": "EVE"
}
```

Using my own client ID to get an access token for Singularity returns a normal, character-level, token, so the problem is most likely in a misconfigured app used by the UI.

**Comment by tsuthers-ccpgames** [comment]
Fixed
