### ISSUE TITLE
500 Error on previously valid characters

### ISSUE THREAD

**Issue by cvweiss** [esi/esi-issues#936]
# Bug

These previously valid characters are now throwing errors:

https://esi.evetech.net/v4/characters/526961107/
2018-05-25 19:04:02 > 500 526961107 Server error: `GET https://esi.evetech.net/v4/characters/526961107/` resulted in a `500 Internal Server Error` response:
{"error":"Unhandled internal error encountered!"}

https://esi.evetech.net/v4/characters/663528105/
2018-05-25 19:04:02 > 500 663528105 Server error: `GET https://esi.evetech.net/v4/characters/663528105/` resulted in a `500 Internal Server Error` response:
{"error":"Unhandled internal error encountered!"}

526961107: https://evewho.com/pilot/Oya+Bugeisha
663528105: https://evewho.com/pilot/arrugala

## Request

See above.

## Response

See above

### Status Code

`500`

### Headers

N/A

### Body

See above.

## Expected

These once valid links to work and provide information on the character_id's.

`200`

# Checklist

Check all boxes that apply to this issue:

- [X] Bug description is provided
- [X] Request path is provided
- [X] Response status code is provided
- [X] Response headers are provided
- [X] Response body is provided
- [X] Expected response is provided

**Comment by ccp-zoetrope** [comment]
These characters are odd in our system and have been passed to the GMs to be taken care of correctly.

**Comment by ccp-zoetrope** [comment]
Reopening until this has been confirmed to be fixed.

**Comment by cvweiss** [comment]
I've edited the original ticket to make the problem link clickable.

**Comment by ccp-zoetrope** [comment]
This was fixed during today's downtime.
