### ISSUE TITLE
market history

### ISSUE THREAD

**Issue by Seavert** [esi/esi-issues#938]
# Bug
Wrong `Last-Modified` and same `Etag` for different data.
Daily endpoint seems to be recognized as static one.
## Request
`GET /v1/markets/10000002/history/?type_id=44992`
### Status Code
`200`
### Headers
```
Date: Fri, 25 May 2018 12:43:18 GMT
Expires: Sat, 26 May 2018 11:05:00 GMT
Last-Modified: Thu, 24 May 2018 11:25:27 GMT
Etag: W/"cd7bffe045a7fe5025b6ab45b475b0fd99f649854eb6b1f51ce15107"
```

```
Date: Sat, 26 May 2018 12:15:13 GMT
Expires: Sun, 27 May 2018 11:05:00 GMT
Last-Modified: Fri, 25 May 2018 11:07:15 GMT
Etag: W/"cd7bffe045a7fe5025b6ab45b475b0fd99f649854eb6b1f51ce15107"
```

```
Date: Sun, 27 May 2018 14:23:13 GMT
Expires: Mon, 28 May 2018 11:05:00 GMT
Last-Modified: Sat, 26 May 2018 11:02:37 GMT
Etag: W/"cd7bffe045a7fe5025b6ab45b475b0fd99f649854eb6b1f51ce15107"
```
### Body
last day: 2018-05-24

last day: 2018-05-25

last day: 2018-05-26
## Expected
# Checklist
- [x] Bug description is provided
- [x] Request path is provided
- [x] Response status code is provided
- [x] Response headers are provided
- [x] Response body is provided
- [ ] Expected response is provided

**Comment by ccp-zoetrope** [comment]
There is a fix being tested and waiting to be deployed, will update here once that has been done.

**Comment by a-tal** [comment]
this was pushed earlier today. the etags for this route should cycle every downtime going forward
