### ISSUE TITLE
Market Hierarchy endpoint

### ISSUE THREAD

**Issue by fuzzysteve** [esi/esi-issues#940]
# Feature Request

Provide an endpoint to allow for generating the Hierarchy for the market, without getting all categories first

## Use case

People writing market browsers for websites.
People writing information viewers for websites.

## Authentication

A public route, no auth required.

## Example return

For a group with no types in it.
```json
{"groups":[{"groupid":"73","name":"Minmatar"},{"groupid":"74","name":"Amarr"},{"groupid":"75","name":"Caldari"},{"groupid":"76","name":"Gallente"}],"types":[]}
```

For a group with no groups in it.
```json
{"groups":[],"types":[{"typeid":"620","name":"Osprey"},{"typeid":"621","name":"Caracal"},{"typeid":"623","name":"Moa"},{"typeid":"632","name":"Blackbird"}]}
```

https://www.fuzzwork.co.uk/api/marketGroups.php?parent=75 for an example ;) (Working API. I just want it official)

Static data so it's all cachable.

# Checklist

Check all boxes that apply to this issue:

- [X] Feature request description is provided
- [X] Use case exists
- [X] Feature requires a new route
- [ ] Feature adds data to existing route
- [ ] Feature requires new auth scope
- [ ] Feature can reuse existing scope
- [X] Feature does not require auth
- [ ] Meta feature, applies to all routes

**Comment by lukasni** [comment]
would this be served by #937?

**Comment by fuzzysteve** [comment]
Duplicate of #937
