### ISSUE TITLE
Historical PI items displaying in assets

### ISSUE THREAD

**Issue by Dusty-Meg** [esi/esi-issues#943]
# Bug

While requesting a characters assets, Planetary structures are now appearing from planets that have been deleted..
In one occasion from a planet that I used and deleted in 2010.

## Request

`GET /v3/characters/{character_id}/assets/`

### Body

```json
  {
    "is_singleton": false,
    "item_id": 1001052229117,
    "location_flag": "AutoFit",
    "location_id": 40016092,
    "location_type": "other",
    "quantity": 1,
    "type_id": 2848
  },
  {
    "is_singleton": false,
    "item_id": 1001052562605,
    "location_flag": "AutoFit",
    "location_id": 40016092,
    "location_type": "other",
    "quantity": 1,
    "type_id": 2848
  }
```

## Expected

The above items to not be shown on the assets at all, the planet was supposedly decommissioned in 2010.

# Checklist

Check all boxes that apply to this issue:

- [x] Bug description is provided
- [x] Request path is provided
- [ ] Response status code is provided
- [ ] Response headers are provided
- [x] Response body is provided
- [x] Expected response is provided

**Comment by tsuthers-ccpgames** [comment]
I've submitted a change to formalise Gnu's fix in the proc. There are no valid assets located on planets (except arguably your current PI installations which are available through the PI endpoints), so I am simply hiding everything located on planets. Next time there's a server patch they'll all disappear.
