### ISSUE TITLE
Invalid JSON encoding when surrogates are used

### ISSUE THREAD

**Issue by sigilxz** [esi/esi-issues#947]
# Bug

JSON encodings for text fields including Unicode characters needing to be encoded with surrogates appear to be encoded incorrectly.

## Request

`GET /latest/characters/92499803/?datasource=tranquility`

### Status Code

`200`

### Headers

```
Date: Thu, 31 May 2018 13:25:09 GMT
Expires: Thu, 31 May 2018 13:57:32 GMT
Last-Modified: Thu, 31 May 2018 12:57:32 GMT
X-ESI-Request-ID: 605a605e-c7ca-460b-9cf8-74f7e39105c4
ETag: "166247d8fb59408995caefe67104f55270448d75b189c8575cc2c16c"
```

### Body

```json
{"alliance_id":99007237,"ancestry_id":18,"birthday":"2012-10-03T01:05:35Z","bloodline_id":8,"corporation_id":98290394,"description":"<font size=\"12\" color=\"#bfffffff\"><\/font><font size=\"36\" color=\"#ffff0000\">         \u301a<\/font><font size=\"36\" color=\"#ffff00ff\"><b>S<\/font><font size=\"36\" color=\"#ff00ffff\">Y<\/font><font size=\"36\" color=\"#ffffff00\">N<\/font><font size=\"36\" color=\"#ffff00ff\">T<\/font><font size=\"36\" color=\"#ff00ffff\">H<\/font><font size=\"36\" color=\"#bfffffff\"> <\/font><font size=\"36\" color=\"#ffff00ff\">S<\/font><font size=\"36\" color=\"#ff00ff00\">O<\/font><font size=\"36\" color=\"#ff7f007f\">L<\/font><font size=\"36\" color=\"#ff00ff00\">O<\/b><\/font><font size=\"36\" color=\"#ffff0000\">\u301b<br><br><br><br><br><br><br><br>               <br><br>              \ud83d_\udc53<\/font>","gender":"female","name":"Niya Qun Liro","race_id":8,"security_status":-2.1964522317}
```

## Expected

At the end of the description field, the encoding \ud83d_\udc53 is incorrect: there is an extra underscore. The correct encoding is \ud83d\udc53.

# Checklist

Check all boxes that apply to this issue:

- [X] Bug description is provided
- [X] Request path is provided
- [X] Response status code is provided
- [X] Response headers are provided
- [X] Response body is provided
- [X] Expected response is provided

**Comment by lukasni** [comment]
This doesn't look like an encoding issue with ESI but someone deliberately using invalid unicode characters to achieve this effect:

https://i.imgur.com/GAyZ2DY.jpg

Closing this as invalid

**Comment by sigilxz** [comment]
I wouldn't say they did that deliberately, because the combination of the two surrogate characters separated by the underscore does result in a valid Unicode character. 

There are much easier ways to get 'invalid' Unicode characters, and I would expect they would use the same invalid character twice.

However, since it is shown this way in game, I would say that it is likely there is a bug in the client and this is resulting in badly coded data in the database.

I will work around this by not expecting to receive correct UTF-16 from the ESI.
