### ISSUE TITLE
[Discussion] Delaying killmails...

### ISSUE THREAD

**Issue by cvweiss** [esi/esi-issues#948]
I am opening this discussion per the request of CCP Zoetrope.

As the maintainer of zkillboard.com I get approached every few weeks with the question: "Why can't you delay killmails? They provide instant intel on where the action is!" or some variation of that. Full disclosure, I did attempt to provide the service but the [community unilaterally pitchforked me for the implementation of the idea](https://www.reddit.com/r/Eve/comments/5s5ydq/zkb_so_about_delaying_killmails/), and the community is right, delaying killmails if implemented should affect everyone across the board.

Since I do run the current largest killboard, I should at least make an attempt to ask CCP to discuss the concept and notion of delaying killmails for everyone across the board.

**It would work like so**:
* `/characters/{character_id}/killmails/recent/` and `/corporations/{corporation_id}/killmails/recent/` would both be modified to return killmails that are at least one hour old.
* `/killmails/{killmail_id}/{killmail_hash}/` would remain unaffected, allowing anyone with the proper kill_id and hash to manually post a killmail at any time.

**Pros**:
* Those who have API verified themselves and/or their corporation will have less worry about killmails posting quickly and providing intel to the Eve community as a whole.
* It will be more difficult to determine if an entity (character, system, etc.) has been very recently active.
* Feed services that rely on killmails being posted for notification will have to wait an hour for the latest, non-manually posted killmails.

**Cons**:
* Those who have API verified themselves and/or their corporation will not see their killmails post automatically and quickly to third party services, such as zkillboard.
* It will be more difficult to determine if an entity (character, system, etc.) has been very recently active.
* Feed services that rely on killmails being posted for notification will have to wait an hour for the latest, non-manually posted killmails.

As you can see, the pros and cons are very tightly mixed. Personal opinions vary on the subject. Full disclosure: I am all for the immediate public release of a killmail as soon as it happens. However, as a leader in the third party community I will listen and attempt to address the concerns of the user base.

Thoughts? Requests for clarification?

**Comment by deadlybulb** [comment]
Not a fan but I'm also not a massive killboard user.  However, why wouldn't the CSM take up this question?  Feels like a game play question more than anything else.

**Comment by CarbonAlabel** [comment]
I strongly oppose the introduction of any artificial limitations which inhibit the players' ability to use their data, such as the one proposed in this issue.

**Comment by NathenSample** [comment]
The current system is unilaterally fair in that it applies the same logic to everyone.
If you have the kill, zkill displays the kill.
If zkill display the kill, it is available via it's api.

People rely on zkills redisq with the understanding that it's liveTM, tools have been built on top of if that not only let you know of nearby PvP so that you can run away, but also tools let you know there's PvP nearby so you can get involved. Why mess with that ecosystem?

There are groups that benefit from immediate kills, there are groups that would benefit from delayed kills, but considering the system has existed, in its current form, for the past... since inception? I don't see the value in stirring the pot, for the sake of stirring of the pot.

**Comment by jowrjowr** [comment]
this has a pretty straight forward solution: if you do not want your killmails posted immediately, don't post them and don't have corp killmail apis. there are many groups that do this, so it isn't outlandish.

i would personally support an endpoint that is like 1/24/whatever delayed if it was a GLOBAL killmail endpoint, but that's another argument i think.

**Comment by jameson2011** [comment]
Please do not impose kill publication throttling.  Just my two cents from my own narrow view...

I'm just one of those - solo & small gang roaming in lowsec - who depend on lowest possible kill latency. Possible gate camps, target areas, target character activity, amusing losses and other derivations need to come through as quickly as possible. 

Delayed kills can also hurt those PVE people people like me love to hunt. Without RT kills, PVErs have no good intel to deduce a good route through lowsec. They have only the map (such as it is), scouts and pure luck. Without that intel, who can say if delaying will cause a drop in their activity, and by how much? 

Lastly, I'd guess (admittedly without any numbers) that a number of zkb users watch nullsec battles only as long-distance voyeurs - take the recent XIX carnage as an example - without the means nor the will to affect the players involved. Eve's stories are often the best aspect of the game; delaying these stories can only hurt.

**Comment by Seavert** [comment]
I don't see any problems.
You as owner can implement delay, payments, hiding - everything. People decide whether they want to share kill log with such service.
Other apps should not suffer.

**Comment by cvweiss** [comment]
I will make the following points to help clear confusion:

* This would affect CCP's endpoints, not zkill's
* zkill could delay what it presents, but that doesn't stop other killboards from presenting. Thus the need to make it happen at CCP's endpoints.
* You can choose to not share the killmail, but that doesn't stop the other party from doing the same.

Anyhow, after the number of downvotes present, I'm happy to see that overall everyone is against the idea of delaying killmails.

**Comment by cvweiss** [comment]
After 20 days and (I'm happy to say) little support for delaying killmails, I say we can close this issue. Further discussion can happen, but mostly this is a good resource to point to people to say: "Look, its been discussed and no one wants to do it."

Thank you all for your contributions.
