### ISSUE TITLE
500 error requesting dogma info on abyssal item

### ISSUE THREAD

**Issue by jeronica** [esi/esi-issues#954]
# Bug

When requesting dogma attributes for a contract item, I receive an unexpected 500 error.

I use the "record_id" from contract items endpoint which is what I suspect is the cause. Record_id doesn't seem to refer to anything, and is unusable. Might be better to re-do this ticket as "replace record_id with item_id" in the contract endpoint.

## Request

Be sure to include the HTTP method, path (including version), and any relevant parameters. Please do not include auth tokens. E.g.:

`GET /latest/dogma/dynamic/items/47793/2620331973/`

### Status Code

`500`

### Headers

```
access-control-allow-credentials: true 
 access-control-allow-headers: Content-Type,Authorization,If-None-Match,X-User-Agent 
 access-control-allow-methods: GET,HEAD,OPTIONS 
 access-control-allow-origin: * 
 access-control-expose-headers: Content-Type,Warning,ETag,X-Pages,X-ESI-Error-Limit-Remain,X-ESI-Error-Limit-Reset 
 access-control-max-age: 600 
 allow: GET,HEAD,OPTIONS 
 content-length: 49 
 content-type: application/json; charset=UTF-8 
 date: Wed, 06 Jun 2018 18:15:34 GMT 
 etag: W/"6018411ecbf9138d934022f9a488d36ac4a177b8017d7dfc120ebe9a" 
 status: 500 
 strict-transport-security: max-age=31536000 
 x-esi-error-limit-remain: 100 
 x-esi-error-limit-reset: 26 
 x-esi-request-id: c9aaf285-7969-49f6-aeb2-d000acb959e3 
```

### Body

Please provide the response body, feel free to scrub any opsec details you wish. E.g.:

```json
{
  "error": "Unhandled internal error encountered!"
}
```

## Expected

`200`

Body (from swagger example)
```
{
  "created_by": 2112625428,
  "dogma_attributes": [
    {
      "attribute_id": 9,
      "value": 350
    }
  ],
  "dogma_effects": [
    {
      "effect_id": 508,
      "is_default": false
    }
  ],
  "mutator_type_id": 47845,
  "source_type_id": 33103
}
```

# Checklist

Check all boxes that apply to this issue:

- [x] Bug description is provided
- [x] Request path is provided
- [x] Response status code is provided
- [x] Response headers are provided
- [x] Response body is provided
- [x] Expected response is provided

**Comment by StephenSwat** [comment]
A record ID is not the same as an item ID which is what `/dogma/dynamic/items/{type_id}/{item_id}/` expects. Abyssal module item IDs look like `1027796877509`. Currently, there is no way to retrieve the item ID from a contract. See #951.

**Comment by GoldenGnu** [comment]
It was briefly discussed in #esi why record_id is returned when it’s not an item_id. I would like to point out that it’s to ensure global uniqueness. I’m all in favor of replacing it with an item_id (if possible), but, don’t remove it until there is an alternative to ensure global uniqueness.

**Comment by ccp-zoetrope** [comment]
A fix for this has been staged in the monolith and instead of returning a 500 this will now return a 400 with "Invalid item ID". I will update this issue once the fix has been deployed.

**Comment by ccp-zoetrope** [comment]
This was deployed today and works now returns a 400.
