### ISSUE TITLE
Bookmark copy endpoint

### ISSUE THREAD

**Issue by Ligraph** [esi/esi-issues#96]
A post endpoint to copy a bookmark from some character or corp's folder to another character or corp's folder.  Would probably have to work with bookmark ids. 

Could be used to sync corp bms across an alliance...

**Comment by polarina** [comment]
How do you envision authentication being handled in this case? You'd need to be authenticated as both characters simultaneously to allow such a copy.

**Comment by Ligraph** [comment]
Couldn't you just pass both auth tokens?  You would probably have to have 2 auth headers, but it seems like it would be possible?

**Comment by ddouglas493** [comment]
This is no different than with Fittings R/W. You copy and store the data
for the book in a session, cookie, or database and then another user can
log into the system and select the books to write to their account via the
API. I have secretly be yearning for this for for ever. Alliances can use
this to make sure that all of the their corps for a set of bookmarks for
say gate camps and what not that way nobody gets lost and everybody can
warp to a specific bookmark and the FC knows for sure that that corporation
has those bookmarks.

**Comment by Ligraph** [comment]
Thing is, the data would have to be encrypted or somehow made so that people can't make custom bms. 
It might be easier to implement it the way you said (as two endpoints) than the way I mentioned earlier (one endpoint with dual auth).  You could even just use the bookmark id instead of data (the fitting in your example).

**Comment by ddouglas493** [comment]
Damnit, I hate that i have to agree with you from a logical perspective, but it would be awesome if BM could be created this way, but I also understand the advantage and disadvantage/unfair advantage it would give players. ON That note, the Bookmark ID thing i don't think would work unless the endpoint was a explicit copy, you give the bookmark id and it would copy that bookmark to another character, but then you have to deal with random copy request. Inputting a random number, writing it to your account, and then flying to see where it goes?

Am I wrong?

**Comment by Ligraph** [comment]
Actually, that could be even worse because you could **possibly** copy the the bookmark to a character that you have access to, then read the coords  (not sure if the coords are exposed).

Perhaps have a randomized hash "password" as part of the bookmark endpoint that is required to copy it.

**Comment by ddouglas493** [comment]
I don't think there is truly a "secure" way of transferring these bookmarks short of knowingly doing in game. Maybe the dual auth, but I think we have exhausted the subject until a CCP Dev can input on this.

**Comment by lukasni** [comment]
This is made redundant by the new bookmark system, closing in favour of #55 and #69
