### ISSUE TITLE
Models in Swagger spec don't list parameters as required if they are required

### ISSUE THREAD

**Issue by gehnster** [esi/esi-issues#960]
# Bug

There seem to be a number of places where required isn't in the swagger spec when it should be for returned model parameters. This causes issues if you use swagger-codegen to create the models for c# since it makes everything nullable when they shouldn't always be.

## Example API end-point

https://esi.evetech.net/latest/#!/Character/get_characters_character_id

## Current swagger.json for corporation_id field in returned model

```JSON
"corporation_id": {
    "description": "The character's corporation ID",
    "format": "int32",
    "title": "get_characters_character_id_corporation_id",
    "type": "integer"
},
```

## Expected

corporation_id to be required in swagger spec, along with any of places required isn't specified in the spec where it should be

**Comment by ddavaham** [comment]
Fixed formatting of the include json snippet

**Comment by guiguilechat** [comment]
https://esi.evetech.net/_latest/swagger.json

path /v4/characters/{character_id}/
get/responses/200/schema/required/0
= "corporation_id"

thus corporation_id is required.

**Comment by a-tal** [comment]
@guiguilechat is pointing you in the right direction. this is not a bug, use the required array to determine what's required.

**Comment by gehnster** [comment]
How am I supposed to use the required array to determine what's required in regards to using swagger-codegen?

**Comment by gehnster** [comment]
ok yeah looks like swagger-codegen isn't generating the models correctly. Shows as required in their online editor but generated code still is nullable. Thanks
