### ISSUE TITLE
[meta] Provide wiki link in README with mention of word wiki

### ISSUE THREAD

**Issue by cvweiss** [esi/esi-issues#963]
Provide a link to the new wiki in the README with a blurb that uses the word wiki as part of it. Existing links in forums, such as https://github.com/esi/esi-issues/wiki/Useful-Formulae#skillpoints are not forwarded properly, leaving the end user flailing in frustration and throwing coffee at the screen and yelling at non existent cats. Or that might just be me.

**Comment by a-tal** [comment]
there's a documentation section at the bottom of the readme for this?

**Comment by cvweiss** [comment]
Yes, but it isn't apparent that this documentation section is replacing the wiki, especially for someone coming in from some other location and seeing an unexpected list of files.

**Comment by cvweiss** [comment]
I like the "don't make me think" methodology of doing things, and this makes me have to think to find where I was supposed to go...

**Comment by cvweiss** [comment]
Wiki appears to no longer be available, closing issue.
