### ISSUE TITLE
POST character/mail responds with 504 but sends the mail ingame

### ISSUE THREAD

**Issue by bahrmichael** [esi/esi-issues#965]
# Bug

When executing a POST request to `/v1/characters/<id>/mail/` I received 504s with the body `{"error": "No reply within 10 seconds"}`. However some of the mails **were actually sent ingame**. As my app retries after server errors, this caused spam mails (~9000 errors and ~1000 mails sent ingame).

## Request

`POST /v1/characters/{character_id}/mail/`

### Status Code

`504`

### Headers

Errors started at 2018-06-14 00:28:57,369.

Reproduced in Postman:
```
Access-Control-Allow-Credentials →true
Access-Control-Allow-Headers →Content-Type,Authorization,If-None-Match,X-User-Agent
Access-Control-Allow-Methods →GET,POST,HEAD,OPTIONS
Access-Control-Allow-Origin →*
Access-Control-Expose-Headers →Content-Type,Warning,ETag,X-Pages,X-ESI-Error-Limit-Remain,X-ESI-Error-Limit-Reset
Access-Control-Max-Age →600
Allow →GET,HEAD,OPTIONS,POST
Connection →keep-alive
Content-Length →55
Content-Type →application/json; charset=UTF-8
Date →Thu, 14 Jun 2018 05:37:38 GMT
Strict-Transport-Security →max-age=31536000
X-Esi-Error-Limit-Remain →100
X-Esi-Error-Limit-Reset →22
X-Esi-Request-Id →a43ca68d-5b85-4525-a190-cd81eba9e95e
```

Prod (apparently no request-id):
```
Status: 504
Body: {"error": "No reply within 10 seconds"}
Headers: 
access-control-allow-credentials:[true], 
access-control-allow-headers:[Content-Type,Authorization,If-None-Match,X-User-Agent], 
access-control-allow-methods:[GET,POST,HEAD,OPTIONS], 
access-control-allow-origin:[*], 
access-control-expose-headers:[Content-Type,Warning,ETag,X-Pages,X-ESI-Error-Limit-Remain,X-ESI-Error-Limit-Reset], 
access-control-max-age:[600], 
content-length:[39], 
content-type:[application/json], 
date:[Thu, 14 Jun 2018 07:55:30 GMT], 
strict-transport-security:[max-age=31536000], 
x-esi-error-limit-remain:[99], 
x-esi-error-limit-reset:[30]
```

### Body

```json
{"error": "No reply within 10 seconds"}
```

## Expected

`504` without sending the mail ingame.

# Checklist

Check all boxes that apply to this issue:

- [x] Bug description is provided
- [x] Request path is provided
- [x] Response status code is provided
- [x] Response headers are provided
- [x] Response body is provided
- [x] Expected response is provided

**Comment by tsuthers-ccpgames** [comment]
This is due to infrastructure issues we're addressing right now. Your request made it to the monolith but you didn't get the thumbs-up message back.

**Comment by cvweiss** [comment]
As this happens to me as well (for over a year, I just learned to accept it), and I'm sure others, shouldn't the bug be kept open for tracking until the overall problem has been corrected?
