### ISSUE TITLE
[BUG] Character Assets responding with Invalid Location ID for Location Type Solar System for item in Asset Safety

### ISSUE THREAD

**Issue by ddavaham** [esi/esi-issues#966]
# Bug

Item in AssetSafety has a `location_id` of `2004` and `location_type` of `solar_system`

## Request

`GET /v3/characters/{character_id}/assets/`

### Status Code

`200`

### Headers

```
 access-control-allow-credentials: true 
 access-control-allow-headers: Content-Type,Authorization,If-None-Match,X-User-Agent 
 access-control-allow-methods: GET,HEAD,OPTIONS 
 access-control-allow-origin: * 
 access-control-expose-headers: Content-Type,Warning,ETag,X-Pages,X-ESI-Error-Limit-Remain,X-ESI-Error-Limit-Reset 
 access-control-max-age: 600 
 allow: GET,HEAD,OPTIONS 
 cache-control: private 
 content-encoding: gzip 
 content-type: application/json; charset=UTF-8 
 date: Thu, 14 Jun 2018 22:41:57 GMT 
 etag: "7db2f2dd6465b695e520ec6a445853dafcbe7c49aef03f8dd6c7a4cc" 
 expires: Thu, 14 Jun 2018 23:28:08 GMT 
 last-modified: Thu, 14 Jun 2018 22:28:08 GMT 
 status: 200 
 strict-transport-security: max-age=31536000 
 vary: Accept-Encoding 
 x-esi-error-limit-remain: 100 
 x-esi-error-limit-reset: 3 
 x-esi-request-id: 9230c7b4-288c-4a4d-a49a-4bad02e7b4e0 
 x-pages: 1 
```

### Body

```json
  {
    "is_singleton": true,
    "item_id": 1027924214371,
    "location_flag": "AssetSafety",
    "location_id": 2004,
    "location_type": "solar_system",
    "quantity": 1,
    "type_id": 60
  }
```

# Checklist

Check all boxes that apply to this issue:

- [X] Bug description is provided
- [X] Request path is provided
- [X] Response status code is provided
- [X] Response headers are provided
- [X] Response body is provided
- [ ] Expected response is provided

**Comment by tsuthers-ccpgames** [comment]
The location ID is correct, but the location type is not. location 2004 is a "#System" type, meaning it is a location for use by the eve system as in software system, as opposed to a solar system.

It's being classified as a solar system because the enum in eve-glue assumes every location with an ID less then 10,000 is a solar system which is totally not correct but easily fixed.

I don't want to have the enum return location_type "system" or "#system" though because it's too easily confused with solar systems. How do you feel about location_type "abstract"? Any better ideas for the enum?

**Comment by ddavaham** [comment]
So the thing I cannot wrap my head around is why is it saying this? The location flag is asset safety, therefore the location I'd and type should corrolate to a station somewhere. Am I wrong? Or is that not the case here?

**Comment by tsuthers-ccpgames** [comment]
So here's the logic of asset safety:

When your station blows up, your stuff goes into asset safety purgatory for 5 days. After that 5 days, you can choose a station to deliver it to. After 30 days, a station is autoselected for you, and your asset safety is delivered there.

During that up to 30 day long purgatory time, the asset is not specifically located anywhere mappable. It is instead kept inside this 2004 asset safety location, which is not anywhere, it's just an organizational concept.

Once the asset gets moved to a station, it is then located inside that station in an asset safety hangar flag until you pay the fee to release it, at which point the hangar flag is changed and it pop into your visible inventory.

**Comment by ddavaham** [comment]
Thank you. That clears it up. I can write that into the logic for ESIknife. Please don't set this to other. Can we go with location_type asset_safety? Or is this not a unique situation?

**Comment by tsuthers-ccpgames** [comment]
There are other abstract locations that are not asset safety, such as the junk yards.

**Comment by tsuthers-ccpgames** [comment]
Was thinking about this some more, I guess there's no reason to be cryptic about the abstract locations. If we're gonna do a version bump I'd be ok with adding a general abstract category and also a specific asset safety category for the 2004 location.

Carbon is right though, we can also fix this without a version bump by moving the abstract locations into the "other" category. Any other strong opinions? @GoldenGnu got thoughts?

**Comment by GoldenGnu** [comment]
Thanks for tagging me on this.
I don't use location_type at all, so this is of little importance to me
I prefer `other` as it's doesn't change the existing enum (AKA avoids a breaking change and version bump).
But, it's just a minor inconvenience if the enum is change (as long as it get a version bump).

**Comment by a-tal** [comment]
this is in staging atm, will push to prod tomorrow morning, just want to let the new stack run for a bit to see if any unrelated issues crop up

**Comment by a-tal** [comment]
something unrelated is holding this back. will reopen and self-assign until a resolution is found. a discussion is ongoing internally, more details to follow.

**Comment by a-tal** [comment]
this was promoted to prod
