### ISSUE TITLE
Make contract endpoint.

### ISSUE THREAD

**Issue by Ligraph** [esi/esi-issues#97]
An endpoint to create a contract.  I assume it would take a list of item ids and maybe stack sizes, along with the rest of the info.

**Comment by rottjr** [comment]
The problem with this is the sanity check that would have to happen in the backend. First you would need to tell it the station and the array of item id's you want to put into the contract. The endpoint would then need to verify that the user has those items and that they are available in that station. Then the endpoint would need to verify skills and open contracts for the user to verify they have contract spots available, finally there would need to be two more information entry points, the first being what kind of contract it is to be (IE: Auction, item exchange, etc.) and second is the contract visability (IE: Private, coporate, alliance). Put this all together and it seems you would end up with a very slow endpoint and would be (in my opinion) making it too easy to do business from your cell phone. I believe CCP is dedicated to not allowing their game to become full of meta-gamers that never have to log in to make isk.

Fly Safe
o7 Pizza Thief

**Comment by HakShak** [comment]
I'm adding this to the backlog as it isn't off the table and is still being discussed internally, but @rottjr has highlighted some of the main concerns.

**Comment by Blacksmoke16** [comment]
I assume this is still on the back burner?

**Comment by jowrjowr** [comment]
Oh, that's an excellent point re comment in: #784 . CCP (aka 'game design') has been pretty explicit about automating gameplay through the API in that it will never happen.
