### ISSUE TITLE
StructureItemsMovedToSafety missing in get_characters_character_id_notifications

### ISSUE THREAD

**Issue by wvdvegt** [esi/esi-issues#971]
# Bug

StructureItemsMovedToSafety missing in get_characters_character_id_notifications output enumeration

Uses 0.8.3 latest

## Request

GET characters/{character_id}/notifications

### Status Code

n/a

### Headers

n/a

### Body

n/a

## Expected

StructureItemsMovedToSafety  to be present in the swagger definition

# Checklist

Check all boxes that apply to this issue:

- [x] Bug description is provided
- [x] Request path is provided
- [ ] Response status code is provided
- [ ] Response headers are provided
- [ ] Response body is provided
- [x] Expected response is provided

**Comment by ccp-zoetrope** [comment]
I am seeing StructureItemsMovedToSafety in the swagger spec for this route under the attribute `type` at https://esi.evetech.net/latest/swagger.json.

**Comment by wvdvegt** [comment]
Clearly looking at an older version of 0.8.3 as when I compare my download from some time ago I see quite some differences. But the issue is apparently fixed.
